### ISSUE TITLE
Running vktrace with validation enabled causes vkreplay to fail.

### ISSUE THREAD

**Issue by mark-lunarg** [LunarG/VulkanTools#1]
Using vktrace on cube --validate will produce the following fatal errors on replay:

`
vktrace -p cube.exe -a --validate -o fred.vktrace
vkreplay -t fred.vktrace
`

Verbose: Enumerated 1 physical devices in the system.
Error: MsgFlags 8 with object 0x7ff94efb9e60, location 1995 returned msgCode 8 and msg vkCreateSwapchainKHR() called with pCreateInfo->imageExtent = (500,500), which is not equal to the currentExtent = (1008,729) returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR().
Error: MsgFlags 8 with object 0x7ff94efb9e60, location 1995 returned msgCode 8 and msg vkCreateSwapchainKHR() called with pCreateInfo->imageExtent = (500,500), which is not equal to the currentExtent = (1008,729) returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR().
Error: Return value VK_ERROR_VALIDATION_FAILED_EXT from API call (vkCreateSwapchainKHR) does not match return value from trace file
VK_SUCCESS.
Error: Failed to replay packet_id 149.

The swapchain layer is logging an error becasue the extents do not match (between trace and replay, on Windows) which causes the vkCreateSwapchain call to fail.

**Comment by ShabbyX** [comment]
> Or alternatively, vktrace could get the window size and write it into the trace file header.

This won't work if a window is resized, and the swapchain is recreated with a different size.

**Comment by karl-lunarg** [comment]
Bump

**Comment by davidlunarg** [comment]
This issues has been fixed.
