### ISSUE TITLE
Problems tracing vkQuake

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#102]
Trying to trace vkQuake on Windows 7, Nvidia graphics, the window comes up and the program stops working.  A small 100k trace file is generated that doesn't do much more than create a window.  Running in the debugger, nothing ever breaks execution, and pausing I see vktrace in MessageStream_BlockingRecv, so it's as if the connection between vkQuake and vktrace drops at some point.  The game redirects stdout, but using a vk_layer_settings file, I can see validation errors over the course of a small run, so layers are capable of being loaded and outputting errors.  The game is available at https://github.com/Novum/vkQuake

**Comment by ardaLunarG** [comment]
After recent changes in Vktrace and vkQuake, trace is working fine. I have tested on Win10 and Linux Fedora. 

I could not try on Win7

**Comment by Tony-LunarG** [comment]
Works for me - thanks
