### ISSUE TITLE
vkVIA: Check for all minor versions

### ISSUE THREAD

**Issue by charles-lunarg** [LunarG/VulkanTools#1061]
Currently VIA makes calls to `vkCreateInstance` with the minimum and maximum version (1.0 and 1.2 usually) it can find on a system. It would be more helpful if it did this for every minor version and report that to the user.

**Comment by davidlunarg** [comment]
The loader doesn't care and doesn't look at what the minor version in specified in vkCreateInstance is, so no matter what minor version is used, the call to vkCreateInstance will succeed. So making this enhancement is probably not worth doing.

Closing.
