### ISSUE TITLE
vkconfig: empty field at end of Vulkan SDKs is concerning

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#1066]
In `vkconfig`, run **Tools->Vulkan Installation Analysis**.  Examine the **Vulkan SDKs** tab:

![via](https://user-images.githubusercontent.com/45772930/89228150-4657e000-d59c-11ea-9066-007cac466320.png)

There's an empty field at the end that is unexpected and looks concerning (like something is missing or misconfigured).

**Comment by richard-lunarg** [comment]
Can you send me the /tmp/vkvia.json file from this system?
This looks like it is a vkvia issue, but the .json file will conform or refute that.

**Comment by lunarpapillo** [comment]
I renamed it to `vkvia.txt` because GitHub apparently doesn't like JSON files.

[vkvia.txt](https://github.com/LunarG/VulkanTools/files/5019223/vkvia.txt)

The important text seems to be here:
```json
    "LunarG Vulkan SDKs": {
        "0": {
            "0": "System Installed SDK",
            "1": "vulkan-sdk",
            "2": "1.2.148.0-1lunarg20.04-1
",
            "3": ""
        }
    },
```

I note that there is an extra newline, which actually makes this an invalid JSON file:
```
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 217, column 1
```

as well as a blank field.  (What a bizarre file, using enumerations as structure indices instead of using lists...)

I note that the **Vulkan Implicit Layers** (and other sections) include blank fields:
```
    "Vulkan Implicit Layers": {
        "0": {
            "0": "/etc/vulkan/implicit_layer.d",
            "1": "Directory does not exist",
            "2": "",
            "3": ""
        },
...
```
but the columns are filled in by other entries, so it doesn't look like something is missing.  (What's supposed to be in this column?)

Maybe adding column headers would make it more clear.

**Comment by christophe-lunarg** [comment]
This is a cosmetic issue of a part of the tool we don't want to support so sorry but we won't fix it.
