### ISSUE TITLE
vkconfig: Add ability to selection compound Debug Action

### ISSUE THREAD

**Issue by jzulauf-lunarg** [LunarG/VulkanTools#1081]
Need a way to specify valid combinations of VkLayerDbgActionBits for the Validation layer presets (Best Practices, Standard, Sync, etc.) .  

While IGNORE is incompatible, the others are combinable.

Specifically, Log/Break and Debug Output/Break (windows only) would be valuable for quickly enabling validation debugging without code/parameter modification.

**Comment by christophe-lunarg** [comment]
Agreed, this is planned for a future version.

**Comment by richard-lunarg** [comment]
It turns out multiple options are permitted for all manner of Khronos validation scenarios. The flag should be a multi-enum instead of an enum.

**Comment by christophe-lunarg** [comment]
Here is what the UI should look like:
![image](https://user-images.githubusercontent.com/62888873/91823181-1e11de80-ec39-11ea-83fd-1c4a4d186c99.png)

**Comment by jzulauf-lunarg** [comment]
Since this is defining a bitmask and Ignore sets no bit 

`VK_DBG_LAYER_ACTION_IGNORE = 0x00000000,`

having ignore as a choice is misleading. 

So we should either skip ignore, or have a single choice level with a nested multi choice (skip ignore would be better)

* Ignore
* Actions
  - [ ] Break
  - [ ] Callback
...

**Comment by christophe-lunarg** [comment]
Very true, filtering this too.

**Comment by christophe-lunarg** [comment]
Part of the work to resolve this issue was done here: https://github.com/LunarG/VulkanTools/pull/1116

@richard-lunarg to make the UI changes part of this.

**Comment by richard-lunarg** [comment]
Addressed with PR #1119
