### ISSUE TITLE
vkconfig: Duplicating a configuration, renaming a configuration is broken in 1.2.148.1

### ISSUE THREAD

**Issue by christophe-lunarg** [LunarG/VulkanTools#1082]
![image](https://user-images.githubusercontent.com/62888873/90254246-bc810000-de42-11ea-84b4-8615ecf935e1.png)

**Comment by christophe-lunarg** [comment]
This is the version 1.2.148.0: 
![image](https://user-images.githubusercontent.com/62888873/90255705-ee936180-de44-11ea-8476-063ce47fd779.png)

So the issue was introduced with last version, I expect by this PR: https://github.com/LunarG/VulkanTools/pull/1070/files

**Comment by richard-lunarg** [comment]
Addressed in pull request #1083
