### ISSUE TITLE
vkconfig: Need better indicator when vkconfig is overriding

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1084]
Originally from @karl-lunarg 

ReallyHappenedToMe Scenario:

I started vkconfig to poke around to see if it did something I was curious about. Satisfied, I just left it running and buried the GUI window or pushed it off into another virtual desktop or whatever.

A few hours later, I ran a completely unrelated Vulkan application and found that it wasn't working as expected. After a long effort to check for having the right things installed, the right environment, the right settings file, etc., I finally remembered that vkconfig was still running. Of course, closing the GUI solved the problem.

Now, what's the best way to keep users from making the same (dumb, perhaps) mistake?

I thought about suggesting some sort of "Apply" toggle, but that is sort of the same as the radio button pair "Fully controlled..." and "Overridden by..."

How about some sort of change in the GUI, like a bright red banner widget or indicator that indicates when vkconfig is actively overriding things, which I guess would be whenever the json file is put in the implicit layer dir.

For example, the text of the "Vulkan Layers Management" text widget could be changed to "Vulkan Layers Management -- ACTIVE" in red bold text when the radio button below it is set to Override. Maybe the background color changed to red?

**Comment by christophe-lunarg** [comment]
Fix with PR #1110
