### ISSUE TITLE
vkconfig: Reset Configurations menu item hidden at first

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1085]
Originally reported by @KarenGhavam-lunarG 

Start vkconfg
Look at drop down under tools (looking for reset configurations). The reset configurations option is not in the dropdown:

FirstTime
![image](https://user-images.githubusercontent.com/58573781/90535427-e12dee00-e148-11ea-84e9-034b15827439.png)

Hover over to help and look at that menu.

Then go back to tools dropdown, and the reset configurations is now visible:

after
![image](https://user-images.githubusercontent.com/58573781/90535472-eb4fec80-e148-11ea-8f7b-b03d7b401d83.png)

**Comment by christophe-lunarg** [comment]
I tried to reproduce this issue with no luck. Tried with scaled screen as well...

That menu is hard coded so it's pretty odd...

**Comment by christophe-lunarg** [comment]
This issue doesn't reproduce on any of my machines probably a machine specific issue.
