### ISSUE TITLE
vkconfig: Don't show Windows only debug actions

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1086]
Reported by @lunarpapillo 

Minor, not new, not a showstopper.

If I understand correctly... Some or all of the validation Debug Action settings only apply to Windows, and do nothing on Linux (e.g. Debug Output, Break, Callback, maybe others).

These should be made obvious in vkconfig, either by removal, listing the settings in the GUI as Windows-only, or by presenting a dialog box if these are selected warning the user that these are no-ops on Linux (and Mac).

**Comment by christophe-lunarg** [comment]
I have changes around to resolve this..

**Comment by christophe-lunarg** [comment]
This issue is fixed with https://github.com/LunarG/VulkanTools/pull/1113
