### ISSUE TITLE
vkconfig: can't find vkcube automatically on Linux when run from terminal

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1088]
On Linux when run for the first time using the apt update method of installing the SDK, the first time vkconfig is run, it does not find vkcube to setup for the default application.

This does NOT occur for tarball SDK installations, when vkconfig is run from the tarball extracted folder. Only for the apt upgrade method when vkconfig is started for the first time on the command line.

Likely cause is the current working directory is searched, which is whatever the current folder is on the terminal environment.

**Comment by johnzupin** [comment]
I am seeing this behavior on ubuntu bionic 18.04 but not on ubuntu focal 20.04

On ubuntu 20.04 I can see vkcube as the default application. Trying to debug this more but if anyone has 20.04 and can confirm this as well please let me know.

**Comment by richard-lunarg** [comment]
@johnzupin It searches the $VULKAN_SDK folder, so make sure that is pointing to the SDK folder as well.

**Comment by johnzupin** [comment]
This was from testing only the packages though so the VULKAN_SDK folder isn't set. Everything should be in system directories.

**Comment by richard-lunarg** [comment]
Where is vkCube installed on Linux when done via packages? We should add this to the search routine that looks for it.

**Comment by johnzupin** [comment]
It will be installed at `/usr/bin/vkcube`

**Comment by richard-lunarg** [comment]
Thanks, so we need to add that to the search path for Linux only.

**Comment by christophe-lunarg** [comment]
Ok, I'll do that!

**Comment by christophe-lunarg** [comment]
This issue is resolved thanks to https://github.com/LunarG/VulkanTools/pull/1171

**Comment by johnzupin** [comment]
Just tested and this looks good
