### ISSUE TITLE
vkconfig: No update to vkcube in launcher with SDK updates

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1092]
Originally from @lenny-lunarg 
Right now, vkconfig will find the vkcube executable on its first time startup and add it to the application launcher menu, but it will never get updated if the vkcube executable no longer exists. I encountered this when going from one pre-release build to another (and I deleted the old one) but the exact same principle should apply to SDK updates. If someone installs a new SDK and uninstalls the old one (which I'd say is quite common), when they launch vkconfig it'll still point to the old (removed) copy of vkcube.

I'll add, though, that this should have no effect whatsoever until the second SDK where vkconfig2 is released. Before that, this should be an esoteric case. You could also argue that it would be nice if vkconfig did a general check to make sure an executable still exists when it loads the saved executable paths on startup.

**Comment by richard-lunarg** [comment]
Having slept on it, and having multiple SDK's installed now, I'm wondering.... do we really ever want to find an app in the list and replace it? I suppose vkcube could be special, but installing a new SDK doesn't actually break this unless they delete the old SDK. If they do, the end user would realize they need to change the vkcube path. 99.99% of the time, no one is going to use vkcube either for testing layer configurations, it's only there initially as a set of training wheels to show the user how to use the tool.

I could be wrong... but we might could just leave this be.

**Comment by christophe-lunarg** [comment]
vkcube is also here to double check that things are working. Also, we should probably use a relative path for vkcube so that with a new version it would use the new SDK vkcube

**Comment by christophe-lunarg** [comment]
This issue is resolved thanks to https://github.com/LunarG/VulkanTools/pull/1112.

- We update the default applications when the executable don't exist anymore. (The user removed the old SDK)
- The list is updated using relative path, so the version of vkcube will be the one from the same SDK as the vkconfig.
