### ISSUE TITLE
vkconfig: User should be able to reorder configurations in the list

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1093]
From @lunarpapillo 
Validation - Standard should be the first configuration in the list, as it is described as "a good default setting and shoul dserve most needs most of the time".

There should be a configuration for gfxreconstruct capture.

from @christophe-lunarg 
I think the user should be able to reorder the configurations which is not the case right now...

**Comment by richard-lunarg** [comment]
I really think alphabetical is best... another view. if the list becomes long it will be unwieldy to find configs by scrolling.

**Comment by christophe-lunarg** [comment]
I am not convinced alphabetical is best. Alphabetical is most likely meaningless for the user but this seems to be a very minor issue at the moment, long lists are not really a common thing right now and actually thanks to a better use of presets, the default list will be reduced to 3 configurations.
