### ISSUE TITLE
vkconfig: Needs an automated testing system

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1094]
From @christophe-lunarg 
We are planning to make vkconfig a relevant and essential tool for the community, the tool requires to be reliable over time: We need runtime tests.

**Comment by christophe-lunarg** [comment]
This issue is revolved with the elements of this card: https://github.com/LunarG/VulkanTools/projects/2#card-43444934

Adding more tests and refactoring the code to make it easier to test with unit test still in progress.
