### ISSUE TITLE
vkconfig: No feedback when a layer fails to load

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1096]
From @dustin-lunarg 
It is possible for layers that are enabled by vkconfig to fail to load. There is currently no feedback from vkconfig to indicate that this happened. The user will see the application launch, but will not be immediately aware that the layer is not active.

One way for a layer to fail to load is for the layer's JSON file to contain an invalid layer path. I experienced this issue when editing the GFXReconstruct layer's JSON file to change the "library_path" value to reference a local debug build of the layer.

The following actions could be performed to detect this case:

The layer file specified by the JSON file's library_path setting could be verified when the application is launched (e.g. check that library exists, has correct access permissions, has correct architecture).
Set VK_LOADER_DEBUG and process the loader output to determine if the layer was or was not loaded.
The loader could also return VK_ERROR_LAYER_NOT_PRESENT from vkCreateInstance for this case to prevent the application from running if the layer is not found.

From @christophe-lunarg 
@charles-lunarg to have a look, this is not expected, we should have an error generated / logged.

From @charles-lunarg 
After some testing, it became apparent that the loader error messages are pass on if the application has a debug callback setup. VkCube requires the --validate argument to enable it, and once enabled reports a missing layer (or any other error message from the loader).

What that really means is that this is a question of whether we want to rely on the debug callback being inside the application, figure out a way for loader errors to get dumped to stdout/stderr, or make vkconfig check layer validity before launching.

From @christophe-lunarg 
stdout
file
debug callback
Visual Studio debug output.
This list is based on the list of possible output from currently layers implementation. Not saying this list is relevant or exhaustive.

I'll implement the solution from @dustin-lunarg with Vulkan Configurator launcher using vkCreateInstance

However, I think the loader should emit a proper error messages and that we should have a way to control where this message is emitted.

from @charles-lunarg 
Currently, the loader doesn't output anything except through the debug callback. This poses a problem as the design of the loader didn't originally have a way to output so we piggy backed off of the debug callback if it was setup.
I would have to look at the validation layers to see how they implement the various output types, to see if there is anything the loader can do to emulate or outright use them.

from @christophe-lunarg 
Ok, in anycase it's not for Siggraph SDK.

from @charles-lunarg 
Ah good then. This is something to discuss with lenny, since hes much more familiar with the subject domain.

**Comment by christophe-lunarg** [comment]
The loader now has loading features so this issue is resolved even if it's not going to be too obvious to see this information.
