### ISSUE TITLE
vkconfig: "Shader Printf" should be "Debug Printf"

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#1102]
What was once called "Shader Printf" was renamed to be "Debug Printf" a couple of weeks before feature launch.  vkconfig should match the rest of the documentation

**Comment by richard-lunarg** [comment]
This is an easy change. The more challenging question @christophe-lunarg , is do we try and make this retroactive to existing installations, or just make the change moving forward?

**Comment by christophe-lunarg** [comment]
Probably something I should fix with my versioning stuff...

**Comment by richard-lunarg** [comment]
@christophe-lunarg That was my thought as well.

**Comment by christophe-lunarg** [comment]
This issue it resolved with #1102
