### ISSUE TITLE
Convert VkConfig synchronization parameters to official _EXT version

### ISSUE THREAD

**Issue by jzulauf-lunarg** [LunarG/VulkanTools#1118]
When [this PR](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2146) is merged... need to convert 

`VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION`

the unofficial name, to

`VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT`

the official extension string name in all configuration parameter generation.

**Comment by jzulauf-lunarg** [comment]
@christophe-lunarg  -- merged.

**Comment by christophe-lunarg** [comment]
This issue is fixed by https://github.com/LunarG/VulkanTools/pull/1121
