### ISSUE TITLE
Remove layer configs that don't work on macOS

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1130]
Both "Validation - GPU-Assisted", an the "Validation - Shader Printf" crash on macOS. MoltenVK does not support the required features of Vulkan for these types of validation to work. Even if the layer could be made to behave more gracefully, these two presets should be removed, but only for macOS builds.

**Comment by christophe-lunarg** [comment]
This issue is fixed with #1133 PR
