### ISSUE TITLE
malloc_debug: +++ ALLOCATION 0xee5c0130 SIZE 47 HAS A CORRUPTED REAR GUARD

### ISSUE THREAD

**Issue by luopan007** [LunarG/VulkanTools#1132]
The Error Log as follow:
malloc_debug: +++ ALLOCATION 0xee5c0130 SIZE 47 HAS A CORRUPTED REAR GUARD
malloc_debug:         allocation[47]  = 0x22  (excepted 0xbb)
malloc_debug:         allocation[48]  = 0x00  (excepted 0xbb)
malloc_debug: Backtrace at time of failure:
malloc_debug:                  #00 pc 00060458  /system/bin/vkreplayer
malloc_debug:                  #00 pc 0004df4a  /apex/com.android.runtime/lib/bionic/libc.so

Follow  the trace, I find this function has some questions:

**_vktrace/vktrace_common/vktrace_platform.c_**

`void AndroidSetEnv(const char* key, const char* val) {
    const char* command = "setprop ";
    const char* space = " ";
    const char* quote = "\"";
    const size_t len_command = strlen(command);
    const size_t len_key = strlen(key);
    const size_t len_space = strlen(space);
    const size_t len_quote = strlen(quote);
    const size_t len_val = strlen(val);
    char* full_command = malloc(len_command + len_key + len_space + len_val + 1); //  len_quote  is not contain, but use in the after
    memcpy(full_command, command, len_command);
    memcpy(full_command + len_command, key, len_key);
    memcpy(full_command + len_command + len_key, space, len_space);
    memcpy(full_command + len_command + len_key + len_space, quote, len_quote);
    memcpy(full_command + len_command + len_key + len_space + len_quote, val, len_val);
    memcpy(full_command + len_command + len_key + len_space + len_quote + len_val, quote, len_quote + 1);

    FILE* pipe = NULL;
    pipe = popen(full_command, "r");
    if (pipe != NULL) {
        vktrace_LogAlways("%s", full_command);
        pclose(pipe);
    }

    free(full_command);
}`

**Comment by KarenGhavam-lunarG** [comment]
It appears this issue is against vktrace/vkreplay. vktrace is no longer part of this repository and has been archived here: https://github.com/LunarG/vktrace

vktrace/vkreplay is no longer under active development or maintenance.

If you are looking for a trace/replay tool, it's replacement which is under active development and maintenance can be found here: https://github.com/LunarG/gfxreconstruct
