### ISSUE TITLE
vkconfig: checkbox configurations in the "Apply only to the selected list of Vulkan applications" window wont persist

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1139]
On Linux using the Linux tar SDK and after setting up the environment variables,

To reproduce the issue: go to the "Applications to override Vulkan Layers" window by checking the box for "Apply only to the selected list of Vulkan applications" and then click the "Edit..." button. "vkcube" and "vkcubepp" should be listed already, thenn remove the checkboxs by clicking on the listed programs and click ok. Repeat the process by clicking the "Edit.." button and try to re-enable those checkboxes. They can't seem to be re-enabled and a warning will come up stating the "Application list to override is empty..."

**Comment by christophe-lunarg** [comment]
This is actually a behavior by design because the Vulkan loader consider an empty list of overridden application has global overriding... This is not ideal but this is due to the Vulkan loader implementation as the message box sort of explains.
