### ISSUE TITLE
vulkan_core.h is missing VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT

### ISSUE THREAD

**Issue by bcollins526** [LunarG/VulkanTools#1140]
```
https://vulkan.lunarg.com/doc/sdk/1.2.148.1/windows/synchronization_usage.html
```
mentions, near the bottom, that synchronization validation may be enabled programmatically, but vulkan_core.h in the latest sdk (1.2.148.1) doesn't include the token in VkValidationFeatureEnableEXT.

**Comment by mark-lunarg** [comment]
The synchronization `VkValidationFeatureEnableEXT `flag was added to Vulkan after the 148 SDK was released.  In that SDK, it could be enabled programmatically via a private extension implemented in the validation layers, or through VkConfig, the layer settings file, or environment variables.  The upcoming SDK will support the `ValidationFeatureEnableEXT `flag natively through the VK_EXT_validation_features extension.

**Comment by bcollins526** [comment]
Ah ok, so just need to wait for the next SDK release then, thanks.
