### ISSUE TITLE
vkconfig: renaming a duplicate layer config to the back to the original causes segfault

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1144]
[Environment]
Linux - Ubuntu 18.04 using master (b3ba5e20706e7a8aa35c3403f98d398c09f98f6d)

[Steps to reproduce]
- Open vkconfig and duplicate a layer configuration
- Remove the original layer config that was duplicated (one without "duplicate" in the name)
- Choose to rename the duplicated layer config and remove "(duplicate)" from the name with no trailing spaces

Note: Sometimes the segfault is triggered switching between layer configs a couple times after renaming.

**Comment by christophe-lunarg** [comment]
This issue is fixed with PR #1147
