### ISSUE TITLE
vkconfig: clicking anywhere in list enables/disables the row's checkbox

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1153]
[Environment]
Ubuntu 18.04 using xfce (gtk3)

[Steps to reproduce]
- Open vkconfig and select the "Apply only to the selected list of Vulkan applications" checkbox under the "Overriden by the Vulkan configurator" radio button
- Click the "Edit..." button on the right that should now be enabled
- Clicking anywhere on an available application in the list other than the checkbox (such as the app's name). This should enable or disable the checkbox for the row.

![clickrowenablescheckbox](https://user-images.githubusercontent.com/3836693/93227467-a14f2c00-f731-11ea-87c3-fc41cc7d17c7.gif)

**Comment by christophe-lunarg** [comment]
This is no a Linux specific issue.

**Comment by christophe-lunarg** [comment]
This is resolved in Vulkan Configurator 3 \o/
