### ISSUE TITLE
vkconfig: relative and full paths mixed in app override layers list

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1156]
In the "Application to override Vulkan Layers" window, there seems to be a mix of relative and full paths. The initial list of applications is listed as a relative path but adding in an application gives a full path. This can allow the ability to add the same application twice.

![relativeandfullpath](https://user-images.githubusercontent.com/3836693/93233185-04dc5800-f738-11ea-9b6c-e6b9d3939082.gif)

**Comment by christophe-lunarg** [comment]
This one is actually by design.

The idea is that when using a new version of the Vulkan SDK, we want to use the version of vkcube that comes with it. Using the relative path will ensure that.

If applications no longer exist they are also automatically removed from the list.
