### ISSUE TITLE
vkconfig: "Remove custom layer path" button becomes available when choosing a layer

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1158]
- Right click on a layer configuration and choose "Select Layers" 
- Clicking on an actual layer under the path, "Remove custom layer path" button becomes available but doesn't do anything. If I select the path everything works as normal.

![selectlayerstoremove](https://user-images.githubusercontent.com/3836693/93238841-34429300-f73f-11ea-80e0-c7edcfe0a039.gif)

**Comment by richard-lunarg** [comment]
I think the proper behavior should be to display a confirmation dialog. Do you want to remove this path and all associated layers?

**Comment by christophe-lunarg** [comment]
This issue is no longer relevant on the layers window but still relevant on the Custom Paths window:
![image](https://user-images.githubusercontent.com/62888873/93873294-c57eb000-fcd1-11ea-8f54-7abe38f0a689.png)

**Comment by christophe-lunarg** [comment]
This issue is obsolete
