### ISSUE TITLE
Incorrect DisplayServer variable handling in CMake files

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#116]
VulkanTools supports building support for multiple display systems, Xlib, Xcb, Wayland...

However, the top CMakeLists.txt file only sets single DisplayServer value regardless of how many systems were enabled.  Build fails because in icd/intel/CMakeLists.txt includes & libraries for different display systems are decided based on that single value.  This obviously causes error when required display system libs are missing at linking phase.

Note: vk-*generate.py scripts also takes DisplayServer as arg, but don't do anything with it (besides complaining if its not one of the pre-defined single values, and there are some differences in their pre-defined lists).  Therefore it may be simplest to get rid of DisplayServer variable and just rely on *_FOUND variables for things that CMake actually found the system to support.

**Comment by eero-t** [comment]
Somewhat related to the build issue: cube & cubepp demos do have X11 & Wayland support, but they seem to assume that one is doing configuration & building of VulkanTools separately for Xlib, XCB and Wayland, or that user has development files installed only for one of these platforms.

While demo_init_vk() inits Vulkan for all present platforms, rest of the cube code does that only for one of the XLIB, or XCB, or Wayland options, so that resulting binary will support only the most obsolete platform of them...

**Comment by karl-lunarg** [comment]
> Somewhat related to the build issue: cube & cubepp demos do have X11 & Wayland support, but they seem to assume that one is doing configuration & building of VulkanTools separately for Xlib, XCB and Wayland, or that user has development files installed only for one of these platforms.

cube and cubepp are actually come from the upstream Vulkan-LoaderAndValidationLayers repo.  There is work in progress going on there that will address this problem.  In short, the current direction is to provide a new CMAKE variable that affects building only the demos (cube/cubepp) and will select one and only one display target on Linux.  That way, the user can build cube/cubepp for whatever display system they need.

> Build fails because in icd/intel/CMakeLists.txt

We're in the process of removing this component - the icd.  It is now obsolete and there are other better open source drivers available.  So, I suspect this build issue will go away when the icd is removed.

**Comment by karl-lunarg** [comment]
> Therefore it may be simplest to get rid of DisplayServer variable and just rely on *_FOUND variables for things that CMake actually found the system to support.

We tried this and there are still dependencies;  we don't think it is a big problem to leave it in place.  Note that some of these files are downstreamed from the LVL repo, where they may need this variable.

**Comment by karl-lunarg** [comment]
We'll go ahead and close this.
You can use the CMake var BUILD_ICD=NO to inhibit building the ICD to get around any Display Server issues (as well to emulate the eventual deletion of the ICD).
Also, fixes to cube/cubepp are in progress from LVL.
If you have any specific issues that you need fixed in the meantime, please open a new issue that contains the specific request.

**Comment by eero-t** [comment]
Git version from few days ago built fine. -> verified
