### ISSUE TITLE
vkconfig: Support khronos_validation.duplicate_message_limit

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1174]
According to this document (see page 4. "Message Repetition Limit"), the Khronos Validation Layer has a new setting to limit the number of times a given validation message will be displayed.

https://www.lunarg.com/wp-content/uploads/2020/08/Final-ValidationLayerErrorReportingImprovements_08_20.pdf

The document even states that vkconfig can be used to configure this setting. However, vkconfig does not actually have this setting exposed currently.

**Comment by christophe-lunarg** [comment]
Great finding! We are right into the conceptual issue of current vkconfig :/

**Comment by christophe-lunarg** [comment]
This issue is resolved with PR #1174 This PR is an horrible hack that requires a lot of refactor to resolve it that will be done as part of the integration of settings definition (and not settings assignation) within the layer Json file.

This is P0 priority for net SDK release.
