### ISSUE TITLE
vkconfig: F10 hotkey to initaiate capture of gfxrecon trace could be troublesom on windows

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1184]
Enabling the "Frame Capture - Range (F10 to start and stop)" layer configuration and then running vkcube, if you hit F10 vkcube will pause because it might be opening a "invisible menu."

I don't know if there is a better default (maybe something like F5), F10 might be ok to use for games, so this could just be a vkcube problem.

**Comment by christophe-lunarg** [comment]
This issue is fixed by https://github.com/LunarG/VulkanTools/pull/1187
