### ISSUE TITLE
vkconfig: "Capture Specific Frames" is set to 1 when "Frame Capure - Range ..." layer config is set

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1185]
I believe this should have nothing in this "Capture Specific Frames" input by default for this layer configuration.

When "1" is in this input by default then only the first frame is captured and the hotkey to capture a frame range doesn't work.

Manually remove this default "1" in this input gets the correct behavior.

**Comment by christophe-lunarg** [comment]
This issue should be fixed by https://github.com/LunarG/VulkanTools/pull/1187
