### ISSUE TITLE
vkconfig: removing AppData\ config files can cause vkconfig needing to be restarted

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1189]
After removing from the registry `Computer\HKEY_CURRRENT_USER\Software\LunarG\vkconfig` and the directory `%USER%\AppData\Local\LunarG\vkcofnig\`  and trying to start vkconfig:
- If vkconfig is built as Debug an assert window will popup 
![VT-Capture](https://user-images.githubusercontent.com/3836693/94073789-4a8ec580-fdb5-11ea-95db-99b80a1c42c6.PNG)
aborting and reopening vkconfig and everything will behave correctly.
- If vkconfig is built Release/RelWithDebInfo, no assert like the one pictured above will happen after trying to start vkconfig, but applying any of the layer configs takes no effect when trying to run something like vkcube. If vkconfig is restarted then everything behaves correctly.

This may be a non-issue. It could only effect testers.

**Comment by christophe-lunarg** [comment]
I think the issue with removing the registry entry is not valid. Each time the configuration is applied the Registry entry is recreated. No restarted required, I could validated this.

**Comment by christophe-lunarg** [comment]
Regarding removing the AppData area, I am seeing this:
![image](https://user-images.githubusercontent.com/62888873/94148698-3ca17900-fe77-11ea-92e7-8cd4349e7cff.png)

**Comment by christophe-lunarg** [comment]
I think the behavior is actually perfect as the Vulkan developer should not be playing with this directory but I really like that Vulkan Configurator doesn't crash anyway.

**Comment by christophe-lunarg** [comment]
Ok, turns out I dug into it and makes some changes so that if you delete the home directories while running vkconfig, it doesn't matter.

This issue is resolved with #1191
