### ISSUE TITLE
vkconfig: Unexpected Remove button

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1202]
This was found during mac SDK testing but is an potential enhancement for consideration. See original issue [here](https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/521)
When creating your own layer configuration, there's an unexpected space and deactivated **Remove** button, under **Mute Message VUIDs**:

![image](https://user-images.githubusercontent.com/17237544/94747321-c9e34280-033b-11eb-806d-82a58c5356d2.png)

Not sure why this is there, whi it's not active, or what I'm supposed to do to make it active.
@lunarpapillo Found this issue originally.

**Comment by christophe-lunarg** [comment]
The delete button is used to explicitly delete VUIDs. When a VUID is listed and selected, the user can click the delete button.

There are possible UI improvements but this is not a bug.
