### ISSUE TITLE
vkconfig: Should capture both stderr and stdout

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1204]
Originally found by @lunarpapillo during SDK testing. It's an enhancement.

I was using `vkconfig` to execute `vkcube`.  I was mistakenly passing in bad parameters.  There was no indication in the `vkconfig` windows of what had gone wrong (only that the application seemed to start and quickly exit).

If `vkconfig` included `stderr` as well as `stdout` in its log panel, the reasons would have been immediately obvious. There are other situations where being able to see `stderr` would be good as well.

Additionally, it would be nice if the user could select to have one log panel with combined `stdout` and `stderr` output, or two separate panels and/or logfiles for `stdout` and `stderr`.

**Comment by christophe-lunarg** [comment]
This issue was fixed yesterday already as part of this commit https://github.com/LunarG/VulkanTools/commit/ad0d60d0bb5f089e71f050ddc2dbdb218e55e953 fixing vulkaninfo hang
