### ISSUE TITLE
vkconfig: Add button isn't used

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1205]
Originally found during SDK testing by @lunarpapillo 

Under **Mute Message VUIDs**, there is an **Add** button.

This button is not actually intended to be used.  A user should type into the VUID selection box and then select one of the matching VUIDs.

You can use the **Add** button to add arbitrary text to the list of muted VUIDs, but I think this would be useless.

Instead of an **Add** button, I'd recommend placeholder text in the VUID field that says "enter part of a VUID".

**Comment by christophe-lunarg** [comment]
The add button is used to explicitly add a VUID number and not string for example.

There are possible improvements but this is not a bug.
