### ISSUE TITLE
vkconfig causes vk-gl-cts assert

### ISSUE THREAD

**Issue by tpalli** [LunarG/VulkanTools#1212]
I was running vk-gl-cts and noticed I'm hitting following assert:
external/vulkancts/framework/vulkan/vkQueryUtil.cpp:410

When vk-gl-cts made calls to vkEnumerateDeviceExtensionProperties() what happened is that our driver (Intel anv) returned a value which then got bumped up by something injected by vkconfig. When I changed in vkconfig that "apps are in control" then the value was back to normal. This means that something in that wrapping might not be working correctly?

**Comment by tpalli** [comment]
In case of having assert in a different line (with different checkout), here the assert line as is:
TCU_CHECK((size_t)numExtensions == properties.size());

**Comment by christophe-lunarg** [comment]
Hi!
Vulkan Configurator doesn't too anything to the layers. It doesn't injected anything, it just configures the layers with the settings set in the UI.

Would you give us a screenshot of Vulkan Configurator main window when you see the issue to understand the context?

My guess is that configuring differently Vukan Configurator, this issue won't appear.

I suspect that you might be using the devsim layer here which does inject things but this is a wild guess...

**Comment by tpalli** [comment]
I was attempting to use synchronization validation, I workaround previously this issue by selecting layers mgmt to be "Fully controlled by the Vulkan applications".  Now for some reason I'm not able to reproduce this anymore, even when selecting vkconfig to override layer mgmt and enabling synchronization validation. Will keep trying some more, it could be I managed to select such combo of layers that triggers it.

**Comment by tpalli** [comment]
Ok cannot reproduce, I'll get back if this happens again!
