### ISSUE TITLE
vkconfig: layer order ignored

### ISSUE THREAD

**Issue by dor666** [LunarG/VulkanTools#1214]
Steps to reproduce:

0. Install SDK 1.2.154
1. Open vkconfig
2. Click "Select Layers"
3. Pick new name for configuration, ex. "dump+screenshot"
4. Set api_dump as "Overriden / Forced On"
5. Set screenshot as "Override / Forced On"
6. In layer order tree, click on api_dump.
7. Click on "Execute Overridden Layer Closer to the Vulkan Drivers"
8. Click OK.
9. Select saved configuration in "Vulkan Layers Configurations"
10. Open %APPDATA%\..\Local\LunarG\vkconfig\override\VkLayer_override.json and see wrong order in component_layers.

Order in VkLayer_override.json is the same even if I invert order in vkconfig.

**Comment by christophe-lunarg** [comment]
Hi!

You are absolutely right, I could reproduce the issue, I am working on a fix.

**Comment by christophe-lunarg** [comment]
I forgot to close the issue, but it's resolved for December SDK release.

Thanks for reporting!
