### ISSUE TITLE
Measuring performance with vktrace replay

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#122]
There are couple of features which should be easy to add to vktrace and which would help in testing Vulkan performance:
* Output how many frames were played (otherwise it's hard to guess what are good loop start & end frames) and how long that took
* Output min/max/avg FPS at the end of the trace
* If user has specified looping start frame, start measuring FPS only from that frame

**Comment by ardaLunarG** [comment]
We have just added to a new Layer called "Monitor". You can use this layer to see FPS information on any Vulkan App including vkReplay (fps shows up on title bar and works for xcb only for now). For the bullet points, we agree nice to have and considering adding these as options into the Monitor layer.

**Comment by eero-t** [comment]
Sounds great!

Note that while onscreen Monitor information is nice, that's for manual use.  ASCII output from the replay tool is something that can be parsed automatically.

(Apitrace replay tool actually provides also quite a bit of other information too.)

**Comment by ardaLunarG** [comment]
Eero,

Github Issue 129 filed for Monitor layer issues.
Does Monitor layer address the needs for profiling?

If yes, can we close this one?

**Comment by eero-t** [comment]
No.

Monitor layer:
- doesn't currently do *any* of the things requested here
- It's about "current" FPS whereas this ticket is about statistics for the requested frame range
- it doesn't even work for fullscreen use-cases currently

**Comment by justuswang** [comment]
Does #432 address the requirements?

**Comment by eero-t** [comment]
It has everything requested except for the min & max frame timings.  Alternative for that would be having a separate option for printing timing for each of the frames, and/or saving that data at the end of the replay.

GfxBench benchmark suite from Kishonti, outputs time for each individual frame at end of test run, in JSON format.  That or just comma separate values would be easy to post-process.

**Comment by davidlunarg** [comment]
I'll close this issue. If a need for min/max or individual frame timings is identified in the future, please submit a new issue. (Even better, a pull request do just that. :-)
