### ISSUE TITLE
vkconfig: layers not working after clean install

### ISSUE THREAD

**Issue by pc-john** [LunarG/VulkanTools#1221]
Hi and thanks for vkconfig!

Problem: Layers do not work after clean install, independently what I set inside vkconfig.

Details: I installed Vulkan SDK 1.2.154.1 on a clean computer with Windows 10 (no previous Vulkan SDKs). Layers did not work. After half-day investigation, it turned out that the problem is in C:\Users\<user>\AppData\Local\LunarG folder. LunarG folder contains subfolders override and vkconfig. override is empty and vkconfig contains json files ("API dump.json" .... "Validation - Synchronization (Alpha).json"). Looking in Registry: HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers contains the key C:\Users\<user>\AppData\Local\LunarG\vkconfig\override\VkLayer_override.json, and HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\Settings contains C:\Users\<user>\AppData\Local\LunarG\vkconfig\override\vk_layer_settings.txt . Note the difference from the file system. There is no C:\Users\<user>\AppData\Local\LunarG\vkconfig\override folder. Only C:\Users\<user>\AppData\Local\LunarG\override. There seems two possible solutions: either update path in registry to C:\Users\<user>\AppData\Local\LunarG\override or create folder inside C:\Users\<user>\AppData\Local\LunarG\vkconfig with the name override. When I created the override folder and put there empty vk_layer_settings.txt file, all the layers started to work magically after a half of day work. Now vkconfig updates the file based on what I set in GUI. I guess it is simple oversight that could spoil a day of any new Vulkan developer :-).

John

**Comment by christophe-lunarg** [comment]
Hi!

This is a weird one and potentially a bad one. I'll investigate.

**Comment by christophe-lunarg** [comment]
I think this issue is fixed in the master branch already. I am making a new change to ensure we don't end up in a situation where there is no layer configuration.

Thanks for contributing!

**Comment by pc-john** [comment]
Perfect! Good to know it is already fixed.

Very minor note: Maybe if we just faced this issue, it would be useful to update SDK doc (https://vulkan.lunarg.com/doc/sdk/1.2.154.1/windows/vkconfig.html) in the section "OS user-specific modifications", subsection Windows. The paths %TEMP%\VulkanLayerManager\ looks strange. Not sure if C:\Users<user>\AppData\Local\LunarG should replace it or both shall be mentioned there (?). Anyway, %TEMP%\VulkanLayerManager\ points to C:\Users<user>\AppData\Local\Temp and there is no VulkanLayerManager folder there on my Windows 10. But this is just doc comment.

**Comment by pc-john** [comment]
Thanks for the improvement!
