### ISSUE TITLE
Monitor layer gets vkCreateDevice pointer illegally

### ISSUE THREAD

**Issue by lenny-lunarg** [LunarG/VulkanTools#1234]
Inside `vkCreateDevice` the monitor layer gets a pointer to the next layer like:

```c
PFN_vkCreateDevice fpCreateDevice = (PFN_vkCreateDevice)fpGetInstanceProcAddr(NULL, "vkCreateDevice");
```

The Vulkan spec [here](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#vkGetInstanceProcAddr) states that calling `vkGetInstanceProcAddr` with a NULL instance must return NULL for all but a few functions listed out in the spec. As such, a conforming implementation is required to return null here (though no implementation actually does).

The fix is to look up the correct `VkInstance` handle associate with the `VkPhysicalDevice` handle that is passed by this function and to pass that instance handle to `vkGetInstanceProcAddr`.

**Comment by christophe-lunarg** [comment]
Fixed by https://github.com/LunarG/VulkanTools/pull/1255
