### ISSUE TITLE
Vulkaninfo segfault

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#125]
Use-case:
DISPLAY=foobar ./vulkaninfo

Expected outcome:
- complains about not being able to connect to display (windowing system information environment variable may be present although display server is not running, or that info may be wrong)

Actual outcome:
Presentable Surfaces:
-=====================
Segmentation fault (core dumped)

(This is progress, earlier it segfaulted under Wayland even without DISPLAY being set.)

**Comment by ardaLunarG** [comment]
Fixed in [c18eb54](https://github.com/LunarG/VulkanTools/commit/c18eb54c92b625ad2f5d2970eadc53c1d6f55aa5)

**Comment by eero-t** [comment]
Verified.  With this users don't anymore file bugs against drivers when the issue is actually their display setup.
