### ISSUE TITLE
vktrace/vkreplay return exit status 0 even if there are errors

### ISSUE THREAD

**Issue by karl-lunarg** [LunarG/VulkanTools#126]
Observed on Linux; unknown if issue exists on Windows.

If vktrace or vkreplay issue some sort of serious error that causes recording or playback to seriously fail, they still return an exit status of 0.  This makes writing automated tests more difficult, since checking the exit status or using the bash "-e" option isn't useful.

Examples of errors that are issued, but exit status is still 0"

```
vktrace error: Failed to open pagemap file. Fatal error.
vkreplay info: Packet 95: Traced Message (Errors): Failed to open pagemap file. Fatal error.
vkreplay info: Packet 95: Traced Message (Errors): Failed to open pagemap file. Fatal error.
```
It would seem more useful to set exit status to 1 in these situations.

**Comment by davidlunarg** [comment]
Fixed in commit b633f518ec59aa1548863cec59091893df9dd07c. Note this commit only changes vktrace - vkreplay already returned a non-zero status on failure.
