### ISSUE TITLE
Vkconfig builds with a warning

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1274]
Building with GCC 10.2.0, when building vkconfig as a part of the tarball SDK, I get a bunch of warnings. They're essentially the same, and the first one reads:
/home/lenny/1.2.162.0/source/VulkanTools/vkconfig_core/test/test_command_line.cpp: In member function ‘virtual void test_command_line_execute_mode_Test::TestBody()’:
/home/lenny/1.2.162.0/source/VulkanTools/vkconfig_core/test/test_command_line.cpp:30:28: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   30 |     static char* argv[] = {"vkconfig"};
      |
This is just us just casting away const illegally. It should be static const char* argv[] = ...; The other warnings are the same error.

**Comment by christophe-lunarg** [comment]
This was resolved with https://github.com/LunarG/VulkanTools/pull/1273 in master and sdk 1.2.162 branch
