### ISSUE TITLE
vkconfig needs a version

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1275]
This was submitted during 1.2.162.0 SDK testing: 

vkconfig Help->About Vulkan Configurator will tell you the version of Qt being used.  Oddly, it won't tell you the version of vkconfig being used.
An SDK version number, a commit SHA, or another arbitrary internal version number that can be mapped to a particular version of the source would all be useful to provide correct information in bug reports.  (In most cases, having the path to the version of vkconfig being run would be sufficient; but mistakes are possible on machines with multiple SDKs installed, or if the SDK is installed to a location that doesn't include a version number.)

**Comment by richard-lunarg** [comment]
I think we can close this. The vkconfig version number is actually in the caption of the main window (e.g. "Vulkan Configurator 2.1.0<ACTIVE>").
Does anyone think we need more than this? Perhaps a build number? As long as Christophe bumps the last digit at least for minor revisions, I'd think this is fine.

**Comment by christophe-lunarg** [comment]
I am happy to close this too.
