### ISSUE TITLE
vkconfig cuts off radio buttons slightly on windows 10

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1276]
Found by @charles-lunarg during SDK testing:

![image](/uploads/5dc3c289a704e4a31f2b731c71134bb6/image.png)
![image](https://user-images.githubusercontent.com/17237544/101820519-f3f77480-3ae3-11eb-9098-d3bf55ac5254.png)

As you can see, a few pixels on the right are cutoff. i

Minor issue, but didn't want to forget about it.

**Comment by christophe-lunarg** [comment]
This issue is fixed with https://github.com/LunarG/VulkanTools/pull/1279
