### ISSUE TITLE
Vulkan-SDK-Packaging | vkconfig leaves configuration active if exited with ^C

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1277]
Run vkconfig on the command line. In the GUI, select any configuration (e.g. API dump). Use ^C to interrupt the command line.

Then try to run vkcube. The API dump configuration is still active, even though vkconfig has exited and was not configured to have settings persistent on exit.

vkconfig should catch SIGINT and clean up.

**Comment by christophe-lunarg** [comment]
This is a stunning idea which has been resolved with this PR https://github.com/LunarG/VulkanTools/pull/1278
