### ISSUE TITLE
Tracing Talos Principle game: game & Steam abort at game startup

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#128]
Setup:
- Ubuntu 16.04 on SKL GT2
- Today's GIT versions of Mesa & VulkanTools
- Talos Principle game updated in Steam, to today's version
- Following gfx option set in game before tracing: "Vulkan (Beta)" gfx API, FullHD Fullscreen, GPU speed MEDIUM, all other performance options set to HIGH

Test-case:
- Run trace server: vktrace -o talos.vktrace --PMB false
-  On another terminal, start Steam with Vulkan tracing overlay enabled
- From Steam's game properties dialog, set its launch options (to make sure Vulkan is still selected) to: "%command% +gfx_strAPI VLK"
- Start Talos Principle and select 64-bit version

Expected outcome:
- Game starts, same as without tracing overlay

Actual outcome:
- "vktrace_lib library handle signal 6."
- Both game and Steam disappear with message "Aborted (core dumped)" on terminal

**Comment by eero-t** [comment]
Unlike with DOTA2, enabling "--PBM true" doesn't get rid of the signal 6 error (with today's Git versions of VulkanTools & Mesa).

**Comment by eero-t** [comment]
Although DOTA2 has improved a lot, this still aborts.  Is it supposed to work (i.e. game itself doesn't abort if something extra is loaded into its process)?

**Comment by eero-t** [comment]
Besides VulkanTools updates, there was also update to Talos game.

Tracing still crashes to abort immediately on startup.  Steam doesn't anymore die, just the game.

Based on the backtrace it outputs on the console, abort happens in trace layer, not in the game:
```
DBG:  Dumping stack back trace:
DBG:  00007F693044E428 00000001 $adr: "/lib/x86_64-linux-gnu/libc.so.6" 0001:0000000000035428
DBG:  00007F693044E428 00000001 $adr: "/lib/x86_64-linux-gnu/libc.so.6" 0001:0000000000035428
DBG:  00007F693045002A 00000001 $adr: "/lib/x86_64-linux-gnu/libc.so.6" 0001:000000000003702A
DBG:  00007F6930446BD7 00000001 $adr: "/lib/x86_64-linux-gnu/libc.so.6" 0001:000000000002DBD7
DBG:  00007F6930446C82 00000001 $adr: "/lib/x86_64-linux-gnu/libc.so.6" 0001:000000000002DC82
DBG:  00007F691F4CF4C5 00000001 $adr: "dbuild/layersvt/../vktrace/libVkLayer_vktrace_layer.so" 0001:00000000001174C5
DBG:  00007F691F42B130 00000001 $adr: "dbuild/layersvt/../vktrace/libVkLayer_vktrace_layer.so" 0001:0000000000073130
DBG:  00007F691F42AB9C 00000001 $adr: "dbuild/layersvt/../vktrace/libVkLayer_vktrace_layer.so" 0001:0000000000072B9C
DBG:  00007F691F42AC80 00000001 $adr: "dbuild/layersvt/../vktrace/libVkLayer_vktrace_layer.so" 0001:0000000000072C80
DBG:  00007F691F445EA5 00000001 $adr: "dbuild/layersvt/../vktrace/libVkLayer_vktrace_layer.so" 0001:000000000008DEA5
DBG:  0000000001AF974A 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:00000000016F974A
DBG:  0000000001AF6072 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:00000000016F6072
DBG:  0000000001AF7EF3 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:00000000016F7EF3
DBG:  0000000001744A29 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:0000000001344A29
DBG:  00000000008F7DF5 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:00000000004F7DF5
DBG:  00000000008FA12F 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:00000000004FA12F
DBG:  00000000008FAAFD 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:00000000004FAAFD
DBG:  0000000001472B2A 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:0000000001072B2A
DBG:  000000000191BF02 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:000000000151BF02
DBG:  000000000191C1E4 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:000000000151C1E4
DBG:  00007F6930439830 00000001 $adr: "/lib/x86_64-linux-gnu/libc.so.6" 0001:0000000000020830
DBG:  00000000008E663F 00000001 $adr: "/opt/steamapps/common/The Talos Principle/Bin/x64/Talos" 0001:00000000004E663F
DBG:  00007F6930439830 00000001 $adr: "/lib/x86_64-linux-gnu/libc.so.6" 0001:0000000000020830
```

**Comment by eero-t** [comment]
With today's Git version of Mesa & VulkanTools, and latest Talos from Steam (was updated last maybe in December)...

Talos doesn't anymore abort at startup, now it segfaults directly.  Segfault happens also in trace layer:
```
Thread 1 "Talos" received signal SIGSEGV, Segmentation fault.
0x00007fb364093468 in __HOOKED_vkGetInstanceProcAddr () from vktrace/libVkLayer_vktrace_layer.so
(gdb) bt
#0  0x00007fb364093468 in __HOOKED_vkGetInstanceProcAddr () from vktrace/libVkLayer_vktrace_layer.so
#1  0x00007fb364933faa in loader_create_instance_chain () from /usr/lib/x86_64-linux-gnu/libvulkan.so.1
#2  0x00007fb364936aea in vkCreateInstance () from /usr/lib/x86_64-linux-gnu/libvulkan.so.1
...
(gdb) disassemble 
Dump of assembler code for function __HOOKED_vkGetInstanceProcAddr:
   0x00007fb364093240 <+0>:	push   %rbp
...
   0x00007fb364093466 <+550>:	je     0x7fb364093446 <__HOOKED_vkGetInstanceProcAddr+518>
=> 0x00007fb364093468 <+552>:	mov    0x10,%rax
...
(gdb) info registers rax
rax            0x0	0
```

-> NULL pointer access

**Comment by eero-t** [comment]
With latest Talos, and today's Git versions of VulkanTools & Mesa, I was able to get a Talos trace.

This was using (didn't have time to try other ways):
* Medium GPU speed (all other perf options were at Ultra)
* Started 64-bit game with OpenGL and switched it to Vulkan from options

Trace replay worked fairly OK.  There were a lot (every frame?) of both of these warnings:
```
DS(ERROR): object: 0x0 type: 12 location: 4974 msgCode: 15: Cannot get query results on queryPool 0x47 with index 255 which is unavailable.
DS(ERROR): object: 0x2292e00 type: 6 location: 355 msgCode: 6: For image 0x1225 you cannot transition the layout of aspect 1 from VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL when current layout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL.
```

**Comment by eero-t** [comment]
Tested today's git version of VulkanTools & Mesa.

Talos still crashes if started in Vulkan mode with tracing.

By switching to Vulkan once game has started, it still works.  However, now rendering while tracing is broken.

**Comment by davidlunarg** [comment]
Commit 8a24f78a96210523d3b406221f18b6ba6eca5f54 fixes a bug that allows Talos to be traced/replayed on Windows. It might fix this issues you're having on Linux. Could you try it?

**Comment by eero-t** [comment]
```
VulkanTools$ git pull
Already up-to-date.
VulkanTools$ git show 8a24f78a96210523d3b406221f18b6ba6eca5f54
fatal: bad object 8a24f78a96210523d3b406221f18b6ba6eca5f54
```

**Comment by eero-t** [comment]
David, the indicated commit is still missing from VulkanTools repo, but I can now successfully trace Talos even when it starts with Vulkan backend.

There's still a small rendering issue while the game is being traced (and replayed):
* the progress indicator shown in the bottom left corner when game starts (and in middle of screen in some other places), is rendered completely wrong
* similar kind of small broken gfx is left in middle of the screen in the actual game play (and in the benchmark)

Vulkan API validation shows a lot of warnings (same as DOTA2), I don't know whether any of them are related.

As the crash is fixed, I'm fine with closing this (I can file another bug about the rendering issue then).

**Comment by davidlunarg** [comment]
Closing.
