### ISSUE TITLE
Creating a new configuration with .. in the name crashes VkConfig

### ISSUE THREAD

**Issue by charles-lunarg** [LunarG/VulkanTools#1281]
If you create a new config and put `..` in the name, it causes vkconfig to crash.

**Comment by christophe-lunarg** [comment]
This issue has a fix included with this PR: https://github.com/LunarG/VulkanTools/pull/1279
![image](https://user-images.githubusercontent.com/62888873/102244397-893ba400-3efc-11eb-803b-c68e4cb66bf8.png)
