### ISSUE TITLE
vkconfig: Selecting an application from the application dialog is clunky

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1290]
Under macOS, bringing up the "Applications to override Vulkan Layers" dialog while "Apply only to selected list of Vulkan applications", does not allow you to select an application. Checkboxes work, but you cannot change to a new application in the list. This does not occur when the checkboxes are not present, and this does not occur under Windows.

**Comment by christophe-lunarg** [comment]
Great catch! I'll have a look and depending how it goes the fix will go in January SDK but if I find it a little risky that will be for February SDK I think.

**Comment by richard-lunarg** [comment]
Update, this also occurs on Linux builds. I believe I had to use a tree control in this dialog originally because of this. Making the checkbox it's own column, otherwise on the other platforms you can just check them on/off, but not change the selection.

**Comment by christophe-lunarg** [comment]
I noticed this issue only happen when clicking on the text but we can select the applications by clicking at the right on the text so down to P3 but I agree we need to improve this dialog on all platforms.

**Comment by christophe-lunarg** [comment]
This is resolved in Vulkan Configurator 3 \o/
