### ISSUE TITLE
vkconfig: Deleting custom layer path of layer in uses causes a lockup

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1295]
I've produced this on macOS, but likely it is across OS's.
Add a custom layer path with a custom layer.
Create a configuration that uses that layer.
Now, select any configuration, got to "Select Layers" and remove the custom path.
When it returns to the "Select Vulkan Layers" dialog, the custom layer is still shown, but the dialog is non-responsive.

**Comment by christophe-lunarg** [comment]
This issue is fixed thanks to https://github.com/LunarG/VulkanTools/pull/1296

**Comment by christophe-lunarg** [comment]
The bottom line was: trying to set a tool tip to a setting that didn't exist... that launched more investigations about how we handle older layers settings...
