### ISSUE TITLE
vkconfig: devsim json config file not shown when selected

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1298]
Choosing a devsim json file isn't being displayed in the input box. It doesn't seem to be updated when selected, the previous entry is shown.

![input](https://user-images.githubusercontent.com/3836693/102802947-b06af900-4374-11eb-9b98-9f7d1ef44f3d.gif)

**Comment by johnzupin** [comment]
Seeing this on windows as well

**Comment by christophe-lunarg** [comment]
It looks like the UI is not update but the file is properly taken into account.

**Comment by christophe-lunarg** [comment]
This issue is fixed with this PR https://github.com/LunarG/VulkanTools/pull/1302 

It actually concerned all filesystem UI field.
