### ISSUE TITLE
32-bit VIA cannot detect 64-bit Windows

### ISSUE THREAD

**Issue by lenny-lunarg** [LunarG/VulkanTools#131]
When I run the 32-bit version of VIA on a 64-bit Windows installation, the resulting file says that I'm running a 32-bit OS. I've attached a (zipped) sample file, showing this.

[via.zip](https://github.com/LunarG/VulkanTools/files/657988/via.zip)

**Comment by MarkY-LunarG** [comment]
Fixed with commit 83504dd8980ddb42af0ae9b177e0158751aa49f8
