### ISSUE TITLE
vkconfig: corrupts the gfxreconstruct Capture File Name on close/reopen

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#1310]
Steps to reproduce
1. Select "Frame Capture - First two frames" config
2. Use "..." button to set Capture File Name and browse to `C:\Users\Mike\Desktop\gfxrecon_capture.gfxr`
3. Close vkconfig
4. Open vkconfig

Observe
- Error dialog "Cannot find any Vulkan Physical Devices."
  ![no_icd](https://user-images.githubusercontent.com/23323159/103712691-5753b580-4f6f-11eb-8a42-a2fafea384e8.png)
- Capture File Name has now been mangled to `C:\Users\Mikefxrecon_capture.gfxr`
  ![bad_path](https://user-images.githubusercontent.com/23323159/103712980-02646f00-4f70-11eb-9e1e-5648f7682639.png)

Running vulkaninfo while in this state reveals that setting the capture file option to a non-writable path is causing all calls to vkCreateInstance to fail (this is intentional on the part of the capture layer to alert developers of the config issue). I suspect this is what is causing the ICD errors.

```
[gfxrecon] INFO - Found layer settings registry key: HKEY_CURRENT_USER\Software\Khronos\Vulkan\Settings
[gfxrecon] INFO - Found layer settings file: C:\Users\Mike\AppData\Local\LunarG\vkconfig\override\vk_layer_settings.txt
[gfxrecon] INFO - Successfully loaded settings from file
[gfxrecon] ERROR - fopen(C:\Users\Mikefxrecon_capture_frames_1_through_2_20210105T154539.gfxr, wb) failed (errno = 13)
[gfxrecon] FATAL - Failed to initialize TraceManager
[gfxrecon] DEBUG - vkCreateInstance(): Current instance count is 1
[gfxrecon] DEBUG - vkDestroyInstance(): Current instance count is 0
ERROR at c:\vulkansdkbuild\workspace\khronos-tools\repo\vulkaninfo\vulkaninfo.h:643:vkCreateInstance failed with ERROR_INITIALIZATION_FAILED
```

**Comment by christophe-lunarg** [comment]
Select "Frame Capture - First two frames" config
Use "..." button to set Capture File Name and browse to C:\Users\Mike\Desktop\gfxrecon_capture.gfxr
Close vkconfig
Open vkconfig

What happens with after these step is super strange in a first place. On master branch I couldn't reproduce...

When selecting a path (using the ... button) to a folder with no permission will make this window appear:
![image](https://user-images.githubusercontent.com/62888873/104015633-32508400-51b5-11eb-9936-d53e95ff5cab.png)

It's true that this check made by Qt itself it not performed when just entering a path in the text field...
