### ISSUE TITLE
DevSim: Memory Map failure when using simulation of my own device

### ISSUE THREAD

**Issue by vulkan101** [LunarG/VulkanTools#1311]
I have asked this question on S/O so apologies if you've seen it twice now. 

I'm using an RTX 2080 and have been able to successfully replicate an issue on an AMD 5700.

However, for fun I thought I would try using a device file for the same model device I have, and I am getting buffer mapping errors, specifically ERROR_MEMORY_MAP_FAILED when trying to map a buffer that has been successfully created, of size 65536 bytes).

There is no such error when not using the device simulation layer. I don't have the memory mapping failure when using the amd 5700 simulation file. The device files are both from http://vulkan.gpuinfo.org/

Any suggestions on how I can track down the cause of this issue, or an explanation as to why it might be happening, extra info I can provide etc, would be very welcome. 
I've just found the debug output flag, this is what I'm seeing: 

```
DEBUG devsim PhysicalDeviceData::Create()
        DEBUG devsim    deviceName "Intel(R) UHD Graphics"
        DEBUG devsim envar VK_DEVSIM_FILENAME = "D:\pathTo\devices\geforce rtx 2080 with max-q design.json"
        DEBUG devsim JsonLoader::LoadFile("D:\pathTo\devices\geforce rtx 2080 with max-q design.json")
        DEBUG devsim {
        DEBUG devsim    Document schema "https://schema.khronos.org/vulkan/devsim_1_0_0.json#" is schema_id 1
        DEBUG devsim            JsonLoader::GetValue(VkPhysicalDeviceProperties)
        DEBUG devsim WARN "maxBoundDescriptorSets" JSON value (32) is greater than existing value (8)
        DEBUG devsim WARN "maxPerStageDescriptorSamplers" JSON value (1048576) is greater than existing value (64)
        DEBUG devsim WARN "maxPerStageDescriptorUniformBuffers" JSON value (1048576) is greater than existing value (200)
        DEBUG devsim WARN "maxPerStageDescriptorStorageBuffers" JSON value (1048576) is greater than existing value (200)
        DEBUG devsim WARN "maxPerStageDescriptorSampledImages" JSON value (1048576) is greater than existing value (200)        DEBUG devsim WARN "maxPerStageDescriptorStorageImages" JSON value (1048576) is greater than existing value (16)
        DEBUG devsim WARN "maxPerStageDescriptorInputAttachments" JSON value (1048576) is greater than existing value (8)
        DEBUG devsim WARN "maxPerStageResources" JSON value (4294967295) is greater than existing value (200)
        DEBUG devsim WARN "maxDescriptorSetSamplers" JSON value (1048576) is greater than existing value (576)
        DEBUG devsim WARN "maxDescriptorSetUniformBuffers" JSON value (1048576) is greater than existing value (1800)
        DEBUG devsim WARN "maxDescriptorSetStorageBuffers" JSON value (1048576) is greater than existing value (1800)
        DEBUG devsim WARN "maxDescriptorSetSampledImages" JSON value (1048576) is greater than existing value (1800)
        DEBUG devsim WARN "maxDescriptorSetStorageImages" JSON value (1048576) is greater than existing value (144)
        DEBUG devsim WARN "maxDescriptorSetInputAttachments" JSON value (1048576) is greater than existing value (8)
        DEBUG devsim            JsonLoader::GetValue(VkPhysicalDeviceFeatures)
        DEBUG devsim            JsonLoader::GetValue(VkPhysicalDeviceMemoryProperties)
        DEBUG devsim WARN "size" JSON value (8511041536) is greater than existing value (0)
        DEBUG devsim WARN "size" JSON value (257949696) is greater than existing value (0)
        DEBUG devsim            JsonLoader::GetArray(ArrayOfVkQueueFamilyProperties)
        DEBUG devsim            JsonLoader::GetArray(ArrayOfVkFormatProperties)
        DEBUG devsim            JsonLoader::GetArray(ArrayOfVkLayerProperties)
        DEBUG devsim WARN JSON section ArrayOfVkExtensionProperties is deprecated and ignored.
        DEBUG devsim }
        DEBUG devsim PhysicalDeviceData::Create()
        DEBUG devsim    deviceName "GeForce RTX 2080 Super with Max-Q Design"
        DEBUG devsim envar VK_DEVSIM_FILENAME = "D:\pathTo\devices\geforce rtx 2080 with max-q design.json"
        DEBUG devsim JsonLoader::LoadFile("D:\pathTo\devices\geforce rtx 2080 with max-q design.json")
        DEBUG devsim {
        DEBUG devsim    Document schema "https://schema.khronos.org/vulkan/devsim_1_0_0.json#" is schema_id 1
        DEBUG devsim            JsonLoader::GetValue(VkPhysicalDeviceProperties)
        DEBUG devsim            JsonLoader::GetValue(VkPhysicalDeviceFeatures)
        DEBUG devsim            JsonLoader::GetValue(VkPhysicalDeviceMemoryProperties)
        DEBUG devsim            JsonLoader::GetArray(ArrayOfVkQueueFamilyProperties)
        DEBUG devsim            JsonLoader::GetArray(ArrayOfVkFormatProperties)
        DEBUG devsim            JsonLoader::GetArray(ArrayOfVkLayerProperties)
        DEBUG devsim WARN JSON section ArrayOfVkExtensionProperties is deprecated and ignored.
        DEBUG devsim }
```

EDIT: I notice the warning above about `VkPhysicalDeviceMemoryProperties` being larger than current - These are heap sizes, which I set to zero in the file, and then was unable to allocate because heap size was zero - not that surprising really. 

If I remove the section  `VkPhysicalDeviceMemoryProperties` altogether then again, not too surprised that I don't see the issue. 
The physical device memory properties section is as follows:
```
VkPhysicalDeviceMemoryProperties": {
        "memoryHeaps": [
            {
                "flags": 1,
                "size": 8399093760
            },
            {
                "flags": 0,
                "size": 8511041536
            },
            {
                "flags": 1,
                "size": 257949696
            }
        ],
        "memoryTypes": [
            {
                "heapIndex": 1,
                "propertyFlags": 0
            },
            {
                "heapIndex": 0,
                "propertyFlags": 1
            },
            {
                "heapIndex": 1,
                "propertyFlags": 6
            },
            {
                "heapIndex": 1,
                "propertyFlags": 14
            },
            {
                "heapIndex": 2,
                "propertyFlags": 7
            }
        ]
    },
```

**Comment by jeremyk-lunarg** [comment]
It is possible that the memory properties on your specific RTX 2080 are different from the memory properties recorded in the config file.

Try saving the output of vulkaninfo without the devsim layer, and vulkaninfo output with the devsim layer using the problem config file.

Please compare the `VkPhysicalDeviceMemoryProperties` section between the two files and see if there is a difference.

**Comment by karl-lunarg** [comment]
Cross-posting: https://stackoverflow.com/questions/65600940/vulkan-device-simulation-why-might-i-be-having-memory-map-failures-when-using-a

**Comment by vulkan101** [comment]
Thanks both, I was using a file for RTX 2080 super and I have a 2080 with max-q. The only difference appears to be the heap size, not a number of heaps or memory types.
Switching to the max-q design file appears to get rid of the problem though. 

I'm still interested to know in general terms why I would be able to successfully create a buffer and memory, but it was just the mapping that caused a failure?  I would have been nowhere near the heap limit?

**Comment by karl-lunarg** [comment]
My interpretation of the information on gpuinfo.org is that the RTX 2080 Super has 11 memory types, while the non-Super max-q has 5.  If this is truly the case, then that would explain your problem perfectly.

gpuinfo.org shows:

![image](https://user-images.githubusercontent.com/16430219/104040380-d249e580-5194-11eb-91bb-4dd91ff6d90b.png)

The bottom row is the number of memory types.  I think that your actual hardware is the middle column and so has 5 memory types.  You were using a DevSim simulation file for either of the two "Super" devices from the left or right column which both have 11 types.  Simulating a 11-type device on a 5-type device won't work.

The naming of these cards might be a bit confusing or there could be an error in the database.  And so I can't really reconcile your observations, which I don't dispute.  But it is good that it worked when you used a simulation file that matched your hardware. 

> Isn't the idea behind the device sim that I can test devices with different properties, or are there restrictions on things like memory types matching?

Yes, and this may be exposing a design flaw in DevSim.  Memory types really can't be fully simulated, so it may be better to turn off DevSim's replacement of the memory type info and perhaps allow it to be turned on via an option.  I suppose that things like memory heap sizes could still be simulated.  I'm going to open an issue proposing a potential change here.

**Comment by vulkan101** [comment]
It seems to depend on which file for each device is chosen too, there are several files for each variant, and of the 2080 Super variants I looked at, the first few all had 5 memory types, as did the file I originally used by mistake. 
But I'm happy that this is down to an incompatibility between the file I used and my actual device.
Thanks very much for your help!
