### ISSUE TITLE
devsim documentation nits

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#1329]
From https://vulkan.lunarg.com/doc/sdk/1.2.162.1/windows/device_simulation_layer.html ...

- **DevSim Layer Options**
  - Android settings names for each of these control points should be listed.  (Only `debugenable` and `exitonerror` are documented in the **Android** section above.)
  - **Note: Environment variables take precedence over 'vk_layer_settings.txt' options.** - `vk_layer_settings.txt` should be in real backticks (to represent code style), not explicit backticks.
- **Example using the DevSim layer using Linux envirnoment variables** - envirnoment => environment

**Comment by jeremyk-lunarg** [comment]
Fixed by the following [commit](https://github.com/LunarG/VulkanTools/commit/ecef04faeb8229357ef74ce356fbd477ba3686fd).
