### ISSUE TITLE
devsim: Using bool instead of numerical bool

### ISSUE THREAD

**Issue by christophe-lunarg** [LunarG/VulkanTools#1340]
devsim is the only LunarG layer that uses numerical bool instead of actual bool. 

It would be great to change this behavior or rather allowing the setting to take both bool and numerical bool. When numerical bool are used the layer could report in it's log that numerical bool are deprecated and to use bool instead.

This way, the JSON layer file with settings specification would not have to support numerical bool.

**Comment by jeremyk-lunarg** [comment]
Where specifically would you like the use of numerical bools to change?

I ask because the devsim config file schema defines a `VkBool32` to properly represent devices.

**Comment by christophe-lunarg** [comment]
In the setting text file:

```

# VK_LAYER_KHRONOS_validation
khronos_validation.debug_action = VK_DBG_LAYER_ACTION_LOG_MSG
khronos_validation.report_flags = error,perf,info,warn
khronos_validation.log_filename = stdout
khronos_validation.duplicate_message_limit = 10
khronos_validation.message_id_filter = ,
khronos_validation.disables = VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT
khronos_validation.enables = 
khronos_validation.gpuav_buffer_oob = FALSE
khronos_validation.printf_to_stdout = TRUE
khronos_validation.printf_verbose = FALSE
khronos_validation.printf_buffer_size = 1024

# VK_LAYER_LUNARG_device_simulation
lunarg_device_simulation.filename = C:\VulkanSDK\1.2.162.1\Config\VK_LAYER_LUNARG_device_simulation\macOS_gpu_family_1_portability.json
lunarg_device_simulation.debug_enable = 1 # 1 or 0 only in devsim
lunarg_device_simulation.emulate_portability = 1 # 1 or 0 only in devsim
lunarg_device_simulation.exit_on_error = 0 # 1 or 0 only in devsim
```

By supporting both TRUE or FALSE and 1 or 0, we could avoid breaking compatibility and improve consistency.

**Comment by jeremyk-lunarg** [comment]
Sounds like a good idea.

I'll work on it when I get the time.

**Comment by christophe-lunarg** [comment]
Thanks!

**Comment by jeremyk-lunarg** [comment]
@christophe-lunarg, after merging [PR #1395](https://github.com/LunarG/VulkanTools/pull/1359), can this issue be closed?

**Comment by christophe-lunarg** [comment]
Sure indeed!
