### ISSUE TITLE
vkconfig uses Linux file system conventions for Vulkan Installation Analysis

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1368]
Cosmetic only, not critical.
Run Tools->Vulkan Installation Analysis.  Go through the various sections, looking for references to files.
All references use Linux file system conventions, e.g. C:/Users/lunarg/AppData/Local/Temp.
References on Windows should use Windows conventions, e.g. C:\Users\LunarG\AppData\Local\Temp.

**Comment by lunarpapillo** [comment]
There are also references to environment variables that use Linux conventions, e.g. `$VK_LAYER_PATH` and `$VULKAN_SDK`.  These should use Windows conventions `%VK_LAYER_PATH%` and `%VULKAN_SDK%`.

**Comment by christophe-lunarg** [comment]
This is independent from vkconfig that just read vkvia log.
