### ISSUE TITLE
Feature Request - output loader debug messages

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1372]
This is just a "would be nice to have feature". The Vulkan Configurator can launch Vulkan Applications with various layers and layer options set and it collects the layer output. Since the applications are launched as child processes, it would be nice if an option existed to set the environment variable VK_LOADER_DEBUG=all to capture any debug messages from the loader itself as well. This would be particularly useful on macOS where environment variables are not seen by GUI applications when launched from the shell or finder.

**Comment by christophe-lunarg** [comment]
This is a great enhancement idea!

I REALLY need to investigate these Vulkan loaders settings.

**Comment by christophe-lunarg** [comment]
This issue is resolved with https://github.com/LunarG/VulkanTools/pull/1393.
