### ISSUE TITLE
vkconfig: Move the layer version info in vulkaninfo output outside of the title

### ISSUE THREAD

**Issue by charles-lunarg** [LunarG/VulkanTools#1376]
The layer properties contain version information, which is put in the first line. Moving this out into the object itself, ie making version info sub-objects of the layer, would make it easier to read. 

![image](https://user-images.githubusercontent.com/46324611/109218889-39871d80-7774-11eb-8393-011d913dc65a.png)

**Comment by christophe-lunarg** [comment]
It does look ridiculously ugly...
