### ISSUE TITLE
The Configuration Settings pane blanks 

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1377]
The **Configuration Settings** pane blanks when **Tools->User-Defined Layer Paths...** is selected.

![image](https://user-images.githubusercontent.com/17237544/109314371-7c91d100-7806-11eb-9fca-d2e0e83b3c99.png)

It remains blank after the **User-Defined Paths to locate Vulkan Layers** dialog box is dismissed.

It comes back if any other layer configuration is selected.

**Comment by christophe-lunarg** [comment]
This is a duplicated of #1289, closing #1289 to keep this one.

**Comment by christophe-lunarg** [comment]
This issue is fixed on master branch,
