### ISSUE TITLE
platform-specific environment variable conventions

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1378]
`vulkaninfo` and `vkvia` currently use Linux conventions when displaying environment variable information.  `vkconfig` does the same, to match their output.

I assert that these tools should all use Command Prompt conventions on Windows, and POSIX conventions on Mac and Linux, to ensure that developers on each platform clearly understand what is being expressed.  I assert that all Windows developers will understand Command Prompt conventions, even "power users" who instead use PowerShell or other shells.

But I'm not a Windows native.  I'd like to collect insights from our Windows developers before making any changes.

I think we are biased because we are all cross platform developers we think this will be obvious. Most Windows developers are not cross platform and will at the least be given a moment's pause about the $ symbol. We also know a great deal of noob's just jump into the deep end, and we are only creating more "tech support" and "cognitive friction" to adopting Vulkan and the SDK tools. We take great pains to display / or \ as path separators, and likewise we should follow the Windows conventions concerning environment variables when on Windows(we do not expect them to know the difference between ; separated paths and : separated one's either -- same thing). When in Rome...

Not critical for the March 1 SDK release, but I would endorse having this change made for the April SDK.

It appears that this will require changes in vulkaninfo and vkvia (in two different repositories). However using this single issue to track.

**Comment by christophe-lunarg** [comment]
This issue is resolved by https://github.com/LunarG/VulkanTools/pull/1379
