### ISSUE TITLE
devsim layer includes unexpected (?) debug output

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1380]
This has probably been around for a while, and may be intentional.  It looked strange to me, so I'm bringing it up for scrutiny and discussion.

In `vkconfig`, activate a **devsim** configuration.  Select [X] **Debug Enable**.  Launch an application (`vkcube` is fine) and terminate it with the close box on the window (*not* with the **Terminate** button).

Some strange/unexpected debug messages appear in the console pane.  They don't seem complete nor terribly useful:

![image](https://user-images.githubusercontent.com/17237544/109315464-cf1fbd00-7807-11eb-8f3d-c0fa6c5d7166.png)

Are they intentional?  Why were these particular messages chosen?  Is this intended for internal LunarG debugging of the layer, or is it useful for a developer in some way?

**Comment by jeremyk-lunarg** [comment]
These are intentional.  They tell the user what types of config files the layer is loading in.
