### ISSUE TITLE
vkCreateRenderPass SIGSEGV

### ISSUE THREAD

**Issue by Scoopta** [LunarG/VulkanTools#140]
Any time I call vkCreateRenderPass I get a seg fault and I'm not entirely sure why. It only happens if I have the validation layer enabled. Disabling it seems to fix my issue but that's not ideal. I ran into this issue before with vkDestroyImageView but that ended up being a stupid mistake I made so I've tried to find potential stupid mistakes but I haven't found any. As far as I can tell my code is fine. The seg fault happens here:
`[libVkLayer_core_validation.so+0x184475]  core_validation::CreateRenderPass(VkDevice_T*, VkRenderPassCreateInfo const*, VkAllocationCallbacks const*, VkRenderPass_T**)+0x115`

**Comment by karl-lunarg** [comment]
Could you please create this issue in the https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers repo, like you did with the other issue?   This will get more of the right people looking at it.

Did you see any other validation layer messages before the fault?    Often, the layers will detect a bad parameter and print a message.  But subsequent checks made by the layers assume that the parameters are good and the layers will fault.  IOW, one layer checks for good params, but the other layers don't repeat the same checks before accessing these params.   They assume that you saw the message from the param checker and fixed the problem.

Also, there isn't enough information in this issue to come close to being enough for anyone to work on the problem.   You'll need to provide a repro case, an api trace, or at least some code.
