### ISSUE TITLE
devsim: Option to intersect format properties between simulated and host devices

### ISSUE THREAD

**Issue by werman** [LunarG/VulkanTools#1419]
The goal of the layer is to simulate less capable device on a more capable device. For ordinary capabilities desktop GPUs usually have a superset of features of mobile GPUs, or it's easy to fix one or two properties. However, for `VkFormatProperties` there is much more variation and it's not easy to compare and change it by hands.

My current use case is an attempt to capture VK trace of a game which runs through DXVK and play it back on Turnip driver to test it, since almost all games cannot run on arm64.

I made a crude script to make an intersection of format properties and it worked well for my case. However, I'd like to see this feature in the layer itself.

**Comment by jeremyk-lunarg** [comment]
This feature is now supported with the merge of PR #1535.

@werman, does this change meet your needs?

**Comment by werman** [comment]
@jeremy-lunarg Perfectly, thanks!

However I feel that whitelist/blacklist/intersect naming is a bit off:
- "intersect" is really a union of properties, thus "union" naming would be more appropriate
- "whitelist" is an intersection of properties, thus "intersect" naming would be more appropriate
