### ISSUE TITLE
vkconfig: preset doesn't change when switching between duplicat layer configurations

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1445]
Environment:
- Ubuntu 20.04 
- Nvidia driver

Steps to reproduce:
1. Duplicate the default "Validation" layer config - Name it Validation2
2. In the original Validation config notice that the preset is "Standard preset"
3. Switch to the Validaiton2 layer config change the preset to "Best Practices preset"
4. Switch back to the original Validation layer config and checkout the preset.

Gif showing that the preset doesn't change on a duplicated layer configuration:
![preset-selection-duplicate-configs](https://user-images.githubusercontent.com/3836693/115312960-9c22e700-a12f-11eb-9c54-d6a8e95940ae.gif)

**Comment by christophe-lunarg** [comment]
I could reproduce the issue, no idea what is causing this...

**Comment by christophe-lunarg** [comment]
This issue is resolved with https://github.com/LunarG/VulkanTools/pull/1452 PR
