### ISSUE TITLE
vkconfig: hangs trying to export layer configurations

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1447]
Environment:
Ubuntu 20.04
Nvidia

Steps to reproduce:
1. Export any layer configuration

Including a gif because gnome will "grey out" the application for this:
![export-hang](https://user-images.githubusercontent.com/3836693/115314580-b7dbbc80-a132-11eb-93db-f7ae9f636a92.gif)

**Comment by johnzupin** [comment]
Still seeing this as of ref: v1.2.170-261-g5aeab5532

**Comment by christophe-lunarg** [comment]
This issue doesn't reproduce for me on Windows or macOS...

**Comment by johnzupin** [comment]
Confirming that I also didn't see this problem on Windows

**Comment by johnzupin** [comment]
For Linux, it seems to be having trouble opening the file manager to let the user choose a file.

**Comment by johnzupin** [comment]
Closing. See https://github.com/LunarG/VulkanTools/issues/1464
