### ISSUE TITLE
vkconfig: changing Executing overridden layer order

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1448]
Environment:
Ubuntu 20.04
Nvidia

Not entirely sure if this is an issue but I'm seeing some strangeness changing order of the execution of layers.

![layer-reordering](https://user-images.githubusercontent.com/3836693/115314999-9deea980-a133-11eb-9962-d900a8d37cc5.gif)

**Comment by christophe-lunarg** [comment]
This is the expected behavior, Vulkan Configurator will try to reorder the layers when one is overridden to a recommended order of the layers, that the user can override on the bottom window.
