### ISSUE TITLE
vkconfig: hangs when adding no new applications in the "Application to Override vulkan layers" window

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1450]
Environment:
Ubuntu 20.04
Nvidia

Steps to Reproduce:
1. Choose: "Edit..." after checking "Apply only to the selected list of applications"
2. Without changing anything choose "Add"

**Comment by johnzupin** [comment]
![add-nothing](https://user-images.githubusercontent.com/3836693/115440195-b52da580-a1cc-11eb-8781-d5b5805396fa.gif)

**Comment by johnzupin** [comment]
Still seeing this as of ref: v1.2.170-261-g5aeab5532

**Comment by christophe-lunarg** [comment]
This issue doesn't reproduce on Windows or Linux for me...

**Comment by johnzupin** [comment]
Confirming that I also don't see this on Windows

**Comment by johnzupin** [comment]
For Linux, it seems to be having trouble opening the file manager to let the user choose a file.

**Comment by johnzupin** [comment]
Closing. See: https://github.com/LunarG/VulkanTools/issues/1464
