### ISSUE TITLE
vkconfig: hangs when trying to choose a devsim configuration file

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1451]
Environment:
Ubuntu 20.04
Nvidia

Steps to reproduce:
1. Choose the "Portability" layer configuration
2. On the right panel, choose "..." to bring up file manager to select the DevSim json configuration file

**Comment by johnzupin** [comment]
![dev-sim-nothing](https://user-images.githubusercontent.com/3836693/115440467-fb830480-a1cc-11eb-81a8-1e5f06d13798.gif)

**Comment by johnzupin** [comment]
Still seeing this issue as of ref: v1.2.170-261-g5aeab5532

**Comment by christophe-lunarg** [comment]
This issue doesn't reproduce for me on Windows.

**Comment by johnzupin** [comment]
I also don't see this problem on Windows

**Comment by johnzupin** [comment]
For Linux, it seems to be having trouble opening the file manager to let the user choose a file.

**Comment by johnzupin** [comment]
Closing, see: https://github.com/LunarG/VulkanTools/issues/1464
