### ISSUE TITLE
vkconfig: API Dump layer defaults to output to file

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1454]
I'm currently only seeing this on my Windows build, I'm not seeing this on Linux, but selecting the "API dump" layer config has "Output to File" checkbox as checked. It will write the output to a file name "stdout" in the current directory. Going to "Tools"->"Reset To Default" doesn't uncheck the Output to File checkbox, seems to default to having this checkbox checked.

**Comment by christophe-lunarg** [comment]
This issue is fixed with https://github.com/LunarG/VulkanTools/pull/1456

It's more an inconsistency than a bug that I resolved by adding a "Console Output" preset.

**Comment by johnzupin** [comment]
Can confirm fixed as of ref: v1.2.176-9-g125ee32f4
