### ISSUE TITLE
vkConfig missing Synchronization configs on macOS

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1459]
Synchronization2 is available for macOS, but vkConfig does not list it as a layer (it is also present on the system).

**Comment by christophe-lunarg** [comment]
Is it detected in the Vulkan status?

**Comment by richard-lunarg** [comment]
No, it is not listed there either.

**Comment by richard-lunarg** [comment]
This is now working with a clean install of a release build for the SDK.
