### ISSUE TITLE
vktrace of Dota2 on Linux seems to run slow

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#146]
It seems slower than on Windows.

**Comment by davidlunarg** [comment]
Trace file generated when tracing Dota2 is 5x larger on Linux than on Windows. This probably explains why tracing on Linux feels slower than on Windows. Need to understand why trace file is so much bigger.

**Comment by davidlunarg** [comment]
Trace file on Linux are larger than Windows because using /proc/self/pagemap on Linux to detect changed pages in PMB is much faster than using PAGE_GUARD exceptions on Windows. So the app can run at a higher frame rate and modify pmb faster, producing more pmb data to send to the tracefile.

Commit 0de31ce7241a95fdb712c4346266cdc2291d60af results in the tracefiles for Dota2 significantly smaller on Linux, but still not the same size as Windows.

If an app uses lots of PMB and runs really slow while tracing, the slowdown can sometimes be caused by the trace file is taking so long to write to disk. Sending the trace file to a ram disk can speed up the app at the cost of using memory to allocate to the ram disk.

**Comment by eero-t** [comment]
Replay is CPU limited even on Intel GPU.  See #168 for related issue.  According to perf on SKL GT2 + Mesa, there's quite a lot of load on kernel side in addition to vkreplay which takes most of CPU.

Vkreplay uses only one thread to replay DOTA2 trace.  DOTA2 does some work in multiple threads, is it actually rendering with multiple threads?

**Comment by davidlunarg** [comment]
vkreplay uses only one thread. But there's a lot less work to do on replay - for example, vertex data doesn't need to be computed, just pushed out to the GPU. I'd be curious what kernel calls are causing the large load on the kernel.

**Comment by eero-t** [comment]
Even with DOTA2 traces that fit into RAM, vkreplay CPU utilization is ~100%.  GPU is running at max frequency, but according to intel_gpu_top, it's only ~85% busy, so clearly it's CPU activity bound.  Compiling with -O3 instead of default -O2 helping performance by ~10% verifies that.

As #154 had perf data for partly disk bound startup part of a huge DOTA2 trace, here's some perf data for the *gameplay* part of a DOTA2 trace that fits completely into RAM...

Overview where the active CPU cycles are consumed:
```
 99.95% vkreplay
     59.25% vkreplay
     28.80% [kernel.kallsyms]
      5.12% libvulkan_intel.so
      2.80% libc-2.23.so
      1.90% [unknown]
      1.17% libvulkan.so.1.0.39
```

Details:
```
# Samples: 42K of event 'cycles:pp'
# Event count (approx.): 9507583256217
#
#   Samples  Command   Shared Object         Symbol:
0.03%  2601  vkreplay  [kernel.kallsyms] [k] copy_user_enhanced_fast_string
0.02%  1551  vkreplay  vkreplay          [.] std::less<VkFence_T*>::operator()
0.01%  1325  vkreplay  vkreplay          [.] std::_Rb_tree<VkFence_T*, std::pair<VkFence_T* const, VkFence_T*>,
0.01%  1109  vkreplay  [kernel.kallsyms] [k] drm_ioctl
0.01%  1019  vkreplay  vkreplay          [.] std::_Rb_tree<VkFence_T*, std::pair<VkFence_T* const, VkFence_T*>,
0.01%   911  vkreplay  [kernel.kallsyms] [.] entry_SYSCALL_64_fastpath
0.01%   857  vkreplay  vkreplay          [.] vkReplay::replay
0.01%   787  vkreplay  [kernel.kallsyms] [k] i915_gem_wait_ioctl
0.01%   771  vkreplay  vkreplay          [.] std::_Rb_tree_node<std::pair<VkFence_T* const, VkFence_T*> >::_M_valptr
0.01%   677  vkreplay  [unknown]         [k] 0x00007f5050770355
0.01%   607  vkreplay  vkreplay          [.] std::_Rb_tree<VkFence_T*, std::pair<VkFence_T* const, VkFence_T*>,
0.01%   602  vkreplay  vkreplay          [.] __gnu_cxx::__aligned_membuf<std::pair<VkFence_T* const, VkFence_T*> >::_M_ptr
0.01%   586  vkreplay  [kernel.kallsyms] [k] __fget_light
0.01%   556  vkreplay  [kernel.kallsyms] [k] entry_SYSCALL_64_after_swapgs
0.01%   536  vkreplay  vkreplay          [.] std::_Select1st<std::pair<VkFence_T* const, VkFence_T*> >::operator()
0.01%   533  vkreplay  vkreplay          [.] std::less<VkDevice_T*>::operator()
0.01%   509  vkreplay  [kernel.kallsyms] [k] mutex_unlock
0.00%   491  vkreplay  [kernel.kallsyms] [k] _raw_spin_lock
0.00%   473  vkreplay  vkreplay          [.] __gnu_cxx::__aligned_membuf<std::pair<VkFence_T* const, VkFence_T*> >::_M_addr
0.00%   467  vkreplay  vkreplay          [.] std::_Rb_tree<VkDevice_T*, std::pair<VkDevice_T* const, VkDevice_T*>,
0.00%   462  vkreplay  vkreplay          [.] std::_Rb_tree<VkFence_T*, std::pair<VkFence_T* const, VkFence_T*>,
0.00%   446  vkreplay  vkreplay          [.] vkReplayObjMapper::remap_fences
0.00%   445  vkreplay  vkreplay          [.] vkReplayObjMapper::remap_devices
0.00%   445  vkreplay  [kernel.kallsyms] [k] mutex_lock_interruptible
0.00%   432  vkreplay  [kernel.kallsyms] [k] drm_gem_object_lookup
0.00%   394  vkreplay  vkreplay          [.] std::less<VkCommandBuffer_T*>::operator()
0.00%   383  vkreplay  vkreplay          [.] std::_Rb_tree<VkDevice_T*, std::pair<VkDevice_T* const, VkDevice_T*>,
0.00%   364  vkreplay  vkreplay          [.] std::less<VkDescriptorSet_T*>::operator()
0.00%   357  vkreplay  [kernel.kallsyms] [k] i915_gem_object_flush_active.part.42
```

-> Fencing seems to be the main cost?

(I removed first 2 items which were shown as taking tens of percentages of the cycles as they had only couple of samples and were different on every perf run.  I think it's some kind of bug in Ubuntu perf versions, but I haven't seen it before.)
