### ISSUE TITLE
Unknown layer on macOS

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1460]
vkConfig on macOS in the Select Vulkan Layers dialog is listing an unknown layer:
VK_LAYER_LUNARG_reference_1_2_0
It shows under layer properties as:
reference layer
(Custom Path)
.\VKLayer_reference.dll
There are not dll's on macOS, and no custom paths are set.

**Comment by christophe-lunarg** [comment]
You are seeing this only because you built in debug mode. (or there is a problem!)

This is not a bug but the "layer" I am using to test all layer settings and features, making it easier to test.

**Comment by richard-lunarg** [comment]
I am in release mode and I'm still seeing this. Even after a complete clean restart (deleted old files, purged plist).

**Comment by christophe-lunarg** [comment]
This was indeed an actual bug, I reproduced it on Windows too but it's fix with PR https://github.com/LunarG/VulkanTools/pull/1471
