### ISSUE TITLE
API dump preset cannot be changed.

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1461]
This is on macOS (maybe on other platforms too)
When the API dump is selected, the API Dump Settings show a combo box that displays "Text Output Preset". The combo box shows other options as well, such as HTML Output Preset, JSON Output Preset, Console Output Preset, but these cannot be selected.
Might be a selection bug, might be showing options that cannot be selected (both are bugs).

**Comment by richard-lunarg** [comment]
I can now change these presets. Only "Console Output" produces any output however.

**Comment by christophe-lunarg** [comment]
This issue should be resolved with https://github.com/LunarG/VulkanTools/pull/1463.
The issue doesn't reproduce anymore for me on macOS
