### ISSUE TITLE
Shader-Based options not hidden for macOS/vkConfig

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1467]
Therese options where hidden in the last SDK release, and have not been fully validated as ready for macOS. They should remain hidden on macOS for the time being.

**Comment by christophe-lunarg** [comment]
This issue should be fixed with https://github.com/LunarG/VulkanTools/pull/1463.
It doesn't reproduce for me anymore on macOS

**Comment by richard-lunarg** [comment]
I'm seeing this again today.

**Comment by christophe-lunarg** [comment]
Then I have a doubt you are using current master...

**Comment by richard-lunarg** [comment]
I am indeed using current master, but I was running a debug build. A release build followed by a reboot cleared the issue up again. macOS is possessed... it may have been caching some settings, but I think debug builds should behave just like release builds for testing purposes.
