### ISSUE TITLE
VkConfig should have tooltips for `Vulkan App/Vulkan Driver` indicators in layer list

### ISSUE THREAD

**Issue by charles-lunarg** [LunarG/VulkanTools#1479]
When multiple layers are active in vkconfig, its hard to tell why there is a greyed out `vulkan application` and `vulkan driver` appearing above and below the application list. 

Adding tool tips would make it easy for users to find out what those represent.

Example of the grey'd out text I'm referring to.
![image](https://user-images.githubusercontent.com/46324611/116624444-24aa4000-a905-11eb-9407-65c619ff27fe.png)

**Comment by christophe-lunarg** [comment]
This issue is resolved by https://github.com/LunarG/VulkanTools/pull/1480
