### ISSUE TITLE
vktrace of Dota2 can cause corrupt rendering

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#148]
While testing SDK-1.0.39 on NV Windows 7, tracing Dota2 can cause rendering artifacts and sporadic playback failure.  There were black triangles in the terrain, rendering artifacts in the player profile screen, and rendering artifacts at the dashboard screen behind the character.  All of this is tracing while playing a little way through the Mechanics tutorial

**Comment by eero-t** [comment]
On Intel SkyLake on Linux, it seems to now work fine.

Is this still an issue on NV and/or Windows, i.e. is it specific to them?

**Comment by davidlunarg** [comment]
Haven't seen any issues with Dota2 trace/replay for a while. Closing this issue. If new problems arise, please submit a new issue.
