### ISSUE TITLE
vkconfig: everything used by vkconfig emits messages to stdout/stderr

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1493]
This started as https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/695 , but then that issue got converted into a **devsim** issue, so I'm creating a new one.  It's more an enhancement request than a "Must Fix", as I think the behavior is not new to this SDK and is only cosmetic.

Lots of output apparently comes from `vkconfig` even when you're just switching between configurations.  I'm not entirely sure how `vkconfig` is exercising the layer even before an application is launched using it, but clearly something is happening.  Clicking to select the **API dump**, **Portability**, **Synchronization**, or **Validation** presets all provoke output.

It seems common practice for internal layers to provoke output.  It may be common for external layers to do the same.  I'm not sure why; there may or may not be a good technical reason.

It would be easier for `vkconfig` to hide this output in a log file somewhere, rather than modify all the involved layers to avoid such output (especially as even if we modify all our layers to avoid output, the problem can still appear with outside layers).

This is the output I provoked by only changing the selected configuration in `vkconfig`:

[vkconfig.txt](https://github.com/LunarG/VulkanTools/files/6437008/vkconfig.txt)

**Comment by christophe-lunarg** [comment]
By default and convention, the layers emits log to stdout and stderr but this can be typically configured using the layer settings.

Vulkan Configurator leverages this behavior to capture the layers logs and display this log into the log window. Vulkan Configurator would not be capable to figure out what file the layer could use at the moment.
