### ISSUE TITLE
vkconfig: problems with UI scaling

### ISSUE THREAD

**Issue by nikitablack** [LunarG/VulkanTools#1499]
Ubuntu 18, monitor connected to a laptop, the resolution is 1920x1080 on both screens, scale is 100% on both screens. This is what I see on the laptop screen:

![1](https://user-images.githubusercontent.com/6390092/118639310-0cc52e00-b7d8-11eb-9c1c-d7ec27a5d9ed.png)

When I drag the window to the monitor the scale changes to:

![2](https://user-images.githubusercontent.com/6390092/118639405-28c8cf80-b7d8-11eb-81ac-38a964c90266.png)

I can fix this by setting
```
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCALE_FACTOR=1
```
But it would be good to handle the scaling by the application itself.

**Comment by christophe-lunarg** [comment]
Thanks for reporting

**Comment by christophe-lunarg** [comment]
I believe this issue is resolved. The only caveat is that Vulkan Configurator needs to be build with Qt 5.6 or later.
