### ISSUE TITLE
Missing tag v1.2.141

### ISSUE THREAD

**Issue by gmueckl** [LunarG/VulkanTools#1503]
Among the tags corresponding to Vulkan specification versions, the tag for the SDK release 1.2.141 is missing. Can this tag be added?

**Comment by KarenGhavam-lunarG** [comment]
The tags of the format "v.x.y.zzz" are indicating a header version update, not an SDK release.
The branch sdk-1.2.141 is the branch used for the SDK release.

That said, it doesn't appear that the repository was tagged with v.1.2.141 with that header update. Investigating...

**Comment by Tony-LunarG** [comment]
I've added the v1.2.141 tag that was missing
