### ISSUE TITLE
devsim: store boolean instead of numeric boolean in the devsim file

### ISSUE THREAD

**Issue by christophe-lunarg** [LunarG/VulkanTools#1526]
For example:
```
    "Vulkan12Features": {
        "samplerMirrorClampToEdge": 0,
        "shaderOutputViewportIndex": 0,
        "shaderOutputLayer": 0,
        "subgroupBroadcastDynamicId": 1,
        "drawIndirectCount": 0,
        "descriptorIndexing": 0,
        "samplerFilterMinmax": 0
    }
```
Would be easier to read with:
```
    "Vulkan12Features": {
        "samplerMirrorClampToEdge": false,
        "shaderOutputViewportIndex": false,
        "shaderOutputLayer": false,
        "subgroupBroadcastDynamicId": true,
        "drawIndirectCount": false,
        "descriptorIndexing": false,
        "samplerFilterMinmax": false
    }
```
JSON actually supports boolean values so no need to store numeric booleans.

**Comment by jeremyk-lunarg** [comment]
The problem is these "boolean" values are not really boolean.  They are VkBool32, meaning they are stored as 32-bit numbers.

We could change it to be true boolean, but that would break away from the philosophy of formatting config file values as close to the implementation as possible.

**Comment by christophe-lunarg** [comment]
I think this philosophy of being close to the implementation really need to change to a philosophy that focus on the users but I agree this should code with a more substantial redesign, not next SDK.

**Comment by christophe-lunarg** [comment]
This issue was resolved by the profiles layer
