### ISSUE TITLE
devsim: maxSamplerAllocationCount is set to 4000 but in practice the max is 1024

### ISSUE THREAD

**Issue by christophe-lunarg** [LunarG/VulkanTools#1527]
This might be something missing in the Vulkan portability subset extension.

Drivers reports:
https://vulkan.gpuinfo.org/displayreport.php?id=11332#properties
https://vulkan.gpuinfo.org/displayreport.php?id=11396#properties
https://vulkan.gpuinfo.org/displayreport.php?id=11294#properties

**Comment by jeremyk-lunarg** [comment]
I don't see any mention in the spec of an alternative minimum for this value on portability implementations.
That's really weird.

**Comment by christophe-lunarg** [comment]
I created an internal issue for Khronos
