### ISSUE TITLE
devsim: maxSamplerLodBias is set to to for the minimum portability but should be 0

### ISSUE THREAD

**Issue by christophe-lunarg** [LunarG/VulkanTools#1530]
It's part of the KHR_portability_subset: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDevicePortabilitySubsetFeaturesKHR.html

**Comment by christophe-lunarg** [comment]
This is also reflected on actual reports:
https://vulkan.gpuinfo.org/displayreport.php?id=11294#properties
https://vulkan.gpuinfo.org/displayreport.php?id=11396#properties
https://vulkan.gpuinfo.org/displayreport.php?id=11332#properties

**Comment by jeremyk-lunarg** [comment]
Changes to these values are also not mentioned in the spec or, at least, aren't clear.
