### ISSUE TITLE
devsim: min value of optional features are not set to their value for unsupported feature.

### ISSUE THREAD

**Issue by christophe-lunarg** [LunarG/VulkanTools#1532]
maxViewports is 1 but devsim set it to 16

**Comment by christophe-lunarg** [comment]
storageImageSampleCounts is set to 9 but it should be 1 as it's optional

**Comment by christophe-lunarg** [comment]
lineWidthRange is set to 1.0, 7.0 but it should be 1.0, 1.0 as is an optional feature
pointSizeRange is set to 1.0, 63.0 but it should be 1.0, 1.0 as is an optional feature

**Comment by christophe-lunarg** [comment]
lineWidthGranularity is set to 1.0 but it should be set to 0.0 as it is an optional feature
pointSizeGranularity is set to 1.0 but it should be set to 0.0 as it is an optional feature

**Comment by jeremyk-lunarg** [comment]
Would I be correct in stating that this issue essentially encompasses issues #1530 and #1531?

**Comment by christophe-lunarg** [comment]
Yes this is correct.
