### ISSUE TITLE
vkconfig layer configuration - implicit layers are not necessarily "implicitly on"

### ISSUE THREAD

**Issue by jeremy-lunarg** [LunarG/VulkanTools#1546]
Implicit layers, such as the steam layers,  can be controlled by environment variables of the form `(DISABLE|ENABLE)_VK_LAYER_blah_blah`. 
![screen02](https://user-images.githubusercontent.com/6943397/121970320-839c0b00-cd33-11eb-9702-220de7dadbb2.png)

However, `vkconfig` reports all implicit layers as "implicitly on," which is not always true.
![screen01](https://user-images.githubusercontent.com/6943397/121965998-256b2a00-cd2b-11eb-8216-fbafd56a45a4.png)

In such cases, `vkconfig` could detect whether the layer configurations include disable/enable control and add a 4th category called "environment controlled."

**Comment by christophe-lunarg** [comment]
Interesting, I wasn't aware of this mechanism. I'll add support to it in the future.

**Comment by jeremy-lunarg** [comment]
> Interesting, I wasn't aware of this mechanism. I'll add support to it in the future.

The _mechanism_ is humorously complex IMO. I had to ask Lenny 20 billion times how this worked. These are the rules, in order, as I understand them.

1. If `DISABLE`, which is required to be present in the layer's configuration, is _set_ then the _implicit_ layer is _off_.
1. If `ENABLE` is not present in the _implicit_ layer's configuration, then the _implicit_ layer is "implicity on."
1. However if `ENABLE` is present in the _implicit_ layer's configuration and _not set_, then the _implicit_ layer is _off_.
