### ISSUE TITLE
Print warning if screenshot layer is missing and print location and name of the screenshot file

### ISSUE THREAD

**Issue by ardaLunarG** [LunarG/VulkanTools#157]

**Comment by davidlunarg** [comment]
If the env var VK_LOADER_DEBUG is set to "warn" or "info", the loader will print a message that it was not able to load the screenshot layer.

When the screenshot layer writes to a screenshot image file, it prints out "Screen Capture File is: <filename>". If VK_SCREENSHOT_DIR is set, <filename> is preceded with the path to where the file is written.
