### ISSUE TITLE
vkconfig: fails to find custom layers on Arch Linux

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1602]
4. Select the "API dump" layer configuration. Make sure the "Overriden by the Vulkan Configurator" radio button is selected. Click the "Launch" button. API Dump output should be displayed in the log panel at the bottom of the window.
5. Create a folder for a custom layer test. Copy the libVkLayer_api_dump.(dll|so|dylib) and VkLayer_api_dump.json files to this folder. Open VkLayer_api_dump.json, and edit the "library_path" entry to "./libVkLayer_api_dump.(dll|so|dylib)" and edit the "api_version" to the current SDK version number +1.
6. Press the "Find Layers..." button at the far right top of the window and select the custom layer path from above in the dialog to add the custom layer.
7. Right click in the Vulkan Layers Configurations area and select "New...". Verify the the Api Dump layer reports the new version number from your .json file changes. Select "Overriden/Forced On" for that layer. Click OK to create the new configuration.

This was found during SDK 1.2.189.0 testing. See original issue[ here](https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/842)

It was confirmed this issue also existed on Ubuntu 20.04 with SDK 1.2.182.0 as well (so it wasn't a regression)

**Comment by christophe-lunarg** [comment]
Regarding this issue, `setup-env.sh` has: VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d" export VK_LAYER_PATH

The behavior in vkconfig has always been: 1 Load `VK_LAYER_PATH` 2 Load layers from vkconfig user-defined paths 3 Load layers from system path 4 Load layers from VULKAN_SDK

So we consider that VK_LAYER_PATH is the variable that overrides any other choice.

I think the test should be changed.
