### ISSUE TITLE
VkConfig should make sure the layers added to the override layer match API version

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/VulkanTools#1603]
The loader will reject a meta-layer which has component layers that have different API versions in their layer manifests.  Make sure that VkConfig catches this case and throws a warning to the user.

**Comment by MarkY-LunarG** [comment]
Our current thought is maybe we should have VkConfig determine what the API version of each layer is and set the override layer to a version compatible with each?  Or have the person determine a version and it gets set to that?  IDK.

**Comment by christophe-lunarg** [comment]
This is currently done in Vulkan Configurator but this is way to restrictive for the Vulkan developer. Basically it's not possible to create a layers configuration with an implicit layer as they will typically not be build with the same Vulkan Header version than the SDK layer.
