### ISSUE TITLE
API Dump on Android should support option to send output to logcat

### ISSUE THREAD

**Issue by mark-lunarg** [LunarG/VulkanTools#1611]
Currently, the only way to see apidump output on mobile platforms is to redirect the output to a file.  This works, but can be problematic depending upon the location chosen for the file -- valid locations are severely limited due to platform security constraints.  Having an option (or preferably the default) allowing the sending of output to logcat would allow it to be viewed in real time and in context with other Android standard output.

**Comment by 06393993** [comment]
Hi maintainers,

I have a local change that will do this. Is the upstream open to accept such change? If so, I will open a PR of my local change.

Thanks!

**Comment by charles-lunarg** [comment]
> I have a local change that will do this. Is the upstream open to accept such change? If so, I will open a PR of my local change.

Yes we are definitely open to changes!

**Comment by 06393993** [comment]
A WIP PR is opened: https://github.com/LunarG/VulkanTools/pull/1835. Will add tests and split it into 2 commits.

**Comment by juan-lunarg** [comment]
https://github.com/LunarG/VulkanTools/pull/1835
