### ISSUE TITLE
API Dump: Include vulkan video extensions

### ISSUE THREAD

**Issue by charles-lunarg** [LunarG/VulkanTools#1626]
Currently, the vk video extensions are not being used in the generated code due to the headers containing types which aren't defined in the vk.xml (like platform specific types but lacking a platform specific header which includes the definition).

In the future, the vulkan registry should contain the necessary data to generate these types. 

The disabling of these extensions is found here: https://github.com/LunarG/VulkanTools/blob/7b4657cb6ce03c3d296a56b14fb69ab18ba10bc6/CMakeLists.txt#L213

**Comment by theHamsta** [comment]
A naive question: I tried recent master and the structs from video.xml seem to be generated now: https://github.com/theHamsta/VulkanTools/blob/c27c724bc67f72399d757751bca76eef743462aa/CMakeLists.txt#L216-L230. Isn't this issue already fixed?

**Comment by charles-lunarg** [comment]
Yep, forgot to close this issue.

Thanks for pointing it out!
