### ISSUE TITLE
build: shift-op-parentheses warning for Ubuntu clang builds

### ISSUE THREAD

**Issue by sfricke-samsung** [LunarG/VulkanTools#1646]
Running on Ubuntu 20.04 with clang 10 I keep getting the following build error

```
layersvt/api_dump_text.h:24411:89: error: operator '>>' has lower precedence than '+'; '+' will be evaluated first [-Werror,-Wshift-op-parentheses]
    dump_text_array<const VkSampleMask>(object.pSampleMask, object.rasterizationSamples + 31 >> 5, settings, "const VkSampleMask*", "const VkSampleMask", "pSampleMask", indents + 1, dump_text_VkSampleMask); // BQB
```

I have been just adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-shift-op-parentheses")` as workaround but not sure if something can be fixed in the generation logic instead

**Comment by charles-lunarg** [comment]
Definitely a bug. Seems the assumption that << has a lower precedence than + is misfounded. Thankfully the fix is easy, just move the 'fix' logic from the python code itself into the C++ template (not to be confused with the C++ template code in api_dump.h!)
