### ISSUE TITLE
vkconfig command line doesn't work on Windows

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#1666]
@Tony-LunarG found this, but I went investigating.  It appears on the latest SDK, and seems to reproduce at least as far back as SDK 1.2.162.0.  Sometimes the `%errorlevel%` is reported as `3` or `9009`; I haven't figured out a pattern.
```
> C:\VulkanSDK\1.3.204.1\Tools\vkconfig.exe help
> echo %errorlevel%
0
```
The same thing happens with any `vkconfig` command (`version`, `layers`, `reset`) except `gui` (which, as expected, brings up the **Vulkan Configurator** dialog box).  Passing no command also brings up the dialog box (as expected).

I expect `vkconfig.exe help` on Windows to produce the same output as the Linux command-line usage, and all the other commands to work as intended on the Windows system:
```
$ vkconfig help
Usage
	vkconfig [[help] | [version] | [gui] | [layers <args>]]

Command:
	help                      = Display usage and documentation.
	version                   = Display Vulkan Configurator version.
	gui                       = Launch the Vulkan Configurator GUI.
	layers                    = Manage system Vulkan Layers.
	reset                     = Reset layers configurations.

  (Use 'vkconfig help <commamd>' for detailed usage of Vulkan Configurator commands.)
```
**VulkanTools** testing should also add a test case for `vkconfig` command lines.

This is needed for **Vulkan-ValidationLayers** live game performance testing.  Some games (apparently deliberately) cannot be configured to use layers through our normal control mechanisms; instead, we must rely on system-level overrides (e.g. through `vkconfig`, or through esoteric registry modifications to invoke the meta-layer).  Using `vkconfig` is considerably cleaner and more maintainable, but only if it can be made to work.

**Comment by christophe-lunarg** [comment]
I couldn't reproduce this issue...

**Comment by lunarpapillo** [comment]
It seems to be present on SDK 1.3.211.0:
```
> C:\VulkanSDK\1.3.211.0\Tools\vkconfig.exe help
```
produces no output.

**Comment by jmccarthy634** [comment]
Can confirm this issue is still present on SDK 1.3.224.1, none of the commands appear to output anything on the command line.

**Comment by christophe-lunarg** [comment]
@lunarpapillo, am I correct that this issue is actually a developer environment issue that you figured out? How can it be fixed?
This is not something I ever been able to reproduce.

**Comment by mickbeaver** [comment]
Hello. Without knowing more, this appears to be due to vkconfig2 being built as a Windows GUI application, as opposed to a console application. It seems it has been that way since https://github.com/LunarG/VulkanTools/commit/f68bf0cff5762b3ac68be02ce5531a9dacc3b0b9

In vkconfig/CMakeLists.txt, we have:
```
add_executable(vkconfig WIN32 ${FILES_ALL} ${CMAKE_CURRENT_SOURCE_DIR}/resourcefiles/vkconfig.rc)
```

**Comment by lunarpapillo** [comment]
> am I correct that this issue is actually a developer environment issue that you figured out? How can it be fixed?
This is not something I ever been able to reproduce.

I'm sorry, I actually have no additional insights into the issue.  I don't understand why you're not able to reproduce the same behaviors I see, @christophe-lunarg .  When you use `vkconfig.exe` on the command line, what output do you see?

**Comment by christophe-lunarg** [comment]
![image](https://user-images.githubusercontent.com/62888873/195100443-4cc8ced3-2d46-4cb4-909c-96b1598a02fa.png)

**Comment by christophe-lunarg** [comment]
![image](https://user-images.githubusercontent.com/62888873/195101155-bc909108-95bf-4605-b509-6545a0371a0a.png)

**Comment by christophe-lunarg** [comment]
Following @mickbeaver comment, I tryed to remove the WIN32 qualifier in CMake but that didn't change the behavior.

This said, his comment is relevant and it looks like we are just seeing the expected behavior for Windows GUI applications :
https://superuser.com/questions/1198821/how-do-i-read-the-console-output-of-a-windows-gui-application

**Comment by richard-lunarg** [comment]
This also "used" to work on Windows, I'm sure of it.

**Comment by christophe-lunarg** [comment]
The first version that had command line argument was the one with SDK 1.2.162.1:
![image](https://user-images.githubusercontent.com/62888873/195140897-0ce1a01c-5225-4e3c-b913-b2dad9ce7256.png)

![image](https://user-images.githubusercontent.com/62888873/195140956-4e07d305-9faf-4f6c-820e-2855d608c169.png)
