### ISSUE TITLE
UBuntu (22.04 alpha/beta what ever) no vkconfig

### ISSUE THREAD

**Issue by ericwomer** [LunarG/VulkanTools#1674]
No package in the ubuntu repositories provide vkconfig.

**Comment by KarenGhavam-lunarG** [comment]
LunarG creates Ubuntu packages for 18 and 20. See the SDK download page at vulkan.lunarg.com:

![image](https://user-images.githubusercontent.com/17237544/161548655-157d95c0-b283-4cc3-817f-f089790dda57.png)

**Comment by KarenGhavam-lunarG** [comment]
FYI. This repository is not the correct location for SDK (and Ubuntu packages delivered by LunarG) issues. If you would like to continue this discussion, please open the issue at vulkan.lunarg.com

Thanks!
