### ISSUE TITLE
Erroneous message when closing vkconfig.exe

### ISSUE THREAD

**Issue by ikapoura** [LunarG/VulkanTools#1684]
Hello there. I had an issue where my program was not requesting any validation layers upon device creation but I would still see validation layer messages. After some fiddling around, I found that I had the "Overriding Layers by the Vulkan Configurator" setting enabled, even though the Vulkan Configurator was not running. Setting this to "Layers Fully Controlled by the Vulkan Applications" solved the issue.

The problem is that when I am closing the Vulkan Configurator, I see the following message as in the attached image "No Vulkan layers override will be active when Vulkan Configurator closes.". This message suggests that closing the Vulkan Configurator with the "Override Layers..." option checked will not have any effects on the applications because the Configurator will be closed, but the override persists with the Configurator closed even after restarting the PC.

Is this message erroneous or I have misunderstood it? Thanks.

![2022-04-12_17h23_35](https://user-images.githubusercontent.com/40468844/162984448-9056012a-b073-4afd-8ee2-9df36d4ca9fb.png)

**Comment by christophe-lunarg** [comment]
Hi,
I just check the behavior to ensure it's correct and it looks correct.

If "Continue Overriding Layers on Exit" is checked then the selected "Vulkan Layers Configuration" will remain active when exicting Vulkan Configurator.

If "Continue Overriding Layers on Exit" is unchecked then the selected "Vulkan Layers Configuration" will be discarded giving back full control of the layers to the Vulkan application..

This said, for the layers configuration changes to be taken into account the Vulkan application need to be restarted or at least, the Vulkan instances needs to be destroyed on recreated.

Thanks,
Christophe

**Comment by ikapoura** [comment]
Hello Cristophe and thank you for the fast reply.

The behavior I am describing was happening without the "Continue Overriding..." checked. I now checked it, restarted vkconfig, unchecked it, closed vkconfig and I no longer have the issue.

Thank again,
Ilias
