### ISSUE TITLE
I can't build VulkanTools with the step :Android Build from Windows

### ISSUE THREAD

**Issue by 8426ty** [LunarG/VulkanTools#1698]
When start ndk-build, find the error" [armeabi-v7a] Compile++ thumb: VkLayer_api_dump <= api_dump.cpp
In file included from jni/../generated/include/api_dump.cpp:27:
jni/../generated/include/api_dump_text.h:4107:30: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const StdVideoH265PictureParameterSet')
    return settings.stream() << object;"
![image](https://user-images.githubusercontent.com/74665253/170233656-1e6747c5-a72d-4e38-ad10-17877af3ea72.png)

**Comment by 8426ty** [comment]
OK，I find the diff between "android-generate.bat" and "android-generate.sh".And modify "android-generate.bat" like that:

`py -3 %VT_SCRIPTS%\vt_genvk.py -registry %REGISTRY% -scripts %REGISTRY_PATH% api_dump.cpp -removeExtensions VK_KHR_video_queue -removeExtensions VK_KHR_video_decode_queue -removeExtensions VK_KHR_video_encode_queue -removeExtensions VK_EXT_video_decode_h264 -removeExtensions VK_EXT_video_decode_h265 -removeExtensions VK_EXT_video_encode_h264`

It looks like a bug, doesn't it?

**Comment by Tony-LunarG** [comment]
Fixed in #1706
