### ISSUE TITLE
API version in VIA is hardcoded to 1.2

### ISSUE THREAD

**Issue by krOoze** [LunarG/VulkanTools#1713]
E.g.:

https://github.com/LunarG/VulkanTools/blob/4da65beb7755f0ad227c8e633dbd5a422e3fe5d2/via/via_system_windows.cpp#L902

Meanwhile 1.3 is already out.

**Comment by davidlunarg** [comment]
Fixed in https://github.com/LunarG/VulkanTools/pull/1721
