### ISSUE TITLE
Layer Factory does not Build with MacOS

### ISSUE THREAD

**Issue by dasmysh** [LunarG/VulkanTools#1716]
This if in the CMakeLists.txt https://github.com/LunarG/VulkanTools/blob/fdfc762d8df37cf67b0e91176eb580fb81ffa626/layer_factory/CMakeLists.txt#L2 prevents the layer factory from being build in MacOS.

Adding a new branch can fix the issue:
```
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    add_definitions(-DMACOS)
    if (BUILD_MOLTENVK_SUPPORT)
        add_definitions(-DVK_USE_PLATFORM_MACOS_MVK)
    endif()

    if (BUILD_METAL_SUPPORT)
       add_definitions(-DVK_USE_PLATFORM_METAL_EXT)
    endif()
```

I would also suggest to remove the explicit setting of the C++ standard https://github.com/LunarG/VulkanTools/blob/fdfc762d8df37cf67b0e91176eb580fb81ffa626/layer_factory/CMakeLists.txt#L45 for non-windows builds so that users can pass it from command line using '-DCMAKE_CXX_STANDARD=17' for example.

I could create a PR for this if that would help.

**Comment by richard-lunarg** [comment]
I'd wager you are the first one to try and build this on the Mac! Go ahead and create a PR for the cmake changes, as it appears to work with these changes. I don't know who is relying on the C++ standard code, so I'd create a separate issue for that to see if anyone has thoughts on it.

**Comment by dasmysh** [comment]
There is also another (slightly bigger) issue if you try to cross-compile on ARM Macs for x64 platforms (not sure if the other way is possible, but it would have the same issue). This involves also changing the `scripts/update_deps.py` script to pass the correct CMake flag to the dependencies builds (`-DCMAKE_OSX_ARCHITECTURES`) would this also be a separate PR or can this go directly into the Mac fix (and is this even something that you want to support)?

**Comment by richard-lunarg** [comment]
I'm able to build for Apple silicon and/or X86 just using environment variables:

ARCHS  = "x86_64 arm64"
ONLY_ACTIVE_ARCH = "NO"
CMAKE_OSX_ARCHITECTURES = "x86_64;arm64"

I can build the entire SDK and all it's repositories anyway I wish, just by tweaking these environment variables.

**Comment by dasmysh** [comment]
Including the layer factory? How would you get around the if/fatal error in the beginning? Otherwise thanks for the environment variables, that simplifies things a lot.

**Comment by richard-lunarg** [comment]
Ah no. The SDK build does not include the layer factory (it was removed right after I joined LunarG a while back).
But these environment variables will give you combined ARM/Intel builds of any libraries built with CMake and the XCode tools.

**Comment by KarenGhavam-lunarG** [comment]
The layer factory has been removed from this repository and archived [here.](https://github.com/LunarG/Vulkan-Layer-Factory) There are not any plans to add macOS support for the layer factory.
