### ISSUE TITLE
Validation error in screenshot layer

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#1737]
If vkcube is run with validation and screenshot enabled, and the output format is set to UINT, the following validation error message is displayed:

VUID-vkCmdBlitImage-srcImage-00230(ERROR / SPEC): msgNum: 569695033 - Validation Error: [ VUID-vkCmdBlitImage-srcImage-00230 ] Object 0: handle = 0x1fa202e0380, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x21f4db39 | vkCmdBlitImage: If one of srcImage and dstImage images has unsigned integer format, the other one must also have unsigned integer format.  Source format is VK_FORMAT_B8G8R8A8_UNORM Destination format is VK_FORMAT_R8G8B8A8_UINT. The Vulkan spec states: If either of srcImage or dstImage was created with an unsigned integer VkFormat, the other must also have been created with an unsigned integer VkFormat (https://vulkan.lunarg.com/doc/view/1.3.224.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdBlitImage-srcImage-00230)

This issue was originally submitted as https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/1112 by @ziga-lunarg

**Comment by juan-lunarg** [comment]
Closed by @davidlunarg in https://github.com/LunarG/VulkanTools/pull/1738/files

**Comment by juan-lunarg** [comment]
Verified this is fixed by @davidlunarg 's PR by running validation with screenshot layer:
```
Selected GPU 0: Apple M2 Max, type: IntegratedGpu

screenshot: Incompatible output format requested, changing output format to VK_FORMAT_B8G8R8A8_UNORM

screenshot: Capture file is: /Users/juanramos/VulkanSDK/1.ppm 

Process terminated
```

**Comment by juan-lunarg** [comment]
I updated the SDK screenshot layer testing regardless though to ensure this stays fixed.
