### ISSUE TITLE
layer manifest file format documentation does not match layers_schema.json

### ISSUE THREAD

**Issue by Waffl3x** [LunarG/VulkanTools#1756]
The layers manifest documentation [located here](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/docs/LoaderLayerInterface.md#layer-manifest-file-format) does not appear to match the [layers_schema.json located here](https://github.com/LunarG/VulkanTools/blob/master/vkconfig_core/layers/layers_schema.json).
My specific issue is that it is not specified if the json object with name "layer" is optional, but there is an example that uses the "layers" node that lacks a "layer" node. The layers_schema.json appears to require a "layer" node despite this. If I am mistaken in my interpretation of the layers schema please let me know.
I request that the documentation is updated to be more specific in it's requirements, and if there's a more detail spec somewhere please let me know as I couldn't find one.

If it is that "layer" is mandatory and "layers" is optional, I also would like to know the correct way of handling it. In the [Vulkan-Loader source code](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/loader/loader.c#L2578-L2632) it's handled by checking first for a "layers" node, and falling back to checking for a "layer" node, however it also supports other violations so I would like clarification on what is actually required.

I intend to use the layers_schema to validate discovered layers, so I would prefer it doesn't fail on a layer manifest that is legal.
I recognize this isn't necessarily the right place to post this issue, but I figure that if the documentation is correct as is, the layers_schema.json needs to be changed to reflect it. Or perhaps I'm just reading the layers_schema.json wrong and there is more than one description of requirements. The lines in the schema that I am referring to can be found [here.](https://github.com/LunarG/VulkanTools/blob/master/vkconfig_core/layers/layers_schema.json#L7-L10)

 edit:
The documentation states this [here](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/docs/LoaderLayerInterface.md#layer-manifest-file-version-101):
> The ability to define multiple layers using the "layers" array was added. This JSON array field can be used when defining a single layer or multiple layers. The "layer" field is still present and valid for a single layer definition.

Given the behavior of the loader, I feel like this description is inaccurate, but at the very least, the schema should reflect that "layer" object is optional when a "layers" object is present.

edit2:
I have just noticed this comment in the loader source code
```
    // The following Fields in layer manifest file that are required:
    //   - "file_format_version"
    //   - If more than one "layer" object are used, then the "layers" array is
    //     required
```
this leads me to believe that it's acknowledged that "layer" and "layers" are mutually exclusive, it just needs to be formalized.

**Comment by charles-lunarg** [comment]
This should be resolved by [this PR in the Vulkan-Loader](https://github.com/KhronosGroup/Vulkan-Loader/pull/1273)

My intent is to combine the two schema's (layer_schema.json and the ones I devised that fully describe the layer manifests as far as the loader is concerned).

Doing that should allow the layer_schema.json in this repo to be removed, since it is redundant.

**Comment by christophe-lunarg** [comment]
I am closing this as it's being resolved in the Vulkan Loader repository.
