### ISSUE TITLE
Screenshot layer crashes if frames is not a number

### ISSUE THREAD

**Issue by ziga-lunarg** [LunarG/VulkanTools#1757]
I launched vkcube from vkconfig with screenshot layer enabled and set frames to an invalid value, either text or a negative number and the vkcube crashed.

**Comment by juan-lunarg** [comment]
Just checked. A negative number and text won't cause a crash.

Although you don't get good error messages either.

This was likely fixed when we updated to use the utility libraries FYI @christophe-lunarg :
https://github.com/LunarG/VulkanTools/commit/7da7301034e48ef4acf9ddfb5e138dc0768c3689

**Comment by juan-lunarg** [comment]
I updated the SDK screenshot layer testing regardless though to ensure this stays fixed.
