### ISSUE TITLE
Repo Description Mentions Trace/Replay

### ISSUE THREAD

**Issue by andrew-lunarg** [LunarG/VulkanTools#1758]
About
Tools to aid in Vulkan development including useful layers, trace and replay, and tests

![image](https://user-images.githubusercontent.com/105252583/199579893-fbf24b8b-5e07-446b-b3a7-6fe218a0aeec.png)

**Comment by Tony-LunarG** [comment]
In the days of vktrace and vkreplay, that was true.  Those are now long gone.

**Comment by Tony-LunarG** [comment]
Fixed
