### ISSUE TITLE
Add README with reference to upstream external repo & commit

### ISSUE THREAD

**Issue by mew-cx** [LunarG/VulkanTools#1761]
It would be useful to have a README which documents exactly which upstream repo and commit was used to populate https://github.com/LunarG/VulkanTools/tree/master/external/valijson

Perhaps the upstream is https://github.com/tristanpenman/valijson, maybe a fork, maybe some other source?
At what commit/tag?

**Comment by juan-lunarg** [comment]
This will be documented in the known_good.json like the other dependencies. Apologies for the delay.

This will be fixed by end of day.

**Comment by juan-lunarg** [comment]
We are currently using the v1.0 tag FWIW:
https://github.com/LunarG/VulkanTools/blob/51f670a8ae1fae13054900567d35d126c14daae1/scripts/known_good.json#L103C8-L103C8
