### ISSUE TITLE
DevSim simulation of missing extensions

### ISSUE THREAD

**Issue by stezkmil** [LunarG/VulkanTools#1765]
Hi,

I just wanted to ask if it would be possible to simulate a missing extension. Here is the scenario I have been facing. I wanted to emulate nVidia Quadro T2000 on my Quadro P5000. For our app the problem was a crash when the
`{
			"extensionName": "VK_KHR_acceleration_structure",
			"specVersion": 12
}
`
extension was missing, but I did not get any sign of this extension missing when I had the simulation layer enabled. I think it would be very useful to have this, because I had to obtain the real hardware to diagnose this, which is always a bit problematic.

Regards,
Milan

**Comment by christophe-lunarg** [comment]
Hi Milan,
Are you using the Profiles layer or the Devsim layer?

The Devsim layer has been deleted. With the Profiles layer you should have this working.

Thanks,
Christophe

**Comment by stezkmil** [comment]
Thanks for the info about the profiles layer. Didn't know about this one. Thing is that in our corporate environment, adopting a new version of the Vulkan SDK is a very rare event, so I am stuck with the DevSim layer for the time being.
