### ISSUE TITLE
Recent change to VVL causes vkconfig to crash when setting a custom path to the VVL build directory

### ISSUE THREAD

**Issue by charles-lunarg** [LunarG/VulkanTools#1773]
Commit in question: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/cce8087a05e065ffd0bc1a09d8d5eadade82505f

This happens on linux and windows, so does not appear to be a OS specific issue.

**Comment by christophe-lunarg** [comment]
Hi Charles,

I reproduced this issue and actually this issue was already fixed when I added the support for this change in vkconfig.
Testing the SDK 1.3.235 tmp build or a master branch build, this issue doesn't reproduce.

Thanks
