### ISSUE TITLE
cube/vkcube: libvulkan_intel.so: undefined symbol: drmSyncobjTimelineWait [Ubuntu 20.04]

### ISSUE THREAD

**Issue by gitthnx** [LunarG/VulkanTools#1779]
`lsbrelease -a`  

> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.5 LTS
> Release:	20.04
> Codename:	focal
> 

cube/vkcube: symbol lookup error: /usr/lib/x86_64-linux-gnu/libvulkan_intel.so: undefined symbol: drmSyncobjTimelineWait

`ldd -r /usr/lib/x86_64-linux-gnu/libvulkan_intel.so`

> [ ]
> undefined symbol: drmSyncobjQuery	(/usr/lib/x86_64-linux-gnu/libvulkan_intel.so)
> undefined symbol: drmSyncobjTimelineWait	(/usr/lib/x86_64-linux-gnu/libvulkan_intel.so)
> undefined symbol: drmSyncobjTimelineSignal	(/usr/lib/x86_64-linux-gnu/libvulkan_intel.so)

(thx)

**Comment by Tony-LunarG** [comment]
Vkcube lives in the https://github.com/KhronosGroup/Vulkan-Tools repo, but this looks like more of a Mesa driver issue since the symbols are missing from the Intel Mesa driver.  I would ask the Mesa folks, but if you really think it is an issue with vkcube, pleas open an issue in Vulkan-Tools.
