### ISSUE TITLE
GLSLang package in Vulkan SDK is missing the header file glslang_c_interface.h

### ISSUE THREAD

**Issue by corporateshark** [LunarG/VulkanTools#1787]
`glslang/Include/glslang_c_interface.h` should be a part of the GLSLang package.

It should be placed here: `VulkanSDK/1.3.236.0/Include/glslang/Include/glslang_c_interface.h`

**Comment by Tony-LunarG** [comment]
SDK issues are usually filed in Lunar Exchange.  Filed here:
https://vulkan.lunarg.com/issue/view/63d158a85df11200d569b2ab

**Comment by corporateshark** [comment]
@Tony-LunarG Thanks!

I think this ticket https://vulkan.lunarg.com/issue/view/631adb345df112f88f25d523 is related as it describes a similar packaging issue.

**Comment by KarenGhavam-lunarG** [comment]
Sergey,

Would you please go to the [LunarXchange issue](https://vulkan.lunarg.com/issue/view/63d158a85df11200d569b2ab) and set yourself up for notifications (watch)? 

Also indicate that you believe this is related to  https://vulkan.lunarg.com/issue/view/631adb345df112f88f25d523

This issue will get closed and the LunarXchange issue will be the method for you to get any updates.

Thanks!

**Comment by juan-lunarg** [comment]
Closing due to this not being a LunarG/VulkanTools issue.
