### ISSUE TITLE
vkconfig wayland issue

### ISSUE THREAD

**Issue by juan-lunarg** [LunarG/VulkanTools#1796]
Force enabled Wayland, and vkconfig wouldn't run.

```
$ vkconfig
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
$ vim .bashrc # export QT_QPA_PLATFORM=wayland
$ source ~/.bashrc
$ vkconfig
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

This doesn't really matter for current LTS releases but the my understanding is more Distros will start using Wayland as the default now that Nvidia supports it better.

**Comment by richard-lunarg** [comment]
Try this?
sudo apt-get install -y qtwayland5

**Comment by juan-lunarg** [comment]
Looks like that works. Just needs to be addressed as part of the SDK now.

+ @johnzupin for Ubuntu / Tarball packages

**Comment by johnzupin** [comment]
Thanks for finding this, this is an easy fix for Ubuntu. I build QT5 from source for the tarball, probably need to enable a build flag for qt5 to fix this.

**Comment by johnzupin** [comment]
Maybe I misunderstood, it looks like I am building with qtwayland support but this qtwayland5 run-time platform plugin dependency needs to be installed? I can update the docs for tarball and ubuntu package dependencies if so.

**Comment by juan-lunarg** [comment]
Yes there is currently a missing runtime dependency if you actually try to run wayland with our provided package/tarball

**Comment by juan-lunarg** [comment]
closed. This was an issue with the packaging for the SDK.
