### ISSUE TITLE
vkconfig freezes when a custom user-defined manifest path is selected.

### ISSUE THREAD

**Issue by nikitablack** [LunarG/VulkanTools#1802]
I have built the validation layers from sources and want to set the path to the manifest file in the Vulkan Configurator. I select `New` -> `Add User-Defined Path...` -> `path to the folder with VkLayer_khronos_validation.json`. That freezes the tool.

However, selecting a standard path with manifests installed with the SDK (`/usr/share/vulkan/explicit_layer.d`) works fine. Here is the [compressed json file](https://github.com/LunarG/VulkanTools/files/11042419/VkLayer_khronos_validation.zip) that causes the problem. It was built using the standard build procedure from [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/BUILD.md).

Os: Ubuntu 18.04
Vulkan Configurator: 2.5.0

**Comment by christophe-lunarg** [comment]
Hi,
I believe this issue didn't show up once using Vulkan Configurator 2.5.1 but the issue remained and was linked to potential mismatch of layers configurations directory which should be fixed.

Thanks for reporting!
