### ISSUE TITLE
vkconfig doc output: "Setting Default Value" should be on separate line

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#1815]
The "vkconfig doc" cmd is used to auto-generate layer documentation via scripts in in the Vulkan-SDK-Packaging repo.

The description of env vars in the auto-gen documentation has a line containing "Setting Default Value" and a value. This text should be on it's own line. For example, in the description for VK_APIDUMP_OUTPUT_RANGE in https://vulkan.lunarg.com/doc/sdk/1.3.243.0/windows/api_dump_layer.html, the line that reads "Setting Type: STRING - Setting Default Value: 0-0" should broken up into two lines with "Setting Default Value: 0-0" on a new line. Also, both "Setting Type" and "Setting Default Value" should probably be a bullet item in the bullet list under "Setting Properties".

Here's is an image with the lines that should be broken up underlined:
![AutoGenImage](https://user-images.githubusercontent.com/10409469/233734664-ad24b6db-e673-402a-8bc2-b784cfcd784e.png)

**Comment by charles-lunarg** [comment]
Closing as it appears to have been fixed in the 1.3.250 SDK docs.
