### ISSUE TITLE
Trim crashes when used with screenshot layer

### ISSUE THREAD

**Issue by ardaLunarG** [LunarG/VulkanTools#182]
When I enable screenshot layer with trim
- Vktrace dumps heap and crashes
- vkreplay crashes

**Comment by plohrmann** [comment]
I've identified the issue, and a fix is pending internal code review.
* Screenshot layer is caching a VkCommandPool object to use, but didn't handle the situation that the CommandPool got destroyed. The simple solution is to keep a most-recently-created list of command pools, remove items from the list if they are destroyed, then take the CommandPool that is at the front of the list when the screenshot is saved.

**Comment by ardaLunarG** [comment]
fixed
