### ISSUE TITLE
vkconfig: Spaces in command-line arguments cannot be escaped

### ISSUE THREAD

**Issue by pierremoreau** [LunarG/VulkanTools#1828]
vkconfig currently splits the argument string using `.split(" ")`, so a path containing a space will always end up broken into two separate arguments no matter whether the path was enclosed in quotes or the space was escaped.

**Comment by christophe-lunarg** [comment]
I wish I found a way people are resolving this as it took me a while a do something that handles hopefully all the cases... but that's really tricky and I don't know exactly what's the expected/typical behavior for this.

Thanks for reporting!
