### ISSUE TITLE
Api Dump for cooperative_matrix and external_memory_screen_buffer disabled

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#1840]
Api dump codegen for VK_NV_cooperative_matrix and VK_QNX_external_memory_screen_buffer was disabled to facilitate the next SDK because there were compile failures in the generated code.  Once fixed, those two extensions should be reenabled

**Comment by charles-lunarg** [comment]
This is partially fixed in #1856
