### ISSUE TITLE
No layer factory template in SDK.

### ISSUE THREAD

**Issue by zamirez** [LunarG/VulkanTools#1842]
Copy of #963 but for the latest 1.3.250.1 version.

https://vulkan.lunarg.com/doc/sdk/1.3.250.1/windows/layer_factory.html states that the template should be in %VULKAN_SDK%\Templates\Visual Studio 201x\VulkanLayer.zip, but it's not.

![image](https://github.com/LunarG/VulkanTools/assets/140101101/0db5a825-f0f2-4346-b896-faf8fb744ddf)

Is there still support for layer_factory? I saw #1822 so I understand it may not be as maintained but it's unclear to me if it's totally unusable for generating a simple layer or if I can modify a few things(and what that would entail) to get it working.

**Comment by KarenGhavam-lunarG** [comment]
The layer factor was removed from the SDK over a year ago. It is not maintained and will be moved to a read-only repository soon.

The link to the documentation you must have created manually from a previous SDK link (just updated SDK version). The documentation file might be out there. But from the SDK documentation at vulkan.lunarg.com (left panel), there is no way to link to this documentation. There may be old files we are not deleting that enables you to see this no longer supported file.

**Comment by KarenGhavam-lunarG** [comment]
The layer factory has been removed from this repository and archived [here](https://github.com/LunarG/Vulkan-Layer-Factory).
