### ISSUE TITLE
Physical Device Selection by Device UUID does not work

### ISSUE THREAD

**Issue by asuessenbach** [LunarG/VulkanTools#1844]
Using the Vulkan Configurator 2.5.4 from the Vulkan SDK 1.3.250.1, I try to use "Physical Device Selection" with "Force Device (BETA)" set to "Using Device UUID", running on Win10.
With a dual device machine, setting the UUID to one of the two devices, I would expect to have that device as the only one when running a vulkan progam. But I get the following message:
`Force physical device by device name is active but the requested physical device '408d1cc6-c3c9-8848-904e-3758748a5cb5'('') couldn't be found.`
Is that message wrong (as it says "by device name" instead of "by device uuid"), the UUID I provide somehow ill-formatted, or that feature not working as I expected?

**Comment by christophe-lunarg** [comment]
The syntax of the UUID is correct in the message. You can copy the UUID from the log:

![force_gpu_selection_by_uuid](https://github.com/LunarG/VulkanTools/assets/62888873/81d9a806-af06-4cc7-85ff-f60b4429c88f)

I'll improve the Profile layer error message.
