### ISSUE TITLE
Information about Trim (Beta)

### ISSUE THREAD

**Issue by ardaLunarG** [LunarG/VulkanTools#186]
This is functionality is implemented such that at trace-time you can enable and disable frame tracing on-demand. Currently this only supports being able to generate a single trace file from a single enable/disable tracing pair. Vktrace could be extended in the future to support multiple trims from a single run of the application, but it requires some restructuring to the communication between vktrace and the vktrace_layer and how vktrace recognizes that a new trace file should be created and / or saved. It was beyond the immediate scope of this feature.

Enable this feature by setting environment variable "VKTRACE_TRIM_TRIGGER="
can be of the format:
"frames-,"
"frames--"
"hotkey-"

can be F1 through F12, or Tab, ControlLeft, ControlRight on Linux, or TAB, CONTROL on Windows

There will be a pause in the gameplay when trim becomes enabled while it stores a snapshot of all the objects and buffer contents, and another pause when trim is disabled and all the necessary trace packets are written to the trace file.

While the trim is enabled and recording trace packets, memory consumption will climb because the trace packets are stored in memory for post-processing to eliminate some unneeded objects. We have alternatives to this but as they are considered optimizations we decided to leave them until another time. Because of the increasing memory consumption, it is recommended that trims not last longer than 1-2 minutes, but that's highly dependent on your system and the application you are recording.

Note: Trim is added as (Beta) and has known issues.

**Comment by davidlunarg** [comment]
Trim is now implemented. Closing.
