### ISSUE TITLE
apidump broken with GPL

### ISSUE THREAD

**Issue by zmike** [LunarG/VulkanTools#1860]
The apidump layer doesn't follow GPL rules regarding which members of pipeline create structs can be read in a given stage

This is the same issue I reported in VVL https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5609

**Comment by charles-lunarg** [comment]
Thanks for reporting this.
Are you able to validate whether the linked PR fixes the issue? Do note that the autogen is not checked in, so building it & running it would be the easiest way to verify.

**Comment by zmike** [comment]
Sorry, I've been swamped this week. I'll double check soon and report back if it's not fixed.
