### ISSUE TITLE
Vulkan SDK installer for Mac "vold haders" presumably should be "volk headers"

### ISSUE THREAD

**Issue by tim-rex** [LunarG/VulkanTools#1863]
The Vulkan SDK installer for Mac shows a text description referencing "vold haders"
Presumably this should say "volk headers"

See image attached
![image](https://github.com/LunarG/VulkanTools/assets/19639392/816a6143-966f-4ac2-bdc1-d130131cfff6)

**Comment by richard-lunarg** [comment]
Indeed it should. Thanks for reporting this!

**Comment by richard-lunarg** [comment]
Fixed internally, will be in the next release.
