### ISSUE TITLE
Incorrect structure type reported in pNext chain of device create info

### ISSUE THREAD

**Issue by SollyCB** [LunarG/VulkanTools#1882]
The validation layers see a VK_STRUCTURE_TYPE_PRIVATE_DATA_SLOT_CREATE_INFO.  This happens with shader object layer on and the extension enabled. With the extension disabled and the layer enabled, it does not happen. 

I cannot tell if this is a bug with the validation layers or the shader object layer.  But it definitely seems like a bug, as I could not typo in a create info structure.

**Comment by KarenGhavam-lunarG** [comment]
This may be an issue against the shader object emulation layer which is in the [Vulkan-ExtensionLayer](https://github.com/KhronosGroup/Vulkan-ExtensionLayer) repository. I recommend you submit this issue to that repository.

**Comment by juan-lunarg** [comment]
FYI @ziga-lunarg

**Comment by juan-lunarg** [comment]
Moved the issue to the extension layer repo:
https://github.com/KhronosGroup/Vulkan-ExtensionLayer/issues/344
