### ISSUE TITLE
VkConfig is trying to load the wrong profile

### ISSUE THREAD

**Issue by ziga-lunarg** [LunarG/VulkanTools#1894]
If I select the Portability layer, and select any layer other than `VP_LUNARG_desktop_portability_2022.json`, I will get a message like this: 

> "VP_LUNARG_desktop_portability_2022" profile could not be found in "C:/VulkanSDK/1.3.261.1/Config/VK_LAYER_KHRONOS_profiles/VP_KHR_roadmap_2022.json" file. Loading the default "VP_KHR_roadmap_2022" profile of the file.

**Comment by christophe-lunarg** [comment]
This issue should be fixed with next SDK
