### ISSUE TITLE
vkconfig related unit test failing on macOS

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#1897]
One of the unit tests (test_path.get_path_vulkan_sdk) is failing on macOS:

The output is:
/Users/lunarg/Dev/MacOS-CI/VulkanTools/vkconfig_core/test/test_path.cpp:165: Failure
Expected equality of these values:
  ConvertNativeSeparators("~/VulkanSDK").c_str()
    Which is: "~/VulkanSDK"
  value.c_str()
    Which is: "~/VulkanSDK/share/vulkan"

[  FAILED  ] test_path.get_path_vulkan_sdk (0 ms)

**Comment by juan-lunarg** [comment]
https://github.com/LunarG/VulkanTools/pull/1911
