### ISSUE TITLE
Screenshot error message confusing (from 1.3.2680.SDK)

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#1906]
Trying to use USE_SWAPCHAIN_COLORSPACE I get the following message:

> screenshot: Selected format:USE_SWAPCHAIN_COLORSPACE
> Is NOT in the list:
> UNORM, SNORM, USCALED, SSCALED, UINT, SINT, SRGB
> Swapchain Colorspace will be used instead

This is confusing, is swapchain colorspace not in the list but it will be used? What is the error? The message could also explain what the list is. 

I don't remember seeing this message ever before

**Comment by juan-lunarg** [comment]
Yeah this is confusing and is a regression. I'll fix this ASAP.
