### ISSUE TITLE
macOS: Hardcoded paths for loader / layers / settings

### ISSUE THREAD

**Issue by mizvekov** [LunarG/VulkanTools#1909]
To support bundling these tools on package managers, we need to allow the paths to be customized, not hardcoded assuming VulkanSDK locations.

For example, homebrew installs loader and layers on a separate prefix, typically `/opt/homebrew`.
Similarly, it has an `etc` inside that prefix which we should use instead, for the settings.

**Comment by juan-lunarg** [comment]
Which tool in particular are you talking about? This repo houses various utilities.

**Comment by mizvekov** [comment]
Both via and vkconfig are affected by this.

**Comment by christophe-lunarg** [comment]
Hi @mizvekov,

I don't know how `homebrew` is working, how others projects figured the path is /opt/homebrew?

**Comment by mizvekov** [comment]
They can figure out the path to libvulkan.a through cmake config or pkgconfig.
Some times the path is passed through the build system command line.
Otherwise, I would expect they then would find the loader `.so` using the normal mechanisms.

I think the same problem should exist for linux in multiarch distributions, or otherwise ones which allow multiple versions of the same library to be installed.

I can't find an example of a linux distribution packaging these tools, as opposed to the Khronos Vulkan-Tools, but I would expect that if they did, they would run into the same kind of issues.

**Comment by juan-lunarg** [comment]
> I can't find an example of a linux distribution packaging these tools, as opposed to the Khronos Vulkan-Tools, but I would expect that if they did, they would run into the same kind of issues.

Archlinux does package LunarG/VulkanTools:
https://gitlab.archlinux.org/archlinux/packaging/packages?filter=vulkan

Perhaps that could be a useful reference?

**Comment by mizvekov** [comment]
Yeah, archlinux is one of the simplest examples you can find though, and the existing hardcoded paths cover it.

For debian based. you have `/usr/lib/<target_triple>`, and there are a lot of arches and variants out there.
The current source code has just the triples for x86_64 and i386 hardcoded.

On my debian x86_64 system, I can install the Vulcan loader for armhf like so:
```sh
apt install libvulkan1:armhf
```

And this gets installed at `/usr/lib/arm-linux-gnueabihf/libvulkan.so.1`.

**Comment by christophe-lunarg** [comment]
Hi @mizvekov,

I have no idea how to resolve this issue.  If you could give me more precise information on what needs to be done has I don't have experience with package managers. Is there specific a environment variable for this? Same for CMake?

**Comment by mizvekov** [comment]
Hi, sorry for dropping this and taking so long to respond.

The basic idea here is to offer customization for specifying installation directories at the build system level.

The most common way within cmake would be to use [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module, or handcoding similar functionality.

You can offer a default organization, where user just passes install-dir to the build system, and all other directories are derived from it, but the important detail is to allow the user to override this organization. For example, he can pass SYSCONFDIR just to change where what goes in `/etc` should logically be, and similarly, and more relevant here, he can pass LIBDIR to specify where libraries go.

These paths can be either relative, where they will be relative to the install-dir, or they can be absolute.

**Comment by christophe-lunarg** [comment]
I believe this issue is fixed with https://github.com/LunarG/VulkanTools/pull/2019 but really I don't know enough about this. 

So if doesn't work for you, please create a PR.

Thanks
