### ISSUE TITLE
can not follow build instructions without Khronos account

### ISSUE THREAD

**Issue by sheepdestroyer** [LunarG/VulkanTools#2]
````
...
git clone -o khronos git@gitlab.khronos.org:vulkan/LoaderAndValidationLayers.git
Cloning into 'LoaderAndValidationLayers'...
The authenticity of host 'gitlab.khronos.org (45.55.52.146)' can't be established.
...
Warning: Permanently added 'gitlab.khronos.org,45.55.52.146' (ECDSA) to the list of known hosts.
git@gitlab.khronos.org's password: 
Permission denied, please try again.
...
````

**Comment by sheepdestroyer** [comment]
I just want to build the intel driver, do I need the full stack?

**Comment by karl-lunarg** [comment]
We've just pushed a commit to https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers that updates the instructions to point to the public Khronos repos, for which you do not need an account.

You will need LoaderAndValidationLayers and VulkanTools to build the intel driver in VulkanTools.
