### ISSUE TITLE
Feature request: a way to see the section of the manifest that defines each layer option

### ISSUE THREAD

**Issue by jeremyg-lunarg** [LunarG/VulkanTools#2081]
It would be helpful to have a right click or popup that shows the json for a configuration option. This would make it easier to understand how to set options via environment variables or VK_EXT_layer_settings.

**Comment by jeremyg-lunarg** [comment]
In the same project:

- vk_ray_tracing_gltf_KHR - 6.5 fps
- vk_ray_tracing_indirect_scissor_KHR - 5fps
- vk_ray_tracing_instances_KHR - 12 fps
- vk_ray_tracing_intersection_KHR - 15 fps
- vk_ray_tracing_motionblur_KHR - 8 fps

**Comment by christophe-lunarg** [comment]
Hi @jeremyg-lunarg ! 
I think this is already something you can do.
- Right click on the settings tree and you can export the vk_layer_settings.txt file 
- Or right click on the layer to display the layer doc which includes the list of settings.

**Comment by christophe-lunarg** [comment]
> In the same project:
> 
> * vk_ray_tracing_gltf_KHR - 6.5 fps
> * vk_ray_tracing_indirect_scissor_KHR - 5fps
> * vk_ray_tracing_instances_KHR - 12 fps
> * vk_ray_tracing_intersection_KHR - 15 fps
> * vk_ray_tracing_motionblur_KHR - 8 fps

Miss post?

**Comment by jeremyg-lunarg** [comment]
> > In the same project:
> > 
> > * vk_ray_tracing_gltf_KHR - 6.5 fps
> > * vk_ray_tracing_indirect_scissor_KHR - 5fps
> > * vk_ray_tracing_instances_KHR - 12 fps
> > * vk_ray_tracing_intersection_KHR - 15 fps
> > * vk_ray_tracing_motionblur_KHR - 8 fps
> 
> Miss post?

Yep that's for a bug for Spencer... sorry.

**Comment by jeremyg-lunarg** [comment]
good enough, thanks!
