### ISSUE TITLE
WoA Vulkan SDK is broken due to https://github.com/KhronosGroup/SPIRV-Tools/issues/5762

### ISSUE THREAD

**Issue by mtavenrath** [LunarG/VulkanTools#2092]
SPIRV-val & the shader portion of the validation layers are broken due to a bug in the MSVC ARM64 compiler. It'd be good to release a new version of the SDK for WoA one a fix for this issue has been merged.

**Comment by KarenGhavam-lunarG** [comment]
The L[unarXchange issue](https://vulkan.lunarg.com/issue/view/66b380718ce88db27e3641fc) will be used for tracking fix and delivery of this issue.

I am closing this issue so it is only tracked in one location.
