### ISSUE TITLE
vkconfig: API dump - Log Filename ignored

### ISSUE THREAD

**Issue by dorian-apanel-intel** [LunarG/VulkanTools#2112]
When writing the API dump output to a file, it is always saved as stdout in the current working directory, regardless of the filename specified.

Steps to reproduce:

1. Launch `vkconfig`.
2. In the "Vulkan Layers Management" section, set the option to `Layers Controlled by The Vulkan Configurator`.
3. In the "Vulkan Layers Configurations" section, select `API Dump`.
4. In the "API Dump Settings" section, choose `Output to File`.
5. In the "Log Filename" field, enter `vk_apidump.txt`.
6. Open the file located at `%LOCALAPPDATA%\LunarG\vkconfig\override\vk_layer_settings.txt `and observe the following entry:
7. `lunarg_api_dump.log_filename = stdout`

Expected behavior: The log filename should be `vk_apidump.txt`, not `stdout`.

**Comment by christophe-lunarg** [comment]
This issue should be fixed with https://github.com/LunarG/VulkanTools/pull/2116.

Thanks for contributing!
