### ISSUE TITLE
vkconfig3 duplicated paths in Vulkan Layers Location

### ISSUE THREAD

**Issue by ziga-lunarg** [LunarG/VulkanTools#2181]
![image](https://github.com/user-attachments/assets/5c041fc3-aea4-4925-be8e-5d3d76797212)

If I uncheck the first checkbox, the second checkbox will also be unselected.

**Comment by christophe-lunarg** [comment]
This issue is resolved with https://github.com/LunarG/VulkanTools/pull/2202
