### ISSUE TITLE
vkconfig3: Command line issues

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#2186]
On macOS, having run source setup-env.sh there are some issues with the command line version.

Listing layers:
vkconfig layers --list

This command lists all the layers twice.
e.g.   
VK_LAYER_LUNARG_api_dump
VK_LAYER_KHRONOS_profiles
VK_LAYER_KHRONOS_shader_object
VK_LAYER_KHRONOS_synchronization2
VK_LAYER_KHRONOS_validation
VK_LAYER_LUNARG_screenshot
VK_LAYER_LUNARG_api_dump
VK_LAYER_LUNARG_screenshot
VK_LAYER_LUNARG_api_dump
VK_LAYER_KHRONOS_profiles
VK_LAYER_KHRONOS_shader_object
VK_LAYER_KHRONOS_synchronization2
VK_LAYER_KHRONOS_validation
VK_LAYER_LUNARG_screenshot

Loading a configuration just fails:
vkconfig layers --override ./TestSTandardValidation.json
e.g.
vkconfig: Failed to load ./TestSTandardValidation.json layers configuration file...

Ah, so this one... it won't load in the GUI either. Probably you've changed the format of the json? If so, it would be nice to import old one's anyway, and perhaps upgrade it, or just honor an existing config file. Bug or feature I'll leave to you, but anyone else using this feature will probably at least grimace ;-)

**Comment by christophe-lunarg** [comment]
I'll separate this issue into two differents issues:
- This one for the command line --list issue
- One new issue for Vulkan Configurator 2 configuration compatibility which I would see has a feature request. Not sure this is really possible.

**Comment by richard-lunarg** [comment]
The SDK automated tests relies on both of these features. We need a way to activate a configuration from the command line.

**Comment by christophe-lunarg** [comment]
Right click to open the context menu on a configuration in the UI to export it.

**Comment by christophe-lunarg** [comment]
This issue is resolved by https://github.com/LunarG/VulkanTools/pull/2202
