### ISSUE TITLE
vkconfig3: Reset doesn't reset everything

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#2192]
Reset button here:
![image](https://github.com/user-attachments/assets/89ccc747-223e-4628-a415-046faec7657a)

Does not reset
- Vulkan Layers Location
- System Diagnostic (Keep running and VK_HOME options)
- Tray icon state

**Comment by christophe-lunarg** [comment]
This issue should be resolved thanks to this PR: https://github.com/LunarG/VulkanTools/pull/2204

With the new approach, they should be no left over anymore as reset to default delete the saved files and restart vkconfig3 like it is the first start.
