### ISSUE TITLE
vkconfig3: Adding new layer locations to existing configs bugged

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#2193]
Adding a new layer in a custom location:
![image](https://github.com/user-attachments/assets/951ef18f-2a8a-40ee-8e28-d5894c458ccf)

The new layer gets added to the top of existing configuration and cannot be configured:
![image](https://github.com/user-attachments/assets/aba024ca-8359-4642-9df9-173f4c4c2be3)

Restarting vkconfig-gui fixes it

**Comment by christophe-lunarg** [comment]
I reproduced this issue a bit differently.

But yes, adding a new layer, caused issues, I'll fix it.

**Comment by christophe-lunarg** [comment]
This issue is fixed with https://github.com/LunarG/VulkanTools/pull/2213
