### ISSUE TITLE
vkconfig3: Cannot select between two layers with same name, same version

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#2194]
I have added a custom layer path with my dev path for gfxreconstruct and it matches the SDK version:
![image](https://github.com/user-attachments/assets/62a475db-5dd8-4eca-b4c7-6d40fbf4c9b7)

I see different paths when I hover over the versions:
![image](https://github.com/user-attachments/assets/69e83bc5-a523-4ac4-8793-c7e852fa43be)
![image](https://github.com/user-attachments/assets/bfe63504-c79b-4a94-b1e2-96446917b989)

But all three options put the "latest" dev path in vk_loader_settings.json. I can no longer enable the SDK version.

**Comment by christophe-lunarg** [comment]
This issue is fixed with: https://github.com/LunarG/VulkanTools/pull/2202
I also checked `vk_loader_settings.json`.

![manifest_version2](https://github.com/user-attachments/assets/cc211237-597c-46f6-90b6-4c0dd782096c)
