### ISSUE TITLE
vkconfig3: Application Launcher arguments get reused

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#2195]
Steps to reproduce
1) Launch an applications with arguments
2) Launch an different application with no arguments

The 2nd application will be launched with the arguments from the 1st

**Comment by christophe-lunarg** [comment]
Hi Mike,

I didn't manage to reproduce this issue. Could you send me an animated gif so that I could reproduce it?

Here is what I did:
![arguments](https://github.com/user-attachments/assets/8394e021-2f63-4c79-9277-44b68f9dff2f)

**Comment by mikes-lunarg** [comment]
Your gif does reproduce the problem. Notice that vulkaninfo doesn't show the normal output, but instead shows the help text because it got an unexpected argument.

Here is another example:
![arguments](https://github.com/user-attachments/assets/4d3275b3-bd1b-432a-ae36-31a0b5ce0161)

**Comment by christophe-lunarg** [comment]
Ah ok, I see!

This issue is resolved by https://github.com/LunarG/VulkanTools/pull/2205
