### ISSUE TITLE
vkconfig3: Settings VK_HOME does nothing

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#2196]
Setting a custom VK_HOME:
![image](https://github.com/user-attachments/assets/e750f1da-294a-4658-acf4-9ab0270f542d)

Application launcher still uses default value:
![image](https://github.com/user-attachments/assets/001a159d-714e-4d9b-8e7b-1f256728fec3)

So do any layer settings which use VK_HOME in a path (e.g. gfxreconstruct `capture_file`)

**Comment by christophe-lunarg** [comment]
This issue is fixed with https://github.com/LunarG/VulkanTools/pull/2202
