### ISSUE TITLE
vkconfig: Terminate button doesn't always reset

### ISSUE THREAD

**Issue by mikes-lunarg** [LunarG/VulkanTools#2197]
Fast applications like vulkaninfo can exit before the button gets updated, causing it to stay on "Terminate" even after the program is done running

![image](https://github.com/user-attachments/assets/5ce59273-78ab-4d67-b2ad-68bb83d32061)

**Comment by christophe-lunarg** [comment]
This issue should be resolved with https://github.com/LunarG/VulkanTools/pull/2202
