### ISSUE TITLE
Vkconfig3: not system tray icon

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#2198]
Selecting "Keep Vulkan Configurator running in system tray when closing the main window", I do get a message box that confirms this is what I want to do, however, there is no vkConfig in the system tray or system menu, etc. The icon is there while vkconfig is running, but it disappears as soon as I exit vkconfig-gui.

**Comment by richard-lunarg** [comment]
I'm seeing this on Windows ARM as well.

**Comment by christophe-lunarg** [comment]
This issue is resolved with https://github.com/LunarG/VulkanTools/pull/2202
