### ISSUE TITLE
vkconfig3: $VULKAN_SDK on macOS

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#2199]
Under the system diagnostic tab on macOS, near the top is this line: 

 - ${VULKAN_SDK}: /usr/local/share/vulkan

This is confusing to me, as $VULKAN_SDK (actually all environment variables) are not set for GUI applications. When it is set via 
source setup-env.sh it is actually something like:
/Users/lunarg/VulkanSDK/1.3.302.0/macOS

This could be clearer for macOS users what this is representing.

**Comment by christophe-lunarg** [comment]
The diagnostic tab only reflect on how the system is setup.

So it looks like that when you are running Vulkan Configurator here, ${VULKAN_SDK} is set to `/usr/local/share/vulkan`, not `/Users/lunarg/VulkanSDK/1.3.302.0/macOS`

Something is most likely wrong somewhere.

**Comment by christophe-lunarg** [comment]
Launching vkconfig3 from qtcreator, I am also getting:
Vulkan Configurator 3.0.0 - 20241127:
 - Build: macOS Release
 - Vulkan API version: 1.3.298
 - ${VULKAN_SDK}: /usr/local/share/vulkan
 
 From the console, I am getting:
 christophe@Christophes-Air 1.3.302.0 % echo $VULKAN_SDK
/Users/christophe/Documents/vulkan-sdk-1.2.154/macOS

Shouldn't the installer do something for this?

**Comment by richard-lunarg** [comment]
macOS, like Linux does not set a system wide $VULKAN_SDK environment variable. Even if it did, GUI apps would not "see it". Perhaps on macOS just reflect that this is the default path for the SDK components, but as you even got surprised, $VULKAN_SDK is potentially misleading and confusing.

**Comment by christophe-lunarg** [comment]
This issue should be fixed with this PR:
https://github.com/LunarG/VulkanTools/pull/2205

When `$VULKAN_SDK` is set on Linux and macOS, Vulkan Configurator should find the layers, the default executables (vkconfig, vulkaninfo) and profiles
When is `$VULKAN_SDK` unset, Vulkan Configurator should use the default executables (vkconfig, vulkaninfo) and profiles, and installed layers in system path.
