### ISSUE TITLE
vkconfig3: Validation log cache size

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#2201]
This is more of a feature request. Under the application launcher, the log cache is rather small. Sometimes if things go "really wrong", I want to scroll up to the top to see the first errors. It's often truncated. I know there's a text log, but can we make this log just a bit bigger? Maybe 2x or 3x? (Or make it user configurable?).

**Comment by christophe-lunarg** [comment]
I guess this is not causing any issue to significantly increase the log size, so I just did it in https://github.com/LunarG/VulkanTools/pull/2202 PR

**Comment by richard-lunarg** [comment]
Thanks!

**Comment by christophe-lunarg** [comment]
This updated issue is resolved with: https://github.com/LunarG/VulkanTools/pull/2211

![image](https://github.com/user-attachments/assets/633e47e9-a3c0-4dd7-b15e-70660d260c1e)
