### ISSUE TITLE
vkconfig3: No way to remove enabled executables?

### ISSUE THREAD

**Issue by ziga-lunarg** [LunarG/VulkanTools#2208]
After adding multiple paths to enabled vulkan executables, I don't see a way to remove them.

![image](https://github.com/user-attachments/assets/bb02251e-d2cd-426a-be78-91051b5d4fad)

**Comment by christophe-lunarg** [comment]
they can be removed from the launcher tab, isn't it enought?

**Comment by ziga-lunarg** [comment]
Yes that works, but unintuitive.
