### ISSUE TITLE
Unable to trace the replay of a newly created trace

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#221]
With today's master, go to build/demos

"vktrace.exe -p .\debug\cube -o cube.vktrace -w ."  Works
"vkreplay.exe -t .\cube.vktrace" Works
"vktrace.exe -p vkreplay.exe -o cube2.vktrace -w . -a "-t .\cube.vktrace""

Gets "Error creating trace header file, Are vktrace and trace layer the same version?"
then "Client couldn't find any connections"
then "Return value is INITIALIZATION_FAILED" and spew from then on

**Comment by davidlunarg** [comment]
Fixed in commit 32ab212a813693c095617349ab6c8111258b027b
