### ISSUE TITLE
vkconfig3 suggestions: Show files when searching for Layer Manifests Folder

### ISSUE THREAD

**Issue by ziga-lunarg** [LunarG/VulkanTools#2212]
When I'm trying to add a new path to a layer I am searching for a directory:

![image](https://github.com/user-attachments/assets/898bd8da-4d28-40fc-ac98-b24241b8efa3)

But when I am looking for a manifest file I am not 100% sure which is the correct folder, so it would be great if I could see the files that are here.

**Comment by christophe-lunarg** [comment]
I agree it would be better to have folders with unclickabled files but that would imply to create a custom dialog window instead of using the native UI which introduce UI insconistency and come with drawbacks (less powerfull dialog UI).

So, I am not too convinced I should implement this...

**Comment by ziga-lunarg** [comment]
Did not realize this was not a simple bool somewhere, feel free to close.

**Comment by christophe-lunarg** [comment]
> Did not realize this was not a simple bool somewhere, feel free to close.

Me neither! I needed an investigation. ^^
