### ISSUE TITLE
vkreplay freezes on DOTA2 trace replay startup

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#248]
Setup:
* Ubuntu 16.04 on SKL SkullCanyon
* Today's DOTA2 Steam version
* Today's Git version of Mesa & VulkanTools

Use-case:
* Start Steam with Vulkan env vars
* Start: "vktrace -o dota2.vktrace" in another window
* Start DOTA2 with "-vulkan" option
* Quit DOTA2
* Try to replay resulting trace file: "vkreplay -o dota2.vktrace"

Expected output:
* Trace is captured & replayed

Actual outcome:
* Tracing works fine, but replay freezes every time with 100% CPU utilization, right at startup

Same thing happened few weeks ago when I last tested this, so I guess this has been the problem at least since (see https://github.com/LunarG/VulkanTools/issues/154).

Perf reports following:
```Overhead       Samples  Command          Shared Object                  Symbol
  98,38%          2478  swapper          [kernel.kallsyms]              [k] intel_idle
   1,35%         63512  vkreplay         vkreplay                       [.] vkReplay::replay
   0,15%          6966  vkreplay         libvulkan.so.1.0.50            [.] vkGetFenceStatus
   0,10%          4667  vkreplay         libvulkan_intel.so             [.] anv_GetFenceStatus
...
```

So I guess it gets stuck at fencing.

And starting vkreplay with validation reports following:
```IMAGE(ERROR): object: 0x0 type: 0 location: 3029 msgCode: 180357110: vkCreateImageView() format VK_FORMAT_B8G8R8A8_UNORM differs from image 45 format VK_FORMAT_B8G8R8A8_SRGB.  Formats MUST be IDENTICAL unless VK_IMAGE_CREATE_MUTABLE_FORMAT BIT was set on image creation. The spec valid usage text states 'If image was not created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, format must be identical to the format used to create image' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01019)
IMAGE(ERROR): object: 0x0 type: 0 location: 3029 msgCode: 180357110: vkCreateImageView() format VK_FORMAT_B8G8R8A8_UNORM differs from image 46 format VK_FORMAT_B8G8R8A8_SRGB.  Formats MUST be IDENTICAL unless VK_IMAGE_CREATE_MUTABLE_FORMAT BIT was set on image creation. The spec valid usage text states 'If image was not created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, format must be identical to the format used to create image' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01019)
IMAGE(ERROR): object: 0x0 type: 0 location: 3029 msgCode: 180357110: vkCreateImageView() format VK_FORMAT_B8G8R8A8_UNORM differs from image 47 format VK_FORMAT_B8G8R8A8_SRGB.  Formats MUST be IDENTICAL unless VK_IMAGE_CREATE_MUTABLE_FORMAT BIT was set on image creation. The spec valid usage text states 'If image was not created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, format must be identical to the format used to create image' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01019)
DS(ERROR): object: 0x1977 type: 23 location: 2663 msgCode: 61: Descriptor set 0x1977 encountered the following validation error at vkCmdDraw() time: Descriptor in binding #0 at global descriptor index 0 is being used in draw but has not been updated.```

**Comment by davidlunarg** [comment]
I traced and replayed the most recent version of Dota2 using the latest Git version of VulkanTools on Ubuntu 16.04. The graphics card I have is an nVidia GeForce GTX 660 Ti, using nVidia driver 375.26. My driver is a little dated, I'll try a more recent one.

**Comment by davidlunarg** [comment]
Duplicate hang in vkGetFenceStatus using nVidia driver 381.22.

**Comment by eero-t** [comment]
David, I'm not seeing this issue anymore.  Should it be fixed now?

Note: if the trace file size is close to memory, or larger, replay speed gets slowed by factor of 100x and top shows the process being in D state, which I assume to mean its disk bound.

This is strange because it's same DOTA2 tutorial, just recorded a little longer, so there shouldn't be much more data that needs to be in memory at the same time, unless vktrace keeps a lot of duplicates of the in-game data.

Is there some post-processing tool that could reduce the data set by identifying and removing/mapping duplicate data?

**Comment by davidlunarg** [comment]
Every so often, a change is made to Dota2 that breaks vktrace/replay. This has happened so often I have left Dota2 issues open, as a reminder to keep testing Dota2. I'll close this issue.

Dota2 uses mapped buffers, and modified them quite often, resulting in very large trace files consisting of mostly of mapped memory data. vkreplay doesn't keep these buffers in memory for long, simply reading the memory for the trace file and writing it to the memory buffer.

I suspect the slowdown when the file size is close to the size of memory is because doing a read from the trace file causes the file system reads the whole file and put it in memory, then it is effectively played back from memory, without having to go to the disk. I'm not aware of duplicating any data in vktrace - the data is read to a buffer, and from that buffer, the data is copied to the mapped memory.

I'm not aware of a tool to identify duplicate writes to mapped memory. That would be a difficult problem to solve, but be quite useful.
