### ISSUE TITLE
vktrace/replay: VK_INCOMPLETE from vkGetPipelineCacheData

### ISSUE THREAD

**Issue by joey-lunarg** [LunarG/VulkanTools#259]
Received the following error messages when replaying traces on Dota 2 and a Unity test game:

vkreplay error: Return value VK_INCOMPLETE from API call (vkGetPipelineCacheData) does not match return value from trace file VK_SUCCESS.
vkreplay error: Failed to replay packet_id 82, with global_packet_index 1133240.

**Comment by Tony-LunarG** [comment]
See https://lunarg.atlassian.net/projects/VKTRAC/issues/VKTRAC-31?filter=allopenissues

**Comment by davidlunarg** [comment]
Fixed in commit 1cda03f8
