### ISSUE TITLE
(Chinese)Could NOT find Vulkan (missing:  Vulkan_LIBRARY)

### ISSUE THREAD

**Issue by liaowuping** [LunarG/VulkanTools#261]
sorry, i can not speak english. i will use chinese, can you help me?
我在使用 lunarg sdk 进行的默认安装后，使用 cmake find_package(Vulkan) 时出现Could NOT find Vulkan (missing:  Vulkan_LIBRARY)。
我发现在cmake的目录下有一个FindVulkan.cmake文件，其中会查找 $ENV{VULKAN_SDK}/Bin 下的静态库文件，但是 lunarg sdk 默认安装后，这个目录下并没有 *.lib 文件，*.lib文件是在$ENV{VULKAN_SDK}/Lib和$ENV{VULKAN_SDK}/Lib32中，请问我是否需要将*.lib文件手动拷贝到$ENV{VULKAN_SDK}/Bin中？还是有什么其他的办法。

**Comment by davidlunarg** [comment]
This is an SDK install issue. Please submit this issue to vulkan.lunarg.com.

这是一个SDK安装问题。请将此问题提交给vulkan.lunarg.com。
Zhè shì yīgè SDK ānzhuāng wèntí. Qǐng jiāng cǐ wèntí tíjiāo gěi vulkan.Lunarg.Com.

**Comment by liaowuping** [comment]
thanks
