### ISSUE TITLE
Vulkan Layers don't work with Smoke demo sample.

### ISSUE THREAD

**Issue by nvining-work** [LunarG/VulkanTools#262]
I'm filing this as a bug: I want to test a Vulkan layer with the sample programs in the Vulkan Tools SDK (which seems like a sensible use of sample programs). The cube demo works just fine, but the "smoke" sample formerly known as hologram doesn't. This seems to be because Smoke generates its own dispatch table by calling dlopen() and dlsym() directly, which - on my machine at least - means that it is bypassing the trampoline layer. My belief, please correct me if I am wrong, is that the trampoline layer is explicitly designed to prevent having to load a dispatch table like this in the first place. So I'm not sure why the sample is doing this or why it is necessary. Regardless, this seems to be preventing my layer, which has been tested on other fine Vulkan programs, from loading.

What is the purpose of the extra boilerplate here?

**Comment by courtney-g** [comment]
The smoke demo should be dlopen'ing the Vulkan loader and dlsym on vkGetInstanceProcAddr. It then fills in it's own dispatch table using the GetInstanceProcAddr it got from the loader. So everything still calls through the trampoline code as you'd expect.

That kind of dispatch table building is something we see in a lot of applications on OpenGL and so we wanted to model that behavior here. It also allows smoke to fail more gracefully if something isn't configured correctly, whereas an app linking directly to the loader could fail during startup with little diagnostic feedback.

Did you try running "smoke --validate"? That should run with the default validation libraries. If that doesn't work there is probably an issue with the setup and the loader is unable to find the validation layers or something like that.

**Comment by nvining-work** [comment]
Upon further analysis: if I preload my layer's .so with LD_PRELOAD and then run Hologram, the reason the library fails to hook correctly is because Hologram does not link against libvulkan. Consequently, when the trampoline tries to load my library, my library cannot find vkGetInstanceProcAddr, and will not load.

I understand that dispatch table building is what we see in OpenGL applications. The Vulkan trampoline mechanism, as I understand it, is specifically written to avoid this sort of thing, precisely because it was so bad when we did it in OpenGL. If this application is an official part of the LunarG SDK, then why are we encouraging people to use a mechanism that the trampoline layer was *specifically* designed not to make necessary? Should all Vulkan apps be building their own dispatch tables? This seems completely inconsistent with the design of the trampoline API.

I will note that my layer's .so was built using the Overlay layer sample as a starting point. So I presume my usage is correct, since it's what the LunarG sample does. I will verify that this is an issue with the Overlay sample and will report back. It's possible that a linker flag is present in Overlay and not in my layer project for whatever reason, in which case... well, we can figure that out when we get there.

With regards to the actual bug, there are three possibilities.

1. The Overlay sample, which I built my layer on top of, uses the wrong paradigm for getting its symbols, and should be dlopening() something.
2. Hologram is at fault for dlopening() libvulkan, and not linking against -lvulkan
3. The trampoline is at fault for not somehow conveying to the dlopen command that those symbols already exist, or for not handling the case where neither an app nor a layer links against libvulkan explicitly; in which case, I will go file a bug somewhere else.

My belief is that Hologram does the wrong thing here, by not linking against -lvulkan, and furthermore that this is teaching a bad usage pattern. If what Hologram is doing is exactly what Khronos says we should be doing, then I need to go file bugs against the documentation because this is not consistent with my belief on the subject.

**Comment by courtney-g** [comment]
Have you tried setting VK_LOADER_DEBUG="all"?
That will enable debug logging in the loader that will show what it's doing, where it's looking for layers, etc.
Running the validation layers on hologram works, so I don't think there is an issue there.
I'm not as confident with the overlay layer. That's not a validation layer and it's possible that it may get stale. Were you able to verify that the overlay layer worked prior to your customizations?

**Comment by stroyan** [comment]
You comments about using LD_PRELOAD and your layer library trying to find vkGetInstanceProcAddr hint at some misconceptions about low vulkan layers work.  They are very different from intercepting shim libraries that you may have used for OpenGL or other APIs.  Each layer loaded by the vulkan loader can have its functions placed in a chain of functions that are called between the application and the icd.  A vulkan layer library should not be forced in by LD_PRELOAD.

The vulkan loader finds and loads layer libraries as well as driver icd libraries.  The details of how the vulkan loader finds and initializes a layer are documented in **loader/LoaderAndLayerInterface.md** in the vulkan loader source (and in VulkanTools and VulkanSamples).  That document has many helpful details on how to create and use layers.

Starting from the overlay layer example should give you a good start.  Note that your layer should have a new manifest file much like Layer-Samples/Overlay/linux/overlay.json .  There are several ways to cause layers to be discovered and used.  VK_LAYER_PATH and VK_INSTANCE_LAYERS environment variables may be the easiest way for you to instruct the vulkan loader to find and load your layer between the application and the driver icd.

**Comment by nvining-work** [comment]
@stroyan: To be clear, I am only forcing it in via LD_PRELOAD to determine why it was failing to open with dlopen(). In normal operation, it uses the VK_LAYER_PATH and VK_INSTANCE_LAYERS environment variable and the correct .json mechanism.

**Comment by charles-lunarg** [comment]
> Hologram uses dlopen()/dlsym(), which defeats the point of having a trampoline layer

That is simply not true. Linking to `libvulkan.so` and loading it with `dlopen` will result in the same thing. I actually recommend applications create their own dispatch table as it allows for applications to avoid calling into the loader for every function call. After reading this issue this appears to be a faulty understanding of how layer loading & functions work in Vulkan.

For a detailed explanation, check out the https://github.com/KhronosGroup/Vulkan-Loader/blob/main/docs/LoaderApplicationInterface.md

I'm going to close this issue since it is very inactive and the stated issue is due to a misconception.
