### ISSUE TITLE
vktrace/vkreplay: Quake 3 Arena Vulkan fails to replay properly

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/VulkanTools#267]
Requires:
 * Windows
 * Nvidia/AMD

Step 1 - Install Quake 3 Arena from either Steam or GOG
  * NOTE: Q3 Arena free demo will not work, must be full game
Step 2 - Clone https://github.com/kennyalive/Quake-III-Arena-Kenny-Edition
Step 3 - Build quake3.sln inside the new repo (in visual-studio folder)
Step 4 - Copy the resulting binary from bin\x64\Release into your Quake 3 arena folder
  * Steam location of this folder on my machine was: "C:\Program Files (x86)\Steam\steamapps\common\Quake 3 Arena"
Step 5 - Record:

```
vktrace.exe -o q3.vktrace -w "C:\Program Files (x86)\Steam\steamapps\common\Quake 3 Arena" -p "C:\Program Files (x86)\Steam\steamapps\common\Quake 3 Arena\quake3-ke.exe" -a "+ set r_renderAPI 1 + timedemo 1 + stopsound + demo four"
```

Step 6 - Playback:

```
\vkreplay.exe -o q3.vktrace
```

Playback fails with either an error, or vktrace crashes.

Errors shown when Optimus is enabled:
vkreplay error: Failed to remap VkPhysicalDevice.
vkreplay error: Error detected in GetPhysicalDeviceProperties() due to invalid remapped VkPhysicalDevice.
vkreplay error: Failed to remap VkPhysicalDevice.
vkreplay error: Error detected in GetPhysicalDeviceProperties() due to invalid remapped VkPhysicalDevice.
vkreplay error: Failed to remap VkPhysicalDevice.
vkreplay error: Error detected in GetPhysicalDeviceProperties() due to invalid remapped VkPhysicalDevice.
vkreplay error: Failed to remap VkPhysicalDevice.
vkreplay error: Error detected in GetPhysicalDeviceProperties() due to invalid remapped VkPhysicalDevice.
vkreplay error: Failed to remap VkPhysicalDevice.
vkreplay error: Error detected in GetPhysicalDeviceProperties() due to invalid remapped VkPhysicalDevice.
vkreplay error: Failed to remap VkPhysicalDevice.
vkreplay error: Error detected in GetPhysicalDeviceProperties() due to invalid remapped VkPhysicalDevice.
vkreplay error: Failed to remap VkPhysicalDevice.
vkreplay error: Skipping vkGetPhysicalDeviceSurfaceFormatsKHR() due to invalid remapped VkPhysicalDevice.
vkreplay error: Return value VK_ERROR_VALIDATION_FAILED_EXT from API call (vkGetPhysicalDeviceSurfaceFormatsKHR) does not match return value from trace file VK_SUCCESS.

**Comment by davidlunarg** [comment]
I created a trace of Quake 3 Arena on a GeForce GTX 660 Ti using nVidia driver 382.53 and successfully replayed it. This was using Vulkan SDK 1.0.45.0. I updated the nVidia driver to 384.72 and successfully replayed the trace. I created a new trace file using the newer driver and successfully replayed it.

What graphics hardware and driver version did you use?
