### ISSUE TITLE
vktrace: segfault when tracing application without arguments

### ISSUE THREAD

**Issue by ChristophHaag** [LunarG/VulkanTools#283]
This call to strtok() segfaults when pInfo->processArgs is null.

https://github.com/LunarG/VulkanTools/blob/73b2b843eedb880934a1f57cda3e00dbc157bef5/vktrace/vktrace_common/vktrace_process.c#L81

I had tried vktrace recently, I believe it was 1.0.51 too, and did not have this issue. But when I used it today, it did segfault. Weird.

Workaround for tracing an app with no arguments: `vktrace <...> -a ""`

**Comment by davidlunarg** [comment]
I can't duplicate this issue. What platform are you running on?

I have probably created hundreds of traces in which program arguments are not specified and have never seen the problem.

**Comment by ChristophHaag** [comment]
Archlinux, glibc 2.26, gcc 7.2.0

Looks like this:
https://gist.github.com/ChristophHaag/5f69cc23b8854b48140f053bfd6dc43d

and it works if I add `-a ""`

**Comment by davidlunarg** [comment]
I don't have an archlinux system readily available. Looking at the strtok() man page, it looks like it does not define behavior if the first arg is NULL, so that might be why you are now seeing the segfault.

Could you try changing Line 81 to:
   args[idx] = pInfo->processArgs?strtok(pInfo->processArgs, delim):NULL;

**Comment by ChristophHaag** [comment]
Yes, that works.

**Comment by ChristophHaag** [comment]
My guess is that glibc 2.26 changed the behavior.

    [2017-08-18 14:30] [ALPM] upgraded glibc (2.25-7 -> 2.26-1)

that was a week ago.

**Comment by davidlunarg** [comment]
Fixed in commit 97ac69b5be8f504e447b5d55f1ef8dd17c0daf03
