### ISSUE TITLE
VIA: add support for new ICD registry locations

### ISSUE THREAD

**Issue by scyganINTEL** [LunarG/VulkanTools#289]
Following was added in 1.0.57 release. It seems this is not supported by VIA, yet:

> Additionaly the loader will scan through registry keys specific to Display Adapters and all SoftwareComponents assocatied with these adapters for the locations of JSON manifest files. These keys are reflecting HKR device hive created during driver installation and contain configuration for base settings, including OpenGL/D3D ICD location.
> 
> The Device Adapter and SoftwareComponent key paths should be obtained via PnP Configuration Manager API. In each of this path, a "VulkanDriverName" (and "VulkanDriverNameWow" for 32-bit Windows on Windows compatibility) key can be present, what should look like:
> 
>    HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Class\{Adapter GUID}\000X\VulkanDriverName
>    HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Class\{Adapter GUID}\000X\VulkanDriverNameWow
>    
>    HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Class\{SoftwareComponent GUID}\000X\VulkanDriverName
>    HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Class\{SoftwareComponent GUID}\000X\VulkanDriverNameWow
> If any of these keys exsist and is of type REG_SZ, the loader will open the JSON manifest file specified by the key valye. Each value must be a full absolute path to a JSON manifest file.

**Comment by MarkY-LunarG** [comment]
Thanks Salwik, I'm on it.

**Comment by MarkY-LunarG** [comment]
Can you try the VIA in the "via_update" branch?  MS doesn't seem to like the debug version and crashes before it even starts.  But the release version works perfectly fine.  It should find your new driver registry locations.

**Comment by MarkY-LunarG** [comment]
Changes committed.  Please file a new issue if these don't satisfy the requirements.
