### ISSUE TITLE
Invalid DisplayKHR Object

### ISSUE THREAD

**Issue by kristan2016** [LunarG/VulkanTools#292]
When I enabled the layer named "VK_LAYER_LUNARG_standard_validation", the ObjectTracker reported  the error information as below:
```
* ERROR: [ObjectTracker] Code 696279041 : Invalid DisplayKHR Object 0x214b070. The spec valid usage text states 'display must be a valid VkDisplayKHR handle' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkGetDisplayModePropertiesKHR-display-parameter)
```
and then the application crashed.
The application executed successfully without the layer "VK_LAYER_LUNARG_standard_validation"

**Comment by davidlunarg** [comment]
This is an issue with with Vulkan Validation Layers.

Please resubmit to https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers. Closing this issue.
