### ISSUE TITLE
Corrupted progress indicator gfx in Talos Principle under tracing

### ISSUE THREAD

**Issue by eero-t** [LunarG/VulkanTools#294]
This is continuation from #128.

When tracing Talos principle:
* The progress indicator shown in the bottom left corner when game starts (and in middle of screen in some other places), is rendered completely wrong
* Similar looking & sized small broken gfx is left in middle of the screen e.g. when extras->benchmark is started

Vulkan API validation shows a lot of warnings (same as DOTA2), I don't know whether any of them are related.

In case it matters, Talos is started from Steam, and configured to use with Vulkan backend with medium GPU speed (other performance settings are high).

**Comment by davidlunarg** [comment]
I don't see a progress indicator in the bottom left corner when game starts. Can it be turned on and off and I have somehow set it to off?

**Comment by eero-t** [comment]
There's no option for toggling that in Talos GUI. I have latest Talos version that Steam provides, so I think it should be enabled by default.

Note that the "Loading..." text with the progress indicator (at bottom left) at the Talos game start shows for a very short time when one is NOT doing tracing, it's right in the beginning before the CroTeam logo is shown.

Don't you see progress indicator even when you start/continue a game or start the benchmark?  Right in middle of screen, below the "Loading..." & "...Please wait..." texts?

Or when you stop the game, in same place, below the "Stopping..." & " ...Please wait..." texts?

PS. In Talos.ini there seem to be two options for progress indicator:
sha_bNoProgressBar = 0; _(version="3")
tex_bNoProgressBar = 0;

But enabling those didn't hide the progress indicator.

**Comment by davidlunarg** [comment]
I just created a trace of Talos Principle on Ubuntu 16.04 using the latest source from master on VulkanTools (last commit is f169277837d5de152a1246ef637c166d975e7a63). The progress indicators were displayed during trace and look OK during replay. I used an nVidia GTX 660Ti graphics card with driver version 381.22.

I have uploaded a copy of the trace file to share.lunarg.com, and shared it with eero...@intel.com (You will have to create an account on share.lunarg.com to access it.)

Please let me know it it works for you. You may need to play it back on nVidia in order for it to work.

**Comment by eero-t** [comment]
I don't have Nvidia to try it with.

When using Mesa git with VulkanTools git on Intel SkyLake, I get:
```
Enabling validation layer(s): VK_LAYER_LUNARG_standard_validation
Running:  ../vktrace/vkreplay -o TalosPrinciple.vktrace
DL(ERROR): object: 0x1c43e00 type: 2 location: 1939 msgCode: 786434538: vkGetPhysicalDeviceSurfaceSupportKHR: queueFamilyIndex (= 1) is not less than any previously obtained pQueueFamilyPropertyCount from vkGetPhysicalDeviceQueueFamilyProperties (i.e. is not less than 1). The spec valid usage text states 'queueFamilyIndex must be less than pQueueFamilyPropertyCount returned by vkGetPhysicalDeviceQueueFamilyProperties for the given physicalDevice' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkGetPhysicalDeviceSurfaceSupportKHR-queueFamilyIndex-01269)
Segmentation fault (core dumped)
```

But that doesn't really matter, as with latest Mesa & VulkanTools git the issue has disappeared, the loading indicator looks fine now! :-)

I noticed you had commited some fixes from Justus Wang in the meanwhile, maybe those corrected it.  

Anyway, closing this as fixed.

PS.  ezBench tool which can bisect performance and rendering changes for Linux 3D stack  has now support also for Vulkan render validation with vkreplay screenshots:
https://cgit.freedesktop.org/ezbench
