### ISSUE TITLE
DevSim should emit warning when exceeding device limits

### ISSUE THREAD

**Issue by Jasper-Bekkers** [LunarG/VulkanTools#296]
From the README.md:

"Also, if the configuration attempts to add capabilities beyond what the actual device is natively capable of providing, then the results are undefined."

Please output a (non fatal) warning to prevent accidental mistakes.

**Comment by mikew-lunarg** [comment]
Thanks for the suggestion.

This is checking against limits when configuring DevSim.  Related is [LVL 2063](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2063) for validating against a simulated device.

**Comment by mikew-lunarg** [comment]
Please see pull request #308

**Comment by mikew-lunarg** [comment]
This change has been pushed to master.
