### ISSUE TITLE
Missing Dependencies in BUILDVT.md

### ISSUE THREAD

**Issue by yousry** [LunarG/VulkanTools#30]
"wget" is a necessary dependency.
"autotools" is a necessary dependency.

Prüfe Konnektivität ... Fertig.
./update_external_sources.sh: Zeile 67: wget: Kommando nicht gefunden.

**Comment by yousry** [comment]
Instead of Ubuntu/Debian repositories a list of necessary tools/packages would be desirable.

**Comment by karl-lunarg** [comment]
I've added those two deps.  Much of the documentation is based on the assumption that Ubuntu/Debian environments are in use.  It should be straightforward for users of other environments to map what is documented into the corresponding form for their OS.
