### ISSUE TITLE
vkreplay doesn't support file more than 4GB on windows

### ISSUE THREAD

**Issue by linqunzju** [LunarG/VulkanTools#321]
on windows, ftell and fseek only support 4GB, we should use _ftelli64 and _fseeki64 on windows, but it is missed in vkreplay, and it causes vkreplay exit in initial time, could you have a look? Thanks!

another minor issue is vkreplay doesn't stable on window
-  some time it only can work correctly in VC IDE, it seems some variable are not initialized.
-   some time it trig null pointer access in driver, it seems some functions are called incorrectly.
but I don't know the root causes.

Qun

**Comment by davidlunarg** [comment]
Yes, the 64 bit versions of ftell and fseek should be used on Windows. The calls to those functions will need to be different on Windows and Linux, so it is not a simple textual substitution to fix this issue. I can certainly accept a pull request to fix this. :-)

**Comment by davidlunarg** [comment]
Created pull request https://github.com/LunarG/VulkanTools/pull/329 to fix this issue.

**Comment by davidlunarg** [comment]
vktrace/replay now works with files > 4GB in both 64 and 32 bit mode. Issue had been fixed. Closing.
