### ISSUE TITLE
The trace file generated on 32bit system cannot be read by 64bit traceviewer

### ISSUE THREAD

**Issue by jyangsh** [LunarG/VulkanTools#33]
The size of packet_vkApiVersion is different from 32bit system to 64bit system so the data packet generated on 32bit system should not be compatible with 64bit traceviewer.

It may be a problem, if the 32bit trace file cannot be replayed on 64 bit system，vice versa.

**Comment by davidlunarg** [comment]
We have decided that 32 <-> 64 bit interoperability will not be supported. A trace captured as 32 bit needs to be viewed/replayed using a 32 bit viewer/replayer. A traced captured as 64 bit needs to be viewed/replayed back using a 64 bit viewer/replayer.

That being said, we could add code to the viewer/replayer to check to see if the trace file is the type it can handle, and it is is not, automatically invoke the correct viewer/replayer.
