### ISSUE TITLE
screenshot: Validation error when linear images are not supported

### ISSUE THREAD

**Issue by polarina** [LunarG/VulkanTools#354]
The `VK_LAYER_LUNARG_screenshots` layer [creates linear images](https://github.com/LunarG/VulkanTools/blob/3483aa91155283f985e6e136b8c6271a0d267f9e/layersvt/screenshot.cpp#L621). Implementations are not required to support _any_ linear images.

The layer does not check for support of linear images, thus triggers a validation error:

> IMAGE(ERROR): object: 0x0 type: 0 location: 656 msgCode: 165676962: vkCreateImage format parameter (VK_FORMAT_R8G8B8A8_UNORM) is an unsupported format. The spec valid usage text states 'If tiling is VK_IMAGE_TILING_LINEAR, format must be a format that has at least one supported feature bit present in the value of VkFormatProperties::linearTilingFeatures returned by vkGetPhysicalDeviceFormatProperties with the same value of format' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-tiling-00977)

Ideally, the layer should have a fallback path through `vkCmdCopyImageToBuffer` when linear images are not supported. At least, it should detect the lack of support and bail.

**Comment by davidlunarg** [comment]
I don't see the validation error  when I enable screenshots and the validation layer.

From the Description section of the VkImageCreateInfo spec page:

>Creation of images with tiling VK_IMAGE_TILING_LINEAR may not be supported unless other parameters meet all of the constraints:
> - imageType is VK_IMAGE_TYPE_2D
> - format is not a depth/stencil format
> - mipLevels is 1
> - arrayLayers is 1
> - samples is VK_SAMPLE_COUNT_1_BIT
> - usage only includes VK_IMAGE_USAGE_TRANSFER_SRC_BIT and/or VK_IMAGE_USAGE_TRANSFER_DST_BIT

I think the screenshot layer is meeting all the constraints, so VK_IMAGE_TILING_LINEAR should be supported. Or maybe I missed something?

**Comment by davidlunarg** [comment]
I believe the screenshot and validation layers are behaving correctly, so I will close this issue. If I am incorrect, the issue can be reopened.
