### ISSUE TITLE
vkreplay: trace file with VK_PRESENT_MODE_MAILBOX_KHR present mode is not replayed correctly

### ISSUE THREAD

**Issue by justuswang** [LunarG/VulkanTools#365]
Does vkreplay support replaying a trace file with VK_PRESENT_MODE_MAILBOX_KHR present mode?

Following is the current observation when replaying a trace file with mailbox present mode and 4 swap-chain images.

1. vkAcquireNextImageKHR returns image index 2 in Trace, but it returns image index 3 in Replay.
2. Trace renders to image index 2 with address#1, but Replay renders to remapped image (remapped from address#1) which is not the expected image index 3.
3. Trace presents image index 2 (because vkAcquireNextImageKHR returned 2 during trace), but Replay presents image index 3 (because vkAcquireNextImageKHR returned 3 during replay).

Seems it renders to a wrong image in step 2 during replay.

**Comment by davidlunarg** [comment]
Yes, this is a bug. Replay needs to be modified so rendering is done to the correct image.

**Comment by justuswang** [comment]
Pull Request created #368.
