### ISSUE TITLE
Fix warnings on VulkanTools build

### ISSUE THREAD

**Issue by mark-lunarg** [LunarG/VulkanTools#369]
There are about 25 warnings on the Windows build of VulkanTools Master and at least a couple in the Linux build, apparently in vktrace.  These should be fixed.

**Comment by davidlunarg** [comment]
Fix in commits 7e22dd6274085207390b93996f6044723b6514a7 and 3d9368ef16240cb0228dc7f1df22be0dbff25cdc. Closing.
