### ISSUE TITLE
Error when trying to use image aspect plane flags on multiplane images in vkGetImageSubresourceLayout

### ISSUE THREAD

**Issue by atomnuker** [LunarG/VulkanTools#380]
Creating a non-disjoint multiplane image and attempting to get the VkSubresourceLayout of each individual plane by using vkGetImageSubresourceLayout (by setting the aspectMask flag to VK_IMAGE_ASPECT_PLANE_<number>_BIT_KHR) results in the layer reporting an error:

> vkGetImageSubresourceLayout(): For color formats, VkImageSubresource.aspectMask must be VK_IMAGE_ASPECT_COLOR. The spec valid usage text states 'aspectMask must be a valid combination of VkImageAspectFlagBits vaues'

However the [https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/html/vkspec.html#vkGetImageSubresourceLayout](spec) says that "If the format of image is a multi-planar format with three planes, the aspectMask member of pSubresource must be VK_IMAGE_ASPECT_PLANE_0_BIT_KHR, VK_IMAGE_ASPECT_PLANE_1_BIT_KHR or VK_IMAGE_ASPECT_PLANE_2_BIT_KHR"

It also says it can't be a combination but may only have 1 bit flagged.

The location in the code of the error is https://github.com/LunarG/VulkanTools/blob/b9145cd69ddb30b93878e513d8821604282abd0e/layers/buffer_validation.cpp#L4152

**Comment by davidlunarg** [comment]
This issue is in files that are trunk merged into VulkanTools from https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers. Please resubmit this issue to that project.
