### ISSUE TITLE
Trying to build Vulkan ICD driver requires Khronos SVN login..

### ISSUE THREAD

**Issue by oscarbg** [LunarG/VulkanTools#4]
In update_external_sources.sh this step:
 svn checkout -r $LUNARGLASS_REVISION_R32 --force https://cvs.khronos.org/svn/repos/SPIRV/trunk/LunarGLASS/ .
requires passworkd and login which I don't have..
being all opensourced by now doesn't make sense,right?
can update script to fetch from public repos?
thanks..

**Comment by karl-lunarg** [comment]
Yes, we became aware of this issue soon after the SDK shipped.  We're in the process now of updating a public repo with the contents of the private, and then updating the script to point to the updated public repo.  We'll update this issue when this work is done.

**Comment by karl-lunarg** [comment]
We're in the process of updating the public LunarGLASS repo with the correct code. The portions of the script that use svn to fetch and build LunarGLASS are going to be removed from the script in the LoaderAndValidationLayers repo and moved to a new script in the VulkanTools repo, which is really the repo that needs LunarGLASS. This new script will fetch and build from the updated public LunarGLASS repo and so will not need a password.

**Comment by greg-lunarg** [comment]
We have modified the process to create LunarGLASS for the 1.0.3 SDK. We have created an update_external_sources.sh in VulkanTools which should now be used to create LunarGLASS. The update_external_sources.sh in LoaderAndValidationLayers no longer builds LunarGLASS but should be run first to create the required glslang. We have also changed the LunarGLASS build process so that it is not dependent on Khronos access.

**Comment by oscarbg** [comment]
Ok.. thanks will try and report possible issues..
only a question: does LunarG driver work with Skylake GPU as intel Mesa
Anvil driver?
if not are plans to upgrade to support it?
also would be nice if someone can upload some report of LunarG driver to
http://vulkan.gpuinfo.org using http://vulkan.gpuinfo.org/download.php to
compare to Intel Mesa Anvil (
http://vulkan.gpuinfo.org/displayreport.php?id=53) in terms of Vulkan caps
support!
finally if someone could setup some ppa package or a deb package for
testing in Ubuntu will simplify my testing..
thanks..

2016-02-20 0:31 GMT+01:00 greg-lunarg <notifications@github.com>:

**Comment by karl-lunarg** [comment]
The LunarG driver (aka "ilo" driver in the VulkanTools repo) does not work with Skylake.

The LunarG "ilo" driver is being deprecated, for the most part, in favor of other drivers that Intel is releasing.  So, it won't be a good idea to place an entry for it on vulkan.gpuinfo.org.

You should be able to find some ppa packages that people are making or about to make by doing a search.  But you should be able to accomplish nearly the same thing with the Vulkan SDK by first getting and installing a Vulkan driver from your graphics card vendor and then installing the Vulkan SDK.

**Comment by oscarbg** [comment]
Ok. thanks..
only wanted to know if "ilo" had more optional features enabled vs Anvil
as seems Anvil driver features are "limited" currently to what's shipping
in Nvidia driver which basically enables almost every optional feature..

2016-02-22 19:11 GMT+01:00 Karl Schultz <notifications@github.com>:
