### ISSUE TITLE
Use vkCmdBlitImage in Screenshot layer to convert between image formats

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#40]
Right  now, screenshot only supports 2 image formats, (neither of which are the default mesa image format) and it would be nice to use a blit to copy from the source image, converting to one of the two formats that lend themselves to easy ppm file generation.  If the incoming format has VK_FORMAT_FEATURE_BLIT_SRC_BIT in its features for whatever tiling its using, writePPM could use vkCmdBlitImage instead of vkCopyImage to both copy and convert the format.

**Comment by karl-lunarg** [comment]
I basically overhauled writePPM() to support any incoming swapchain image format that is compatible with either RGBA or RGB.  This implies support for any 24-bit or 32-bit compatible swapchain image formats.  The selection of RGBA and RGB allows for efficient pixel writes to the PPM file.

In addition, the new code handles the following three conditions:
1) Input format is already RGB or RGBA : Just do a Copy to put the image in CPU-readable memory and potentially untile it.
2) Device supports BLIT to an untiled destination:  Just do a BLIT for format conversion and to put the image in CPU-readable memory and potentially untile it.
3) Device does NOT support BLIT to an untiled destination:  Do a BLIT for format conversion and then do a COPY to put the image in CPU-readable memory and untile it.

In addition, the function now exits more gracefully if there is an intermediate failure, and allocated resources are cleaned up better.
