### ISSUE TITLE
vkreplay 1.0.68 thinks trace file is version 1.0.65.1

### ISSUE THREAD

**Issue by daveh-lunarg** [LunarG/VulkanTools#400]
Trace file created by 1.0.68 SDK appears to vkreplay to be from 1.0.65.1. I haven't reproduced locally, but feedback harvested from an LVL issue (#2408): 

> I tried opening it with vktraceviewer, but it thought it was made with 1.0.65.1 for some reason (even though the engine loaded the C:\VulkanSDK\1.0.68.0\Source\lib\VkLayer_vktrace_layer.dll file and I ran c:\VulkanSDK\1.0.68.0\bin\vktrace.exe)

**Comment by davidlunarg** [comment]
I installed SDK 1.0.68.0 and created a trace file. The first 16 bits in the trace file are the trace file version, which was 6, which is the most current version when SDK 1.0.68.0 was released.

I opened the trace file with vktraceviewer. The very first entry shows vkApiVersion as 0x40044. If this number is interpreted as the VK_MAKE_VERSION would have constructed it, that number refers to 1.0.68.

I am unable to reproduce this issue. Please reopen if this is still a problem.
