### ISSUE TITLE
Cannot trace and replay Hologram / Smoketest on Linux

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#41]
On 16.04 Mesa a0d9279e3b31ce5e5bb2baf857134bd5f48dbf65 it crashes in the driver on a call to GetPhysicalDeviceXcbPresentationSupportKHRn during replay (a cube trace replays fine using the same call) and on 15.10 Nvidia  vktrace hangs.

**Comment by plohrmann** [comment]
A similar error message appears with trace & replay of Smoketest on Windows.
