### ISSUE TITLE
miss alignment for some arm cpu vfp load instructions

### ISSUE THREAD

**Issue by jyangsh** [LunarG/VulkanTools#42]
Some arm vfp load instructions, e.g. vldr, requires the address of the source to align to 4 bytes.

But sometimes, the address decomposed from the packet is not 4 bytes alignment, e.g., the 4 float type members in the VkPipelineRasterizationStateCreateInfo structure, that is causing the vldr instruction fail.

**Comment by karl-lunarg** [comment]
Is this for vktrace/vkreplay?

**Comment by jyangsh** [comment]
Yes, the issue is for vktrace and vkreplay. Sorry for missing this info.:)

**Comment by davidlunarg** [comment]
I have a proposed fix, which I have verified using assert(). Could you try the david_arm_align branch in VulkanTools and let me know if this addresses the problem?

**Comment by ZLixing** [comment]
Hi,  I have tried the branch on arm platform but failed with the assertion (assert((size&0x3) == 0)).

**Comment by davidlunarg** [comment]
@ZLixing : Thanks for trying it. I made a couple of more changes since I sent you the proposed fix, and it is now on master. Could you try it? And if it fails on an assert, could you send me a stack trace?

**Comment by ZLixing** [comment]
@davidlunarg I merged the newest master to my project and no problem happens, thanks for help

**Comment by davidlunarg** [comment]
Glad it works for you. Thanks for testing it, I don't have an ARM system readily available.
