### ISSUE TITLE
Using Vulkan Layer Framework as part of a CMake project

### ISSUE THREAD

**Issue by Themaister** [LunarG/VulkanTools#436]
I'm interested in using VLF for a new project I'm working on, but I'm not getting how this is supposed to work in practice.

The build instructions seem to suggest that you need to use the entire VulkanTools repo and integrate your own stuff into the repo and use the provided build system.

I also cannot find where the layer_factor class is actually defined.

I'm expecting something like this in my repo:
```
git submodule add <> git://github.com/LunarG/VulkanTools

# In CMakeLists.txt
add_subdirectory(vulkan-tools)
add_factory_layer(my-custom-capture-layer "VK_LAYER_my_awesome_layer" custom_capture.cpp custom_capture.hpp)
```

`custom_capture.hpp` can include `layer_factory.h`, and I do something like:
```
#include "layer_factory.h"
class CustomCapture : public layer_factory
{
    // Override virtual calls as needed.
};
```
This should then build a folder with appropriate JSON (or no JSON for Android) and so/dll. The README suggests the layer name will always include "LUNARG", which won't be right for a non-LunarG project.

Also, do I need to deal with free-threading, or is the layer factor doing something using global locks and hashmaps on every entry point?

Is every single entry point captured and dispatched, or just the ones the custom capture class actually declares?

**Comment by mark-lunarg** [comment]
@Themaister, I have some quick answers but will need some time to incorporate your cmake workflow suggestions.  

Currently, if you work from the VulkanTools repo, the workflow is as you described.  Another option is to develop in the SDK, which has a slightly different workflow in that it's using a Visual Studio template, which *may* make things easier to customize.  

The layer class is defined in a couple of code-generated files (layer_factory.cpp and layer_factory.h) that end up in the build\layer_factory directory.

The VulkanTools (and Vulkan-LoaderAndValidationLayers, for that matter) repo will be undergoing some reorganization in the near future, and we're hoping those changes will ease some of the confusion.  In any case, there is not a current option for replacing the 'LUNARG' in the names and this would need to be done in a post-build step, or by modifying the templates themselves.

As for thread safety, right now the create/destroy device/instance calls are protected, but none of the other calls are -- if you need a lock it should be supplied in your interceptor.  We may need to revisit this situation -- would you have recommendations?

Every entry point is captured.  We tested both implementations (all vs hooked) and with the available workloads the difference was negligible.  This can also be revisited if it becomes an issue.

**Comment by Themaister** [comment]
Would it be possible to include the generated layer factor in the repo and update it when the generator script is updated? It can be a hazard to require a custom build step to generate the layer, especially if it is the same every time.

So, typically layers will need to map various Vk objects to their respective types. E.g.
VkInstance <-> MyInstance*
VkDevice <-> MyDevice*
VkBuffer <-> MyBuffer*

this translation is done through global locks and hashmaps in most layers, does VLF not facilitate this? That might be good to add, because 99% of layers need to do these things.

Another question I'd like clarified: To what extent does VLF reduce boilerplate beyond hooking entry points and forwarding calls to ICD?

One very tedious, but more optimal alternative to lock + hashmap is to return reinterpret_cast<VkType>(my_custom_object) to the API user, and translate to VK types when calling down further the layer chain. That requires performing translation on every single entry point, and I don't think anyone has actually gone to this length yet, but that would avoid a lot of the lock + hashmap overhead that current layers face. That might be something VLF could automate for us if possible.

**Comment by Themaister** [comment]
Based on discussion yesterday regarding "uber-issues", is it worth splitting up this issue into multiple issues?

**Comment by karl-lunarg** [comment]
Yes.  It would be best if you did that, rather than one of us so that the ownership is clear and so you get notified as things progress.

**Comment by Themaister** [comment]
I've split this into 3 major issues: #453, #454, #455.
