### ISSUE TITLE
vulkaninfo output is very hard to read

### ISSUE THREAD

**Issue by tweenk** [LunarG/VulkanTools#44]
Vulkaninfo makes really poor choices about what is displayed as hex values and what is displayed as decimal values. For instance, the Vulkan API verson is reported as a decimal value, even though it's only readable in hex, while device limits are reported as hex, even though decimal would be much more readable.

Furthermore, memory type flags are reported as decimal values rather than a list of flags as with image formats.

**Comment by renelindsay** [comment]
Hi Tweenk,

Thank you for your suggestions, regarding the vulkaninfo tool.
I have checked in some updates to "/Vulkan-LoaderAndValidationLayers/demos/vulkaninfo.c", which will hopefully improve its readability.  Please compare the output in the following two text files, and let me know if this is not what you intended.

[vulkaninfo_after.txt](https://github.com/LunarG/VulkanTools/files/278308/vulkaninfo_after.txt)
[vulkaninfo_before.txt](https://github.com/LunarG/VulkanTools/files/278307/vulkaninfo_before.txt)

**Comment by tweenk** [comment]
This looks a lot better. But things such as minTexelOffset in VkPhysicalDeviceProperties are still unreadable - it's displayed as an unsigned hex value instead of a signed integer.

**Comment by renelindsay** [comment]
Converted the following values from hex to int:
minTexelOffset
maxTexelOffset
minTexelGatherOffset
maxTexelGatherOffset
minInterpolationOffset
maxInterpolationOffset
viewportBoundsRange[0]
tviewportBoundsRange[1]
