### ISSUE TITLE
vkreplay: Is it possible for vkreplay to automatically reorient on Android?

### ISSUE THREAD

**Issue by justuswang** [LunarG/VulkanTools#446]
A trace file traced from Android phone in landscape mode is not able to be replayed in landscape mode automatically on the same phone using vkreplay.apk.

Is it possible to automatically switch to landscape mode when replaying on Android and the trace's width is greater than height?

**Comment by dustin-lunarg** [comment]
We may be able to do this by invoking Activity.setRequestedOrientation() through JNI after detecting that the width is greater than the height.  I should be able to look at this, but may not be able to do so immediately.

**Comment by justuswang** [comment]
I have created a PR https://github.com/LunarG/VulkanTools/pull/477 to do the automatically orientation.  And it works for me when I was testing on an Android phone.  Please let me know if my PR has any side effect?

**Comment by justuswang** [comment]
@dustin-lunarg , your change looks great!  I will close my PR.

**Comment by dustin-lunarg** [comment]
This should be resolved by #478.
