### ISSUE TITLE
Vulkan Layer Framework is difficult to use standalone

### ISSUE THREAD

**Issue by Themaister** [LunarG/VulkanTools#453]
I'm interested in using VLF for a new project I'm working on, but I'm not getting how this is supposed to work in practice.

The build instructions seem to suggest that you need to use the entire VulkanTools repo and integrate your own stuff into the repo and use the provided build system.

I also cannot find where the layer_factor class is actually defined.

I'm expecting something like this in my repo:
```
git submodule add <> git://github.com/LunarG/VulkanTools

# In CMakeLists.txt
add_subdirectory(vulkan-tools)
add_factory_layer(my-custom-capture-layer "VK_LAYER_my_awesome_layer" custom_capture.cpp custom_capture.hpp)
```

**Comment by KarenGhavam-lunarG** [comment]
The layer factory has been archived [here](https://github.com/LunarG/Vulkan-Layer-Factory). There are no plans to maintain or enhance the layer factory moving forward.
