### ISSUE TITLE
Vulkan Layer Framework is missing boilerplate reduction features

### ISSUE THREAD

**Issue by Themaister** [LunarG/VulkanTools#454]
Typically layers will need to map various Vk objects to their respective types. E.g.
VkInstance <-> MyInstance*
VkDevice <-> MyDevice*
VkBuffer <-> MyBuffer*

this translation is done through global locks and hashmaps in most layers, does VLF not facilitate this? That might be good to add, because 99% of layers need to do these things.

A better approach (used by RenderDoc), is to wrap the objects which are passed up to the application. That removes most need for lock + hashmap, which can get really slow if you need to hook at the draw-call level. The downside is that you need to translate every entry point, but since this can be done one, and hopefully auto-generated, this seems like a great opportunity for VLF.

Just random idea on how that'd work, the factory could do something like:

```
template <typename T>
class ObjectBase
{
public:
    T get_vulkan_object() { return vulkan_object; }
private:
    T vulkan_object;
};
```
and the custom layer classes can inherit from `ObjectBase<VkCommandBuffer>` or similar and create objects of that type, so the factory can translate user types to Vulkan objects.

**Comment by KarenGhavam-lunarG** [comment]
The layer factory has been archived [here](https://github.com/LunarG/Vulkan-Layer-Factory). There are no plans to maintain or enhance the layer factory moving forward.
