### ISSUE TITLE
Vulkan Layer Framework should not depend on separate build steps

### ISSUE THREAD

**Issue by Themaister** [LunarG/VulkanTools#455]
Would it be possible to include the generated layer factory in the repo and update it when the generator script is updated? It can be a hazard to require a custom build step to generate the layer, especially if it is the same every time, and especially if a project does not use CMake and just wants to build against the factory as a library.

**Comment by KarenGhavam-lunarG** [comment]
The layer factory has been archived [here](https://github.com/LunarG/Vulkan-Layer-Factory). There are no plans to maintain or enhance the layer factory moving forward.
