### ISSUE TITLE
vkreplay: cannot replay traces taken on a different window system

### ISSUE THREAD

**Issue by erik-kz** [LunarG/VulkanTools#463]
It seems like it's intended to be possible to replay a trace taken on one window system on a different system. For example, the function manually_replay_vkCreateWin32SurfaceKHR, if built for Linux, will call vkCreateXcbSurface.

However, because the automatically generated vkreplay_vk_replay_gen.cpp places "#ifdef VK_USE_PLATFORM_*" guards around all window system specific code, actually replaying calls to such functions on another platform results in an "Unrecognized packed_id" error. So the aforementioned translation logic will never actually have a chance to run.

If you manually remove these guards after running cmake but before compiling, re-using traces across window systems appears to work fairly reliably, so I think it would be a useful feature to have. Modifying vktrace_file_generator.py to do this properly seems simple enough, however they would also need to be removed from the dispatch table definition currently in vk_layer_dispatch_table.h (also auto-generated) but which is part of the LoaderAndValidationLayers submodule complicating things a bit. Or else vkreplay would need a separate cross-platform dispatch table, maybe?

**Comment by davidlunarg** [comment]
At one time, this used to work. It looks like changes to the generation of vkreplay_vk_replay_gen.cpp broke the capability.

**Comment by erik-kz** [comment]
Looks like commit b896872dc65356805cf8900e70867b2581ec2bc8 got this working again.
Thanks guys! Closing.
