### ISSUE TITLE
[Layer Factory] VkResult accessible from PostCall functions

### ISSUE THREAD

**Issue by chaoticbob** [LunarG/VulkanTools#472]
Hi,

For functions that return a VkResult, how can one access the returned value from within the PostCall? I've been adding the ```VkResult callResult``` as the last parameter and updating the calling function to pass in the result. Was wondering if there is a blessed way of doing this? 

Thanks

**Comment by mark-lunarg** [comment]
@chaoticbob, thanks for the feedback.  We have a few options and this may be the best.  Another would be to save the return value and have a helper function callable by the postcall function to get the retcode, or just an overload of the post-call function that would have the extra parameter.  Either way, we'll add this Real Soon Now.
