### ISSUE TITLE
vktrace crash

### ISSUE THREAD

**Issue by karl-lunarg** [LunarG/VulkanTools#48]
From Dan Ginsburg:
> I’m trying to use vktrace in Vulkan SDK 1.0.13 on Win7 to capture a tough to reproduce flickering bug on NVIDIA GTX 760.  Unfortunately, when I load into the map it seems to get stuck and eventually crash during recording.  If I disable scaleform I can get it to record, so it seems like maybe something scaleform does that is not working in vktrace?

**Comment by jon-lunarg** [comment]
Fixed several bugs in vktrace related to mapping memory at non-zero offset and also vkGetPipelineCacheData.  Now tracing of Dota+scaleform_vulkan no longer crashes but the replay isn't yet correct (mostly just a black window). Leave this bug open to track this replay issue.

**Comment by jon-lunarg** [comment]
Replay issue appears to be a regression in Source2 where it is mapping memory for vertex buffers  and then not unmapping it (nor vkFlushMappedMemoryRanges) before the vkQueueSubmit that references the buffer that was mapped.

**Comment by vinjn** [comment]
FYI
Coherent mapped memory doesn't need unmap or vkFlushMappedMemoryRanges.

**Comment by vinjn** [comment]
We have fixed some of coherent mapped memory in our private fork.
Once getting stabilised, will try to push the changes upstream.
