### ISSUE TITLE
vktrace: VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT is not being handled consistently with regards to VkUpdateDescriptorSets()

### ISSUE THREAD

**Issue by plohrmann** [LunarG/VulkanTools#50]
In working through the code and reading about VkUpdateDescriptorSets, I see that  VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT should be handled similar to other descriptor types that reference the pImageInfo member, but it is not included among the switch case statements.

I don't immediately have a sample which uses it, so I can't provide a test/repro case, but since I know there are issues with trace & replay of several applications, I wanted to raise this issue as a potential cause of error. Should be a simple fix, but since I can't test & confirm it, I'll leave it to someone else to resolve.

**Comment by ardaLunarG** [comment]
Required change has been done but could not be tested.

If any issue please file a new bug.
