### ISSUE TITLE
Deadlock when tracing multi-threaded applications with PMB tracking

### ISSUE THREAD

**Issue by erik-kz** [LunarG/VulkanTools#500]
As of commit 3d3c8e59f67a5d6262200433e3780d133ec7e234 multi-threaded applications are vulnerable to deadlock during tracing if PMB tracking is enabled.

For example, while tracing DOTA 2 it was observed that one thread was stuck in this call-chain:
```
__HOOKED_vkQueueSubmit
flushAllChangedMappedMemory
vkFlushMappedMemoryRangesWithoutAPICall
vktrace_create_trace_packet
vktrace_enter_critical_section
pthread_mutex_lock
```
after having acquired `map_lock_sem_id` through `pageguardEnter`

while another thread was stuck in this call-chain:
```
__HOOKED_vkMapMemory
pageguardEnter
vktrace_sem_wait
```
after having acquired `s_trace_lock` through `CREATE_TRACE_PACKET`

It seems like if an API call will acquiring both of these locks, it needs to be done in a consistent order.

**Comment by justuswang** [comment]
Can you help to have a try with following patch?  It makes sure these locks are acquired in a consistent order if an API call will acquire both of them.  I don't have desktop environment to install DOTA 2 to test for now.

`diff --git a/vktrace/vktrace_layer/vktrace_lib_trace.cpp b/vktrace/vktrace_layer/vktrace_lib_trace.cpp
index 1fececa..46ad367 100644
--- a/vktrace/vktrace_layer/vktrace_lib_trace.cpp
+++ b/vktrace/vktrace_layer/vktrace_lib_trace.cpp
@@ -208,6 +208,9 @@ VKTRACER_EXPORT VKAPI_ATTR VkResult VKAPI_CALL __HOOKED_vkMapMemory(VkDevice dev
     vktrace_trace_packet_header* pHeader;
     packet_vkMapMemory* pPacket = NULL;
     VKAllocInfo* entry;
+#ifdef USE_PAGEGUARD_SPEEDUP
+    pageguardEnter();
+#endif
     CREATE_TRACE_PACKET(vkMapMemory, sizeof(void*));
     result = mdd(device)->devTable.MapMemory(device, memory, offset, size, flags, ppData);
     vktrace_set_packet_entrypoint_end_time(pHeader);
@@ -219,9 +222,7 @@ VKTRACER_EXPORT VKAPI_ATTR VkResult VKAPI_CALL __HOOKED_vkMapMemory(VkDevice dev
     }

 #ifdef USE_PAGEGUARD_SPEEDUP
-    pageguardEnter();
     getPageGuardControlInstance().vkMapMemoryPageGuardHandle(device, memory, offset, size, flags, ppData);
-    pageguardExit();
 #endif
     pPacket = interpret_body_as_vkMapMemory(pHeader);
     pPacket->device = device;
@@ -254,6 +255,9 @@ VKTRACER_EXPORT VKAPI_ATTR VkResult VKAPI_CALL __HOOKED_vkMapMemory(VkDevice dev
             vktrace_delete_trace_packet(&pHeader);
         }
     }
+#ifdef USE_PAGEGUARD_SPEEDUP
+    pageguardExit();
+#endif
     return result;
 }
`

**Comment by erik-kz** [comment]
Thanks for taking a look, that patch does seem to resolve the issue.

**Comment by justuswang** [comment]
Great!  PR #503 has been created which includes this patch to solve the issue.
