### ISSUE TITLE
Message "VS consumes input at location 0 but not provided" could be more helpful

### ISSUE THREAD

**Issue by jcoder58** [LunarG/VulkanTools#51]
I received the above error message from the validation layer during the call to vkCreateGraphicsPipelines with the following parameters to the DebugReport callback:

    objType:  DeviceExt
    obj:  0
    location: 0x655
    messageCode: 3
    layerPrefix:  "SC"
    message "VS consumes input at location 0 but not provided"

As someone who is new to Vulkan, I found it less then helpful.

1) Is "VS" VertexShader?

2) I would like to see more detail as to what test failed or possibly an action to take.  The VkGraphicsPipelineCreateInfo is very complex and narrowing down the issue would make it easier to track down the error.  In this case, I wasn't setting the pVertexInputState structure fields, leaving the values null.  So adding something like "pVertexInputState.pVertexBindingDescriptions must not be null" would have pointed me in the right direction.

**Comment by tobine** [comment]
Note that this is a request for improving the output of a validation message and properly belongs in the Loader and Validation Layers repo at https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.

I've assigned to @chrisforbes who can update the message as appropriate.

**Comment by mark-lunarg** [comment]
@chrisforbes , @tobine , any update on this one?

**Comment by chrisforbes** [comment]
@mark-lunarg Oops, this got ignored since it's in a different repo.

We can certainly get rid of some of the ad-hoc abbreviations in the layers, which should clarify things. I'm not sure if adding another check (with different error message) in front of the actual interface walking is great though, which is what the second half of this would fall out as.

**Comment by karl-lunarg** [comment]
Tracking this issue in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/910.  We'll close this one.
