### ISSUE TITLE
layer_factory and layersvt cmake files reference non-existent generate_helper_files target

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#527]

**Comment by sl1pkn07** [comment]
needs set CMP0046 to OLD, or use the new behavior

**Comment by KarenGhavam-lunarG** [comment]
The layer factory has been archived[ here](https://github.com/LunarG/Vulkan-Layer-Factory). There are no plans to enhance/maintain the layer factory ongoing.
