### ISSUE TITLE
Vktrace Win32 standalone build fails.

### ISSUE THREAD

**Issue by jcoder58** [LunarG/VulkanTools#54]
I followed the Win32 build instructions in vktrace/ReadMe.md, changing the target for cmake to 
"Visual Studio 14 2015 Win64".  I open vktrace/_out64/vktrace_project.sln in Visual Studio 2015 and select Build on the ALL_BUILD projects.  It fails when it is not able to find vk-generate.py.  A partial build log is posted here:

    1>------ Build started: Project: vktrace_common, Configuration: Debug x64 ------
    2>------ Build started: Project: generate_vktrace_layer_helpers, Configuration: Debug x64 ------
    3>------ Build started: Project: vktrace_layer-json, Configuration: Debug x64 ------
    2>  Building Custom Rule C:/VulkanSDK/VulkanTools/vktrace/src/vktrace_layer/CMakeLists.txt
    3>          1 file(s) copied.
    2>  CMake does not need to re-run because C:\VulkanSDK\VulkanTools\vktrace\_out64\src\vktrace_layer\CMakeFiles\generate.stamp is up-to-date.
    2>  Generating vk_dispatch_table_helper.h
    2>  '..\..\..\vk-generate.py' is not recognized as an internal or external command, 
    2>  operable program or batch file.
    2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 9009.

**Comment by davidlunarg** [comment]
There's some instructions at about line 107 in README.md in the section titled "Building Vktrace"  that say "vktrace is built as part of top level Vulkan Cmake for project".  "top level Vulkan" is incorrect, it should say "top level VulkanTools". So follow the directions for building VulkanTools in VulkanTools/BUILDVT.md, and vktrace will be built along with the rest of VulkanTools. The sections titled "Building on Linux (make)" and "Building on Windows" can be ignored and need be deleted from the document - they haven't been kept up to date.
