### ISSUE TITLE
Race condition in Linux build

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#544]
I've seen this race condition about 1 time in 5 when building this repo on my Linux system:

```
[ 38%] Building CXX object vktrace/vktrace_replay/CMakeFiles/vkreplay.dir/vkreplay_vkreplay.cpp.o
In file included from /home/lunarg/VulkanTools/vktrace/vktrace_replay/vkreplay.cpp:26:0:
/home/lunarg/VulkanTools/vktrace/vktrace_replay/vkreplay_vkreplay.h:72:38: fatal error: vk_dispatch_table_helper.h: No such file or directory
compilation terminated.
In file included from /home/lunarg/VulkanTools/vktrace/vktrace_replay/vkreplay_vkreplay.cpp:28:0:
/home/lunarg/VulkanTools/vktrace/vktrace_replay/vkreplay_vkreplay.h:72:38: fatal error: vk_dispatch_table_helper.h: No such file or directory
compilation terminated.
```
Sometimes more than 2 files have the error.  I believe that vk_dispatch_table_helper.h gets generated and maybe not before vkreplay.cpp expects it to be there.

**Comment by juan-lunarg** [comment]
VkTrace and VkReplay have been deprecated and replaced by [gfxreconstruct](https://github.com/LunarG/gfxreconstruct). Both VkTrace and VkReplay have been removed from VulkanTools and can now be found in the [vktrace](https://github.com/LunarG/vktrace) archive. Both these tools are also no longer part of the [Vulkan SDK](https://www.lunarg.com/vulkan-sdk/).
