### ISSUE TITLE
Window size too big when replaying Hologram trace

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#55]
During SDK 1.0.17 testing, I generated a Holgram trace on my Haswell system using the Mesa driver and when playing it back, the window height was bigger than the content being drawn.  This also happens with some of the Sascha Willems samples.

**Comment by davidlunarg** [comment]
Fixed in commit 7b85f2802afe2290b59184ffeb18b3c3c49736fc
