### ISSUE TITLE
vkSetDebugUtilsObjectNameEXT crash when assistant layer is enabled

### ISSUE THREAD

**Issue by cdwfs** [LunarG/VulkanTools#553]
I'm getting a NULL pointer crash in the assistant layer that ships with SDK 1.1.77.0 when calling `vkSetDebugUtilsObjectNameEXT`. It looks like the "check the dispatch table function pointer before calling it" bug that was recently fixed in the validation layers (e.g. https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2630) -- does a similar fix need to be pulled into the layer factory code (& existing factory-based layers)?

**Comment by mark-lunarg** [comment]
@cdwfs, yes, looks like the same fix needs to be applied to all the layers in VulkanTools and Samples as well.  There's actually a semi-related set of changes in flight related to returning null pointers for GetDeviceProcAddress calls where an extension is not enabled -- when this gets ported over to VulkanTools I'l try to fix this issue at the same time.

**Comment by charles-lunarg** [comment]
Closing due to deprecation of layer factory being deprecated/removed.
