### ISSUE TITLE
build_windows_targets.bat references non-existent script .\scripts\determine_vs_version.py

### ISSUE THREAD

**Issue by hrydgard** [LunarG/VulkanTools#558]
Seems to have gotten removed in 08faebac5eaeef433c41c13121953a5c0ed4e34e .

To be fair though, the current build instructions don't go this path (now that I've read them :) )

**Comment by jeremyk-lunarg** [comment]
@mark-lunarg, I believe so, but I would double check with @Tony-LunarG.

**Comment by jeremy-lunarg** [comment]
yeah, I can remove it
