### ISSUE TITLE
Tracing Khronos atw sample hits assert

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#56]
Using vktrace to trace the atw sample at https://github.com/KhronosGroup/Vulkan-Samples results in an assert - vktrace...utils.c line 147: Expression pHeader->size >= pHeader->next_buffer_offset + byteCount

**Comment by davidlunarg** [comment]
Problem has been fixed. Can successfully trace and replay atw_vulkan.
