### ISSUE TITLE
Make the trace file platform independent

### ISSUE THREAD

**Issue by jyangsh** [LunarG/VulkanTools#57]
It looks now the trace file captured from the win32 platform only can be replayed on win32 platform, right?

Can we make the trace file more platform independent? So the trace file can be replayed on different platforms.

**Comment by davidlunarg** [comment]
Support for win32 has definitely taken a backseat to other features and fixes in vktrace/vkreplay. Win32 has been only slightly tested and there are several known problems. A higher priority than 64/32 cross platform support is Windows/Linux cross platform support, which we are currently looking at. Don't hold your breath waiting for 64/32.

**Comment by karl-lunarg** [comment]
Just to be clear, we are working on cross-platform support, meaning that you should be able to record a trace on Windows (64-bit) and replay it on Linux (64-bit), and vice-versa.  There are some Vulkan-related challenges that are making this somewhat difficult and are not related to pure platform differences between Windows and Linux.  For example, the list of available Vulkan memory types could be different between the trace platform and the replay platform.  In cases like these, we have to remap features used in the trace file into things that are supported on the replay platform.  These differences can be less of a problem if you are using the same GPU on both platforms.

David is correct in pointing out the 32-bit support on Windows is lower priority.

**Comment by jyangsh** [comment]
Thanks you both! :)

I have seen the ticket #52. So the trace captured on Windows 64-bit can be replayed on linux 64-bit now? and vice-versa?

I haven't tried the tracer and retracer on the Win64 or linux64. I am working on android and arm linux, and trying to replay the trace captured on the android on the arm linux. And trying to find out a way to translate the android WSI to linux WSI.

Yes, we are replaying the trace on a same GPU.

**Comment by Tony-LunarG** [comment]
I think the answer is maybe.  I have seen differences in the number and properties of Vulkan memory types from one driver to another, so my guess would be that if the memory type layout is the same for both the Linux driver and the Windows driver, you would have a good chance of replaying a Win64 trace on Linux 64, but I haven't tried enough cases to have confidence.  If you try it and run into an issue that isn't related to memory type layout, we'd like to hear about it.

**Comment by karl-lunarg** [comment]
I think that WSI translation is also a work in progress.  Linux <-> Windows WSI translation is pretty far along, but I'm pretty sure that Android WSI translation is behind.  Perhaps David or Tony can give better status.  The status may also depend on what SDK version is in use, or if using the latest code from the repo.

**Comment by jon-lunarg** [comment]
There are a number of other things that can potentially change from one Vulkan driver to another that may cause problems. Hopefully these areas wouldn't change if the GPUs are the same but they might:  pipeline caches, device limits, device features, etc.
