### ISSUE TITLE
Parameter validation layer incorrectly complains about subresource `layerCount`

### ISSUE THREAD

**Issue by ShabbyX** [LunarG/VulkanTools#58]
According to the specs v1.0.17, a subresource's `layerCount` parameter can be `VK_REMAINING_ARRAY_LAYERS` to use all layers of a resource (i.e. image). If the image is created with a single layer, setting the parameter to `VK_REMAINING_ARRAY_LAYERS` should therefore be equivalent to setting it to 1.

However, the parameter validation layer complains that:

    ParameterValidation(ERROR): object: 0x0 type: 0 location: 2529 msgCode: 1: vkCreateImageView: if pCreateInfo->viewType is VK_IMAGE_TYPE_2D, pCreateInfo->subresourceRange.layerCount must be 1

Let me know if this is clear enough, or you would need a small code snippet.

**Comment by dustin-lunarg** [comment]
I have created the following pull request to address this: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/749

**Comment by dustin-lunarg** [comment]
KhronosGroup/Vulkan-LoaderAndValidationLayers#749 has been merged.
