### ISSUE TITLE
Swapchain validation layer complains about unspecified requirement

### ISSUE THREAD

**Issue by ShabbyX** [LunarG/VulkanTools#59]
`vkGetPhysicalDeviceSurfaceFormatsKHR()` and `GetPhysicalDeviceSurfacePresentModesKHR()` functions can have their `pXCount` and `pXs` arguments as `NULL` or not (where `X` is either `SurfaceFormat` or `PresentMode`). The specifications v1.0.17+wsi, in short says:

- if `pXs` is not provided, only the count is returned
- if `pXs` is provided, the minimum of `pXCount` and the supported number of `X`s are written to the `pXs`.

Which is nice and clear. However, the swapchain validation layer complains that:

    Swapchain(ERROR): object: 0x7fd2a3725d68 type: 2 location: 0 msgCode: 25: GetPhysicalDeviceSurfaceFormatsKHR() called with non-NULL pSurfaceFormatCount; but no prior positive value has been seen for pSurfaceFormats.
    Swapchain(ERROR): object: 0x7fd2a3725d8c type: 2 location: 0 msgCode: 25: GetPhysicalDeviceSurfacePresentModesKHR() called with non-NULL pPresentModeCount; but no prior positive value has been seen for pPresentModes.

Digging into why this error is popped, I found this comment in `swapchain.cpp`:

```
// Since we haven't recorded a preliminary value of
// *pSurfaceFormatCount, that likely means that the application
// didn't previously call this function with a NULL value of
// pSurfaceFormats:
```

The specifications don't seem to require that the function should be called with `pXs` once NULL, and then another time not NULL.

**Comment by karl-lunarg** [comment]
There's a pattern in the rest of the validation layers in checking for a previous call to get the count before calling again to get the data for many of the vkGet* functions that return pXCount and pXs sorts of data.  But in these cases, the report is at the WARNING level and not the ERROR level.   It also seems to makes sense for this to be at a WARNING level as well.   I suspect that these functions were all changed to WARNING in core validation, and were missed here.

The rest of the swapchain functions should be audited to make sure that they are consistently using WARNING in these situations.

Mark, can you handle this (or assign to another)?

**Comment by MarkY-LunarG** [comment]
Should these even be a warning?  I agree with ShabbyX that the spec doesn't say this is even recommended.  I can pass in an array of 100 and it should just fill in the appropriate amount without throwing a warning.  Perhaps, only have a warning if the array is too small and we clamp?

**Comment by karl-lunarg** [comment]
I am assuming that there had been some thinking about this in core validation and the result was to use a Warning.  So, this layer should be consistent.

Sure, the spec is clear about the independent nature of the two forms, but it looks like the validation layers are trying to be helpful, even if going beyond the spec a bit.  Perhaps the thinking is that if the user just asks for an arbitrary amount of data, there is the chance that the Get won't get everything that is available, and hence the warning.

I think that the only way a layer could issue the warning when the driver would send back a subset of the available data (clamping) would be for the layer to issue the call to get the available count itself.  This means that the layer is making a call to the driver that the app did not originate, and I'm not sure if that is "good policy" as far as the layers are concerned.

If the OP is happy with this message being downgraded to a Warning, then we should do that here in this issue.

If the OP or anyone else wants to campaign for not reporting this at all, then I'd suggest a new issue on the LVL [repo](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers).

**Comment by ShabbyX** [comment]
I personally use it to take the first available format and use it, then I check if the count is 0 for error checking. Even warnings are not necessary in my case, but I personally don't have any issues with it being a warning.

**Comment by chrisforbes** [comment]
> I think that the only way a layer could issue the warning when the driver would send back a subset of the available data (clamping) would be for the layer to issue the call to get the available count itself. This means that the layer is making a call to the driver that the app did not originate, and I'm not sure if that is "good policy" as far as the layers are concerned.

Isn't this already covered by the driver being required to return VK_INCOMPLETE? We /could/ warn if we ever see this...

**Comment by karl-lunarg** [comment]
@chrisforbes It is in some cases.  There are a few "pass NULL to get a count" functions that return void.

I suppose we could warn only on VK_INCOMPLETE where that's supported, but some may view this as inconsistent behavior.

**Comment by courtney-g** [comment]
We set it to a warning to indicate to the application that it's making an assumption that may not be safe for all hardware. After reviewing the warning, if an application decides that what it's doing is okay we would expect / hope (?) that the application would ignore that location code in the debug callback. Especially if the call is happening frequently.

**Comment by karl-lunarg** [comment]
Thanks for the background.

Then I think that the action is to just change swapchain to be consistent with the other layers.

**Comment by mark-lunarg** [comment]
This was fixed by PR# 857 on the Vulkan-LoaderAndValidationLayers github repository.

commit 8afe647a114a15d5f96297eb90d2e4435d9e9592
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Tue Aug 16 09:06:15 2016 -0600

    layers: VT59, Change query count errors to warnings

    In patterns where an API call is normally made twice, the first with
    a NULL pointer returning the count of structures to receive followed
    by second call with a pointer to the appropriately-sized buffer, the
    swapchain layer was returning validation errors if the size call was
    made. However, this is legal behavior so these now return validation
    warnings. Also updated the relevant validation tests.

    Change-Id: I9f493b27bf4fa0bec6385499c76c5cece1ad86b9
