### ISSUE TITLE
Is that possible to implement vulkan in pure SPRIV

### ISSUE THREAD

**Issue by lygstate** [LunarG/VulkanTools#6]
So the path line would turn out to be 

vulkan -> SPRIV -> AMDGPU/NVPTX/IntelGPU/OtherGPU

The SPRIV are translated at the runtime.

**Comment by lygstate** [comment]
The SPRIV-> AMDGPU/NVPTX/IntelGPU/OtherGPU can be implemented by 
LLVM
so SPRIV-> LLVM IR -> AMDGPU/NVPTX/IntelGPU/OtherGPU
Cause at the current state LLVM IR are not fully represent SPRIV, we could be able to extend the LLVM-IR
And after that, we could be  able generated AMDGPU/OtherGPU machine code directly from LLVM-IR
without lost the SPRIV semantics.

**Comment by greg-lunarg** [comment]
Expanding LLVM-IR is outside the scope of this project. Please submit this idea to llvm.org.

**Comment by lygstate** [comment]
I am talking about spirv, not llvm.
