### ISSUE TITLE
Object tracker layer complains about `VK_NULL_HANDLE` given to `vkDestroy*`

### ISSUE THREAD

**Issue by ShabbyX** [LunarG/VulkanTools#60]
The specification v1.0.17 for the `vkDestroyX` functions seem to allow `VK_NULL_HANDLE` to be given to these functions. For example `vkDestroyBufferView` says:

> If `bufferView` is not `VK_NULL_HANDLE`, `bufferView` must be a valid `VkBufferView` handle

Which implies that `bufferView` **could** be `VK_NULL_HANDLE`. This is actually nice, similar to how C's `free(NULL)` is correct and useful.

However, the object tracker validation layer complains that:

    OBJTRACK(ERROR): object: 0x0 type: 13 location: 1456 msgCode: 4: Invalid VkBufferView Object 0x0
    OBJTRACK(ERROR): object: 0x0 type: 0 location: 690 msgCode: 1: Unable to remove obj 0x0. Was it created? Has it already been destroyed?

I noticed the nvidia driver (under Linux if it makes any difference) crashing when given `VK_NULL_HANDLE` in these cases as well. Perhaps this is already the established behavior, but the specifications need to be updated to disallow `VK_NULL_HANDLE`?

**Comment by courtney-g** [comment]
It is documented in the Fundamental's chapter that it is allowed to call Destroy and Free with VK_NULL_HANDLE: It is valid to pass VK_NULL_HANDLE to any vkDestroy* or vkFree* command, which will silently ignore these values.

If the NVIDIA driver is crashing when you do that it should be reported to NVIDIA as a driver bug.

**Comment by ShabbyX** [comment]
I _did_ report it to NVIDIA as a driver bug. It was odd to me that the validation layer was also getting confused with receiving a `VK_NULL_HANDLE`.

**Comment by courtney-g** [comment]
Excellent. Then we should get things sorted out in short order.
