### ISSUE TITLE
VLF extension type warning check has false positives

### ISSUE THREAD

**Issue by baldurk** [LunarG/VulkanTools#606]
The `ExtensionTypeWarning` check in `extension_type_warning.h` has false positives.

The core check boils down to basically doing `strstr(pCreateInfo->ppEnabledExtensionNames[i], bigConcatenatedListOfExtensions)`. The problem is that searching for an extension name in a concatenated string will fail when a device extension is a substring of an instance extension - for example `VK_KHR_external_memory` which is a device extension that's a substring of the `VK_KHR_external_memory_capabilities` instance extension.

**Comment by mark-lunarg** [comment]
Fix for this issue is dependent on the Vulkan-ValidationLayers upstream.  Created [VVL issue#282](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/282) for this.

**Comment by mark-lunarg** [comment]
This has been fixed in upstream Vulkan-ValidationLayers.  The fix should propagate to VulkanTools when known-good is updated.  Reassigning to @davidlunarg.

**Comment by KarenGhavam-lunarG** [comment]
The Vulkan layer factory has been archived [here](https://github.com/LunarG/Vulkan-Layer-Factory). There are no plans to enhance/support VLF anymore.
