### ISSUE TITLE
vktrace UnmapMemory of coherent memory should always serialize

### ISSUE THREAD

**Issue by jon-lunarg** [LunarG/VulkanTools#61]
Currently on vkUnmapMemory, vktrace either serializes the entire memory range or nothing if the memory has had a FlushMappedMemoryRange on it. For non-coherent memory this is correct. For coherent memory the app doesn't necessarily need to use FlushMappedMemoryRange but it might. In this case vktrace should probably still serialize the entire range at Unmap even if it has seen some FlushMappedMemoryRange since these aren't strictly required for coherent memory so the app may be relying on the Unmap.

**Comment by karl-lunarg** [comment]
To clarify for coherent memory, the case this would catch is when the app modified the memory after doing a Flush.  Trace is skipping serialization at Unmap because it saw the Flush, but there could have been an undetected modification after the flush, right?

**Comment by jon-lunarg** [comment]
Yes that is correct.

**Comment by ardaLunarG** [comment]
This issue is fixed for windows platforms within [https://github.com/LunarG/VulkanTools/commit/90fce8689cc6c6910e587c76fe37f2357fbac90a](url)

For Linux issue persists.

**Comment by ardaLunarG** [comment]
Opening a Linux specific bug to track this issue and close this one.
vktrace UnmapMemory of coherent memory should always serialize on Linux OS #93
