### ISSUE TITLE
Question regarding formula in "Controlling the Viewport"

### ISSUE THREAD

**Issue by ShabbyX** [LunarG/VulkanTools#62]
The formula in the "Controlling the Viewport" section (specifications v1.0.17) says:

```
xf = px/2 * xd + ox
yf = py/2 * yd + oy
zf = pz * zd + oz
```

Is the above formula correct? First of all, it is [inconsistent with OpenGL](https://www.opengl.org/sdk/docs/man/html/glViewport.xhtml) which has:

```
xf = px/2 * (xd + 1) + ox
yf = py/2 * (yd + 1) + oy
```

In other words, with OpenGL, if you have a viewport with origin (0, 0) and extent (width, height), then normalized coordinates (0, 0) map to the middle of the screen. With the Vulkan formulas, the same viewport would map normalized coordinates (0, 0) to the corner of the screen.

The nvidia driver on Linux actually maps normalized coordinate (0, 0) to the middle screen with such a viewport, which is either a bug in the driver, or a hint at an incorrect formula in the specifications. Or perhaps I'm missing something?

**Comment by montykutyi** [comment]
At the and of that section (23), there is another description for the `VkViewport` structure which says how you can get the parameters for those equations above. For instance:
```
ox = x + width / 2
oy = y + height /2 
``` 
Where `x, y, with, height` are the members of the `VkViewport` structure and as the spec says  "`x` and `y` are the viewport’s upper left corner (x,y),  `width` and `height` are the viewport’s width and height, respectively."

**Comment by karl-lunarg** [comment]
@ShabbyX Vulkan specification questions are better directed to https://github.com/KhronosGroup/Vulkan-Docs.

This GitHub is really for Vulkan Tools such as vktrace, apidump, etc.

**Comment by ShabbyX** [comment]
@montykutyi Right, thanks!

@karl-lunarg Sorry about that, I'll remember it for next time.
