### ISSUE TITLE
(question) Can't make vktrace in client-server mode

### ISSUE THREAD

**Issue by DenKos363** [LunarG/VulkanTools#632]
Hello guys. Could you please help me and sort out the issue with server-client vktrace?
My goal is to catch traces for steam games (dota2 or dirt3 (windows edition, ran via steam proton), as I found out - it should be done via vktrace server. So, here are my steps:
_In first terminal:_
vktrace -o dota2.vktrace

_In second terminal:_
export VK_INSTANCE_LAYERS=Vktrace
steam steam://rungameid/530
(upd - dota 2 will be launched with these options:
export VK_ICD_FILENAMES="/home/den/mesa64/mesa-18.3.0_vulkan_21.09/share/vulkan/icd.d/intel_icd.x86_64.json"
vulkaninfo | grep 'apiVersion'
"$@" 2>&1 -vulkan | tee $HOME/demo.log)

According to your discussions in closed issues, it should be enough for generating .vktrace after closing the game. But in my case - nothing happens (trace doesn't appear).
upd - tracing directly works fine  (like ./vktrace -p '/home/den/repositories/Vulkan/bin/vulkanscene' -o bloo1m.vktrace)

What I am doing wrong?
Thank you in advance

**Comment by DenKos363** [comment]
btw - the question is about server option.
I made the trace directly, using this:
vktrace -p '/home/den/.steam/steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/dota2' -o dota2.vktrace

**Comment by davidlunarg** [comment]
Make sure that you set VK_INSTANCE_LAYERS correctly:

export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_vktrace

I have created many Steam game vk traces. Also, are you sure that whatever game you are tracing uses Vulkan? Many Steam games use OpenGL.

**Comment by DenKos363** [comment]
hmm, David. Thanks! With variable suggested by you, I generated even 3 traces (I think it is ok for launching via steam):
/home/den/repositories/Vulkan/VulkanTools/build/vktrace/bloo3m-1.vktrace
/home/den/repositories/Vulkan/VulkanTools/build/vktrace/bloo3m-2.vktrace
/home/den/repositories/Vulkan/VulkanTools/build/vktrace/bloo3m.vktrace

But according to the documentation https://vulkan.lunarg.com/doc/view/1.0.21.1/windows/trace_tools.html, on client side export should look like this:
export VK_INSTANCE_LAYERS=Vktrace

So I used exactly it

**Comment by davidlunarg** [comment]
Glad you got it working. Thanks for pointing out the error in the documentation. Will close this issue.
