### ISSUE TITLE
api_dump layer does not recognize extended image formats

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#634]
Using VK_FORMAT_G8_B8R8_2PLANE_420_UNORM in vkCreateImage, I see:

       format:                         VkFormat = UNKNOWN (1000156003)

Looking up the enumeration would be useful

**Comment by charles-lunarg** [comment]
Extensions which add enum values to core enums are not accounted for. 
This issue is identical to #742, with likely the same fix.

**Comment by charles-lunarg** [comment]
Confirming that the issue is the same, and fixed by #815
