### ISSUE TITLE
via prints uninitialized variable disable_env_value

### ISSUE THREAD

**Issue by krOoze** [LunarG/VulkanTools#650]
`via` prints uninitialized variable `disable_env_value` here:

https://github.com/LunarG/VulkanTools/blob/54cf6553b20f4261a0104e50f983875c9eb504cf/via/via_system.cpp#L1839

E.g. I have `DISABLE_VK_LAYER_VALVE_steam_overlay_1` globally set to `1`. The `via` html output says it is set to ` ƞ�`.

**Comment by MarkY-LunarG** [comment]
Fixed by PR #651
