### ISSUE TITLE
(Feature) Consider an option to "trim" the trace file

### ISSUE THREAD

**Issue by ardaLunarG** [LunarG/VulkanTools#68]
Trace files can be very large. There should be a way to collect a trace for only a portion of the entire execution, because the user may be interested only in a few frames.

**Comment by eero-t** [comment]
For example, DOTA2 trace size is >20GB even before game play has started (whereas full DOTA2 game install itself is "just" ~16GB).

**Comment by plohrmann** [comment]
We've been working on this feature and hope to get it pushed publicly soon!

**Comment by eero-t** [comment]
Thanks, sounds great!

Btw. I noticed that current traces compress pretty well, e.g. 20GB DOTA2 trace is only 1GB when Gzipped.  Maybe you could consider adding support for different compression methods to traces?  E.g. LZO (lzop & liblzo) is fast both in compression & decompression (its compression ratio isn't as good as with slower compressors).

Or if you don't want to do compression during tracing, what about having at least vkreplay supporting (separately) compressed trace files?

**Comment by ardaLunarG** [comment]
Fixed in 7bb45cac716

**Comment by eero-t** [comment]
There are few typos in the indicated commit:
- paltform -> platform
- Vulakn -> Vulkan

Btw. It would nice to have also documentation / help output for how one actually enables trimming.

**Comment by ardaLunarG** [comment]
I will address the typos.

For documentation I have filed Github Issue #186 

If it makes to SDK we will add to this to SDK documentation
