### ISSUE TITLE
vktrace: Cannot trace/replay RenderDoc multiplane test

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#686]
In the RenderDoc repository (https://github.com/baldurk/renderdoc) there are tests, one of which tests multiplane image formats.  Trying to trace and replay the VK_Video_Textures test results in a trace file that does not render anything on playback.  The VK_Simple_Triangle test does trace and replay correctly, so presumably the problem may be due to the multiplane nature of the video textures test.

There is a solution file to build the demos in the util/test directory.  Once built, run "demos_x64.exe VK_Video_Textures" to run the test.

**Comment by davidlunarg** [comment]
Submitted pull request https://github.com/LunarG/VulkanTools/pull/687 to address this issue.
