### ISSUE TITLE
Persistently mapped memory updates cannot be tracked by Vktrace

### ISSUE THREAD

**Issue by ardaLunarG** [LunarG/VulkanTools#69]
When Vulkan Application uses persistently mapped memory, vktrace cannot track updates within this memory.

**Comment by davidlunarg** [comment]
When this issue is address, we need to make sure we verify Issue #81 is also fixed. Will close #81 because it is a duplicate of this issue.

**Comment by ardaLunarG** [comment]
Issue is fixed for windows platforms within [https://github.com/LunarG/VulkanTools/commit/90fce8689cc6c6910e587c76fe37f2357fbac90a](url)

For Linux issue persists.

**Comment by ardaLunarG** [comment]
Closing this one and follow up for Linux OS on Github #90
