### ISSUE TITLE
API dump layer: Can object names be included alongside handles in API traces?

### ISSUE THREAD

**Issue by karl-lunarg** [LunarG/VulkanTools#690]
(Originally posted to KhronosGroup/Vulkan-ValidationLayers by Dominik Witczak)

Here's an example excerpt from the API dump:

Thread 1, Frame 1:
vkBindBufferMemory(device, buffer, memory, memoryOffset) returns VkResult VK_SUCCESS (0):
device: VkDevice = 000002713BF2D870
buffer: VkBuffer = 0000000000000029
memory: VkDeviceMemory = 0000000000000021
memoryOffset: VkDeviceSize = 4419584

It would be tremendously useful if object handles were followed by names assigned to the corresponding objects via EXT_debug_utils or the other deprecated extension.

**Comment by kbiElude** [comment]
Thanks, @karl-lunarg  :-)

**Comment by karl-lunarg** [comment]
Triage/implementation notes:

The layer already prints object names for debug markers as supplied by the app via `vkDebugMarkerSetObjectNameEXT`.  So it should not be too hard to extend this for Debug Utils object names.  I don't recommend adding support for the deprecated debug_report extension unless it just falls into place somehow.

It might just be a matter of implementing the shim for the debug utils SetName function(s) just like the current shim for `vkDebugMarkerSetObjectNameEXT` in the python generator.  Can probably reuse the same object name map.  And the handle output functions already add on the name string if present.

**Comment by charles-lunarg** [comment]
Issue was addressed in this commit.
https://github.com/LunarG/VulkanTools/commit/ae75956b1351d8f448f819d8ee8d8ea53595a497
