### ISSUE TITLE
Missing queues in versions 1.1.85.0 and 1.1.91.1

### ISSUE THREAD

**Issue by petereichinger** [LunarG/VulkanTools#694]
I hope this is the right place to ask:

I have macOS 10.14 with an AMD Radeon Pro 560X.
Today I updated from 1.1.82.1 to 1.1.91.1 and my application immediately stopped working since it expects at least 3 queues (one general, one dedicated for transfers and compute each). I probably should handle the case that only 1 queue is available but nonetheless there shouldn't be any differences between the versions.

With version 1.1.82.1 vulkaninfo says there are 8 queues for compute, transfer and graphics.
There is only 1in 1.1.91.1 .

I tried 1.1.85.0 as well and it shows only 1 queue.

**Comment by jeremyk-lunarg** [comment]
@petereichinger I'm taking a look at this now.  I would suggest at this time you copy this issue to https://github.com/KhronosGroup/MoltenVK for more coverage.

**Comment by jeremyk-lunarg** [comment]
Further investigation reveals that the issue you are having stems from the newer version of MoltenVK in the later SDKs.
Closing this issue.
As said above, please copy this to the MoltenVK repo if you continue to have problems.

**Comment by petereichinger** [comment]
Thank you :)
