### ISSUE TITLE
BUILD.md needs to be updated with Qt5 packages for vkconfig

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#711]
BUILD.md lists the additional packages required for Linux and Windows.

It should be updated with Qt5 packages for vkconfig and vktraceviewer.

I believe the vkconfig packages are: `qt5-default libwebengine5-dev`

**Comment by davidlunarg** [comment]
Fixed in commit 1e4ee3e9052c5cb30b8c81c13cde128df87fd813
