### ISSUE TITLE
Build failure : windows with python 3.7.2

### ISSUE THREAD

**Issue by digish** [LunarG/VulkanTools#725]
I am doing compilation of tools on windows machine. to my knowledge i have installed the mentioned deps from Build.md

however getting blow build errors.. as python does not have 'generator' package
also not able to install 'generator' subpackage using pip as it does not find any version.
thank you for help in advance.

logs below -----

cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=build/install -DVULKAN_HEADERS_INSTALL_DIR=C:\work\vulkan_tools\Vulkan-Headers -DVULKAN_LOADER_INSTALL_DIR=C:\VulkanSDK\1.1.97.0\Source\lib -DVULKAN_VALIDATIONLAYERS_INSTALL_DIR=C:\VulkanSDK\1.1.97.0\Source\lib
-- Selecting Windows SDK version  to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using find_package to locate Vulkan
-- Found Vulkan: C:/VulkanSDK/1.1.97.0/Source/lib/vulkan-1.lib
-- Vulkan FOUND = TRUE
-- Vulkan Include = C:/work/vulkan_tools/Vulkan-Headers/include
-- Vulkan Lib = C:/VulkanSDK/1.1.97.0/Source/lib/vulkan-1.lib
-- Using Vulkan-Headers install located at C:/work/vulkan_tools/Vulkan-Headers
-- Using Vulkan-Loader install located at C:/VulkanSDK/1.1.97.0/Source/lib
-- Using Vulkan-ValidationLayers install located at C:/VulkanSDK/1.1.97.0/Source/lib
-- Found PythonInterp: C:/python37/python.exe (found suitable version "3.7.2", minimum required is "3")
-- Found VulkanHeaders: C:/work/vulkan_tools/Vulkan-Headers/include
-- Could NOT find VulkanRegistry (missing: VulkanRegistry_DIR)
-- VULKAN_LOADER_INSTALL_DIR specified, using find_package to locate Vulkan
-- Found PythonInterp: C:/python37/python.exe (found version "3.7.2")
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
Traceback (most recent call last):
  File "C:/work/vulkan_tools/VulkanTools/scripts/vt_genvk.py", line 588, in <module>
    from generator import *
ModuleNotFoundError: No module named 'generator'
CMake Deprecation Warning at vktrace/vktrace_viewer/CMakeLists.txt:27 (cmake_policy):
  The OLD behavior for policy CMP0020 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find Qt5WebEngineWidgets (missing: Qt5WebEngineWidgets_DIR)
CMake Warning at C:/Qt/Qt5.12.1/5.12.1/msvc2015_64/lib/cmake/Qt5/Qt5Config.cmake:39 (message):
  Failed to find Qt5 component "WebEngineWidgets" config file at
  "C:/Qt/Qt5.12.1/5.12.1/msvc2015_64/lib/cmake/Qt5WebEngineWidgets/Qt5WebEngineWidgetsConfig.cmake"
Call Stack (most recent call first):
  vkconfig/CMakeLists.txt:9 (find_package)

WARNING: vkconfig will not include vulkaninfo or via because Qt Web Engine Widgets was not found.
-- Configuring done
CMake Error at vktrace/vktrace_dump/CMakeLists.txt:57 (add_executable):
  Cannot find source file:

    C:/work/vulkan_tools/VulkanTools/dbuild/vktrace/vktracedump_vk_dump_gen.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at vktrace/vktrace_layer/CMakeLists.txt:116 (add_library):
  Cannot find source file:

    C:/work/vulkan_tools/VulkanTools/dbuild/vktrace/vktrace_vk_vk.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at vktrace/vktrace_replay/CMakeLists.txt:92 (add_executable):
  Cannot find source file:

    C:/work/vulkan_tools/VulkanTools/dbuild/vktrace/vkreplay_vk_replay_gen.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at vktrace/vktrace_viewer/CMakeLists.txt:167 (add_executable):
  Cannot find source file:

**Comment by davidlunarg** [comment]
generator.py is from Vulkan-Headers.

Here's how I create the .sln file on my system:

> cd C:\src\VulkanTools
> .\update_external_sources.bat
> mkdir build
> cd build
> cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 15 2017 Win64"
> -DCMAKE_INSTALL_PREFIX=C:\src\VulkanTools\build\install
> -DVULKAN_HEADERS_INSTALL_DIR=c:\src\Vulkan-Headers\build\install 
> -DVULKAN_LOADER_INSTALL_DIR=c:\src\Vulkan-Loader\build\install
> -DVULKAN_VALIDATIONLAYERS_INSTALL_DIR=c:\src\Vulkan-ValidationLayers\build\install

Note that you will have to build Vulkan-Headers, Vulkan-Loader, and Vulkan-ValidationLayers before you do the cmake in VulkanTools.

**Comment by digish** [comment]
Thanks it clarified. and helped.
