### ISSUE TITLE
Address test failures that result when Vulkan-Tools/vulkaninfo changes

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#732]
See https://github.com/LunarG/VulkanTools/pull/731

**Comment by mikew-lunarg** [comment]
'jq' portion of tests/devsim_layer_test.sh is temporarily disabled.

**Comment by jeremyk-lunarg** [comment]
Fixed by https://github.com/LunarG/VulkanTools/pull/1282
