### ISSUE TITLE
windows via has inconsistent path conventions

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#747]
Windows Via (inside vkconfig) shows the **Exe Directory** as **C:/VulkanSDK/1.1.101.0/Bin** (which is Linux pathname convention), but the **Current Directory** as **C:\VulkanSDK\1.1.101.0\Bin** (the Windows pathname convention).

Both should be using the Windows pathname convention.

I don't think this is important enough to hold up this SDK.

**Comment by davidlunarg** [comment]
Duplicate of https://github.com/LunarG/VulkanTools/issues/912
