### ISSUE TITLE
Install build on Windows has lots of files missing from install folder

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#751]
Missing files include layer dll files, layer json files, vktrace.exe, vkreplay.exe, vktracedump.exe, vktraceview.exe, vkvia.exe.

There's some files I'm not sure why they are there: libGL*.dll and opengl*.dll.

Need to determine what object files should be copied to the intstall folder and modifiy cmake files to make sure those (and only those) files  are copied.

**Comment by mikew-lunarg** [comment]
A similar issue on VVL https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/743
