### ISSUE TITLE
layer_factory broken on Android

### ISSUE THREAD

**Issue by michel-iwaniec** [LunarG/VulkanTools#756]
The layer_factory is currently broken on Android. The Android.mk it generates does not include any of the sub-classes, so the result is a hollow wrapper layer that does pretty much nothing no matter what layer .so is used

Investigating the vlf_makefile_generator.py shows 3 bugs which appear to be the culprit:
* It attempts to perform an os.walk on the factory_layer, whereas this should be be done on layer_factory_path, to perform it on the directory of source files. This makes it iterate over nothing at all, hiding the other two bugs
* It strangely uses an ampersand for string formatting, where a percentage was probably intended?
* 'LOCAL_SRC_FILES += $(LOCAL_PATH)/$(SRC_DIR)/layer_factory/%s/%s\n' should actually omit the $(LOCAL_PATH)/ prefix, in order to correctly add the .cpp

**Comment by KarenGhavam-lunarG** [comment]
The layer factory code has been archived [here](https://github.com/LunarG/Vulkan-Layer-Factory). There are no plans to add layer factory support for Android.
