### ISSUE TITLE
vkreplay performance dash board

### ISSUE THREAD

**Issue by jyangsh** [LunarG/VulkanTools#765]
Does lunarG have a dash board or something to track the CPU usage performance of the vkreplay? If it exists, is it possible to share it on somewhere?

**Comment by davidlunarg** [comment]
There doesn't exist a CPU usage performance monitor specifically for vkreplay. Would System Monitor on Ubunutu or Task Manager on Windows provide the CPU usage information you are looking for?

**Comment by nickdongarm** [comment]
@davidlunarg , looks like we do not care about the vktrace performance itself here? The dashboard means that it will be gate keeper to avoid some changes which may have cpu cost in vktrace.

**Comment by davidlunarg** [comment]
It wasn't clear what the initial request was for - I think it is asking if there is a way to determine how much CPU time vkreplay is using, not including CPU time in the Vulkan Loader, Vulkan Layer, and the Vulkan ICD. Yes, knowing that would be useful, and, no, a way to do that does not currently exist. Such an enhancement should certainly be considered, but it would be added to gfxreconstuct (https://github.com/LunarG/gfxreconstruct) where where Vulkan trace enhancements are now being directed toward. An issue, or event better, a pull request would be more than welcome. :-)

**Comment by nickdongarm** [comment]
@davidlunarg , thanks for the information. Looks like you and most people who worked on vktrace now switch to gfxreconstruct. Does this mean that there will be no more work on vktrace? For gfxreconstruct, it is a beta release, how about the quality, especially on Android with mobile gpu?

**Comment by davidlunarg** [comment]
vktrace/replay is now in maintenance mode. There are still bug fixes being made to it. If someone were to propose adding major functionality to vktrace/replay, I would encourage them to instead add the functionality to gfxreconstruct. You could say gfxreconstruct is still in beta, not completely done yet. It will eventually do everything vktrace/replay can do, with better performance and better maintainability.

**Comment by nickdongarm** [comment]
@davidlunarg , sounds great. Forgive me for gabbling, is there plan or milestone on gfxreconstruct so that I   will have a plan to try or deploy gfxreconstruct later?
