### ISSUE TITLE
vkreplay crashes when play back vkUpdateDescriptorSets calls

### ISSUE THREAD

**Issue by ZLixing** [LunarG/VulkanTools#78]
I'm using vkreplay on arm+android platform and it crashed in trace files containing "vkUpdateDescriptorSets" calls:

`--------- beginning of crash`
`01-01 17:27:36.791  3356  3394 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x98b8010c in tid 3394 (Thread-266)`
`01-01 17:27:36.842   169   169 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***`
`01-01 17:27:36.842   169   169 F DEBUG   : Build fingerprint: 'Android/firefly/firefly:6.0/MRA58K/jefyan0106081402:eng/test-keys'`
`01-01 17:27:36.842   169   169 F DEBUG   : Revision: '0'`
`01-01 17:27:36.842   169   169 F DEBUG   : ABI: 'arm'`
`01-01 17:27:36.842   169   169 F DEBUG   : pid: 3356, tid: 3394, name: Thread-266  >>> com.arm.vktrace.vktrace_replay <<<`
`01-01 17:27:36.842   169   169 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x98b8010c`
`01-01 17:27:36.851   169   169 F DEBUG   :     r0 00000002  r1 00000036  r2 ffffffd0  r3 b6d992f0`
`01-01 17:27:36.851   169   169 F DEBUG   :     r4 b6d992e8  r5 98bb8670  r6 9eef0000  r7 98b80000`
`01-01 17:27:36.851   169   169 F DEBUG   :     r8 a0c92048  r9 b6d8c594  sl 00000001  fp 9ee40191`
`01-01 17:27:36.851   169   169 F DEBUG   :     ip 98b800d8  sp 9edede48  lr b6d6e613  pc b6d6b692  cpsr 200f0030`
`01-01 17:27:36.857   169   169 F DEBUG   :`
`01-01 17:27:36.857   169   169 F DEBUG   : backtrace:`
`01-01 17:27:36.857   169   169 F DEBUG   :     #00 pc 00055692  /system/lib/libc.so (ifree+49)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #01 pc 0005860f  /system/lib/libc.so (je_free+374)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #02 pc 000592a3  /data/app/com.arm.vktrace.vktrace_replay-1/lib/arm/libreplaycore.so`
`01-01 17:27:36.857   169   169 F DEBUG   :     #03 pc 00061413  /data/app/com.arm.vktrace.vktrace_replay-1/lib/arm/libreplaycore.so (vkReplay::manually_replay_vkUpdateDescriptorSets(packet_vkUpdateDescriptorSets*)+2474)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #04 pc 0008d003  /data/app/com.arm.vktrace.vktrace_replay-1/lib/arm/libreplaycore.so (vkReplay::replay(vktrace_trace_packet_header*)+16642)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #05 pc 0007f059  /data/app/com.arm.vktrace.vktrace_replay-1/lib/arm/libreplaycore.so (VkReplayReplay(vktrace_trace_packet_header*)+36)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #06 pc 00091a4b  /data/app/com.arm.vktrace.vktrace_replay-1/lib/arm/libreplaycore.so (vktrace_replay::main_loop(vktrace_replay::Sequencer&, vktrace_replay::vktrace_trace_packet_replay_library**, vkreplayer_settings)+266)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #07 pc 000921dd  /data/app/com.arm.vktrace.vktrace_replay-1/lib/arm/libreplaycore.so (android_main+1168)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #08 pc 00051233  /data/app/com.arm.vktrace.vktrace_replay-1/lib/arm/libreplaycore.so`
`01-01 17:27:36.857   169   169 F DEBUG   :     #09 pc 0003f817  /system/lib/libc.so (__pthread_start(void*)+30)`
`01-01 17:27:36.857   169   169 F DEBUG   :     #10 pc 00019f73  /system/lib/libc.so (__start_thread+6)`
`01-01 17:27:37.157  1009  3408 W ActivityManager:   Force finishing activity com.arm.vktrace.vktrace_replay/android.app.NativeActivity`
`01-01 17:27:37.157   169   169 F DEBUG   :`
`01-01 17:27:37.157   169   169 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_03`
`01-01 17:27:37.157   169   169 E DEBUG   : AM write failed: Broken pipe`

The problem may be the memory free part of manually_replay_vkUpdateDescriptorSets, I read the source code and

`pRemappedWrites[d].pImageInfo != NULL`
`pRemappedWrites[d].pBufferInfo != NULL`
`pRemappedWrites[d].pTexelBufferView != NULL`

are suspicious because it seems that these pointers are not initialized after malloc.

**Comment by ardaLunarG** [comment]
ZLixing, this is a 32bit device right?

**Comment by jyangsh** [comment]
Yes, it is arm 32bit device.

**Comment by ardaLunarG** [comment]
Assigning to Cody as he can help on 32 bit Arm Android

**Comment by ardaLunarG** [comment]
@jyangsh @ZLixing is this issue still hapepening?

**Comment by jyangsh** [comment]
Yes, it is fixed. Closed it, thanks!:)
