### ISSUE TITLE
vulkaninfo --json doesn't produce the same info as vulkaninfo

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#788]
Running `vulkaninfo --json` doesn't produce the same data that is produced by either `vulkaninfo` or `vulkaninfo --html`.  In particular, it seems to produce information only for GPU 0:
```json
{
        "$schema": "https://schema.khronos.org/vulkan/devsim_1_0_0.json#",
        "comments": {
                "desc": "JSON configuration file describing GPU 0. Generated using the vulkaninfo program.",
                "vulkanApiVersion": "1.1.106"
        },
```
No information on instance extensions, surfaces, or other GPUs seems to be present.

In fact, the output is identical to `vulkaninfo --json=0`, which is supposed to be a targeted type of `vulkaninfo`.  It seems `vulkaninfo --json` assumes a target, and there's currently no way to get a JSON-formatted `vulkaninfo` with information about the Vulkan instance.

**Comment by lunarpapillo** [comment]
> The rationale for leaving content out of the JSON representation is there isn't schema to define what it is supposed to look like. The original schema defined what was needed by DevSim; things have been added since. While the schema is forgiving about content it doesn't recognize, we refrain from creating schema until we have a usecase from an actual consumer (as would be the case when DevSim is extended to use that new data.)

The real problem here is expectation: the `--help` text for the `--json` switch says: "Produce a json version of vulkaninfo output to standard output."  If we're not producing the same data in a JSON format, that's a lie.  Note the `--html` switch, which has similar phrasing "Produce an html version of vulkaninfo output", but clearly does produce the same data.

Perhaps we could just reword the `--help` text to indicate what we're actually producing with the `--json` switch.  (I'm not entirely sure how to phrase that... "produce DevSim output, but with some things added" doesn't really make things clearer...)

> we refrain from creating schema until we have a usecase from an actual consumer

It's a bit lopsided to create new stdout and HTML output without use cases, but to require use cases for JSON output.  IMHO.

One natural use case for JSON output (the one I actually presumed was the case - I had no idea `--json` was originally put in place to support DevSim until you mentioned it) is someone who wishes to reliably and programmatically parse `vulkaninfo` information (for any reason).  In this use case, **all** the `vulkaninfo` output should be present in the JSON; whether the schema is published or not is less important than it being backward-compatible, because the schema can be sufficiently determined by inspection.  The `--help` text could note that the output is compatible with DevSim.

**Comment by mikew-lunarg** [comment]
I agree we should communicate (via --help or docs) how to use the JSON and/or how to implement.  There are docs in the source code, but that's not helping the interpretation of output at runtime.  

The usecase for HTML is a human reader; the usecase for JSON is another program.  Humans don't need as much backwards compatibility.  The existence of JSON output implies (reasonably IMO) that tools can be written to depend upon it.  vulkaninfo is not exclusively for use by DevSim; other tools could use the JSON.

Creating schema for JSON isn't hard, but it merits deliberate design.  What we _dont_ want to happen is some ad hoc JSON representation stuck together, then tools get written to consume that, and creating a proper representation cant happen due to backwards compatibility.  That's exactly what happened with the `vkjson` tool, it continues to live due to a tool chain depending on it.  There's desire to migrate the tool chain to vulkaninfo, but not the motivation (if not broke, dont fix)

**Comment by mikew-lunarg** [comment]
For the current SDK, I propose we document somehow the difference between HTML and JSON content, and not generated ad hoc formatted JSON until a schema is defined, so that JSON can be validated.

**Comment by lunarpapillo** [comment]
I don't think it's necessary for the current SDK.  (I've tested 3 SDKs so far and just noticed this now, so it's clearly not vital enough to hold up a release.)  It would be nice to do for the next.

> That's exactly what happened with the` vkjson` tool

I'd want to know more about this (never heard of `vkjson`).

In my experience, "ad hoc" JSON representations with some reasonable level of design have worked just fine, and certainly better than requiring people to create tools that scrape HTML or text to get the information they need because someone was cautious to put it in a JSON.  (Or is the programmatic parsing use case a non-requirement for us?)

There are various ways to protect backward compatibility while leaving the structure open to enhancement.  I'll save those for the design.

All IMHO, of course.

**Comment by mikew-lunarg** [comment]
Both [JSON](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) and [json-schema](https://json-schema.org/) have formal specifications, which the implementer of ad hoc JSON might not obey.  Not everything that looks like JSON is legal JSON, even if it might work "just fine" with some tool.

Certainly we dont want to encourage scraping of HTML.  Wrong tool for the job, that's what the JSON is for.  The divergence of the formats is fairly recent, and _should_ be fixed.  The author of the recent HTML additions also provided JSON, but we declined the latter.  It requires schema design (to which I'll be glad to invite you!)

One of the huge benefits of using legal JSON is leveraging its vast ecosystem: the schema language, tools like [`jq`](https://stedolan.github.io/jq/), open-source parsers, and schema validators.

The output that `vkjson` is _not_ legal JSON, although it looks confusingly similar.   As one example, it uses hexadecimal representation for integers, which is not legal JSON, numeric values must be decimal.  (not that I like it, but that's the spec)  That non-conformance is part of why we broke compatibility with `vkjson` output when defining `vulkaninfo` output.

`vkjson` was in Vulkan-Tools repo I think, but was moved to an Android repo, as that's the toolchain that required it.

Compliant JSON parsers will _not_ read `vkjson` output properly, and a JSON schema can _not_ be defined for it.    A schema cannot be retroactively deduced from some formatting that is not legal JSON.

There are constructs in Vulkan (defined as a C API) that do not map cleanly to JSON datatypes, some interpretation and mapping is necessary.  That interpretation can lead to different implementations (again what happened between `vulkaninfo` and `vkjson`)  Even things like names of datatypes going from C to JSON require design decisions.   Those decisions should not be made lightly, with the belief of retroactively creating a schema and passing validation.

**Comment by mikew-lunarg** [comment]
A clarification: `vkjson` expressed its hexadecimal values as JSON strings, not numbers.  So while legal JSON, that obscures the datatype, and loses the semantic benefits of numeric validation by a schema.

**Comment by charles-lunarg** [comment]
Now that the vulkaninfo refactor is finished, it would be much easier to add back the missing json capabilities. It wouldn't be to hard to add a "--json-full-info" option which prints the same as text & html. That way we keep the existing schema compatible output and add a new schema that contains the full info possible.

**Comment by mikew-lunarg** [comment]
Awesome!  The important thing is to define the schema first, then implement the output to match that schema.  The new output can then be validated against the schema.

**Comment by mikew-lunarg** [comment]
@charles-lunarg If you could create a list of the new structures to be implemented, we can review for approaches for JSON formatting.  It's not hard, but there are several Vulkan C idioms that really don't map cleanly to JSON types, so there are some new idioms to be aware of.

**Comment by charles-lunarg** [comment]
Quick list I made:
Instance Extensions. Name & revision
Surfaces: VkSurfaceFormatKHR, VkPresentModeKHR, VkSurfaceCapabilitiesKHR (and 2, & EXT), and pNext chain (VkSharedPresentSurfaceCapabilitiesKHR,	VkSurfaceCapabilitiesFullScreenExclusiveEXT, VkSurfaceProtectedCapabilitiesKHR)

Groups: VkPhysicalDeviceProperties, VkDeviceGroupPresentCapabilitiesKHR, VkDeviceGroupPresentModeFlagsKHR

Device specific items:
pipelineCacheUUID is in json but *not* in text/html 
Device Extension list
pNext chains for VkPhysicalDeviceProperties and VkPhysicalDeviceFeatures
extend VkQueueFamilyProperties to include present support for which surface extensions

Action item would be whether we should support the pNext chains o Features only has bool values but has Properties have some members that need special consideration, namely VkPhysicalDeviceDriverPropertiesKHR & 
VkPhysicalDeviceIDProperties. The real question about pNext chains is that they would require modification of the schema when the spec is updated. Not including them would be simpler, but it wouldn't remedy the issue of divergence between output formats. I am for including pNext chains, for output parity, and think it would even be possible to auto-gen those sections of the schema.

**Comment by charles-lunarg** [comment]
Addressed by PR https://github.com/KhronosGroup/Vulkan-Tools/pull/328 which adds a new output backend which mirrors text/html but is in json form.

**Comment by charles-lunarg** [comment]
This was addressed by the Vulkan-Tools PR 328 https://github.com/KhronosGroup/Vulkan-Tools/pull/328. While not a publicly facing backend, it does present the same info as text & html but in json form.

**Comment by mikew-lunarg** [comment]
> adds a new output backend which mirrors text/html but is in ~~json~~ *vkconfig_private*  form.

**Comment by charles-lunarg** [comment]
Closing the issue because vulkaninfo now has text describing how the json output conforms to the dev sim schema, and that there hasn't been a pressing demand for a json output version (beyond the vkconfig_output which was recently merged).
