### ISSUE TITLE
Should this repo be merged with Vulkan-Tools?

### ISSUE THREAD

**Issue by krOoze** [LunarG/VulkanTools#790]

**Comment by KarenGhavam-lunarG** [comment]
The content in Vulkan-Tools is Khronos branded and copyrighted. The content in LunarG/VulkanTools is LunarG branded and copyrighted. Khronos and LunarG would need to decide if they wanted to change that.

What motivates you to want to merge the content?

**Comment by krOoze** [comment]
Just general convenience, and repo discoverability. Also the repo name indicates identical purpose.

The Issue is in the form of a question. Just close it if merging does not make sense.
I thought there is some agreement with Khronos recently over the SDK. I think you guys previously owned the Validation Layers as well as the other Tools repo. How does this repo differ?

**Comment by KarenGhavam-lunarG** [comment]
Khronos owns the Vulkan-ValidationLayers and Vulkan-Tools repos.
LunarG owns the LunarG/VulkanTools repo.

The SDK pulls in content from many sources (Khronos owned or not).

It is true of the similarity in terms of names Vulkan-Tools vs. VulkanTools. When the Loader and Validation Layers were all in one repository and we were splitting them apart, we struggled on the name for Vulkan-Tools but out of the choices we had it seemed to be the best choice.

I am inclined to close this issue for now in that LunarG is currently not motivated to try to merge this repository with the Vulkan-Tools repository.
