### ISSUE TITLE
api_dump should print output before calling ICD

### ISSUE THREAD

**Issue by krOoze** [LunarG/VulkanTools#791]
`api_dump` should provide output before calling ICD.
It may be useful for debugging to see the values. If the driver crashes nothing gets to be shown.

I assume this is only because of need to show `VkResult`. This can be solved differently, e.g. showing it after rest of the output, e.g.:

```
vkSomethingOrOther
argument dump
-> VK_SUCCESS
```

**Comment by davidlunarg** [comment]
Yes, I agree that dumping the api call name and args before calling the next layer would be a useful feature. This is not trivial - most calls could be dumped before calling the next layer. However, calls that query information would need to be dumped after the call to the next layer has returned. So not all calls would be treated the same as they currently are.

**Comment by krOoze** [comment]
Hmm, could be done in two stages then. First the commands that have no output (except VkResult). Then figure out the few outputing commands that remain.

**Comment by charles-lunarg** [comment]
#867 Created PR to address this issue. Not all functions are dumping first, only those without return values or with no parameters that are set by the driver (vkGet*** functions for example).

**Comment by charles-lunarg** [comment]
Closing issue as the aforementioned PR has been merged. The PR has since been modified to have every function call print the function name before calling icd, so apidump will always display the most recent function call before any driver crashes.
