### ISSUE TITLE
Change location of vkVIA  output?

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#792]
I ran vkvia, the output file showed up on my desktop.

I ran it again, this time it showed up in C:\VulkanSDK\1.1.106.0\Bin.

I ran it again, this time it show up in C:\VulkanSDK\1.1.106.0\Bin.

As it turned out, the first time I ran it from the start menu. The second time, I navigated to the SDK Bin folder and double clicked on via. The third time, I typed vkvia in a cygwin bash shell while cd'ed to ~.

I had to search for the output file each time causing me great confusion. 

Here are some ideas that might improve this:
1. Make the html report inside a temp folder, and when finished open it with default browser.
2. Add options to via to specify the name/location of the output file and to disable opening the output file so that scripts can run via and collect the output

Also note that VIA when run from the tab on vkconfig will put it's output in the window.

**Comment by davidlunarg** [comment]
https://github.com/LunarG/VulkanTools/pull/1727 addresses this issue. The location of the html file was not changed, but the html file is opened in a browser window. This change was done only on Windows.
