### ISSUE TITLE
Add flag to override the use of default system libs

### ISSUE THREAD

**Issue by edrickhong** [LunarG/VulkanTools#795]
when running cmake to configure the build, vt_genvk.py uses the system vulkan registry instead of the one build by update_deps.py . This is problematic because the one that I got thru the repos is older than the one VulkanTools expects and the build will fail. Is there a way to explicitly overwrite this behaviour??

**Comment by juan-lunarg** [comment]
This is now fixed. Default system libs aren't used. As you pointed out this is undesirable.
