### ISSUE TITLE
Bring api_dump up to date with current api and extensions

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#796]
For instance, the structs and enums for VK_KHR_sampler_ycbcr_conversion are output as UNKNOWN.  One could look at the history of vulkaninfo to see what extensions it has added over time.  One could also api_dump many tests / examples and see what fields show up as UNKNOWN.

**Comment by charles-lunarg** [comment]
pNext chains are now being dumped in PR #848
