### ISSUE TITLE
api_dump: Remove unnecessary Memory info

### ISSUE THREAD

**Issue by MarkY-LunarG** [LunarG/VulkanTools#799]
API Dump outputs the MemoryType and MemoryHeap information all the way to the end of the static array sizes.  This tends to add a lot of garbage since the structure also contains the size/count of the valid data within those structures.  Limit the output to only the valid heaps and types to reduce garbage in the output.

**Comment by cdgiessen** [comment]
I've made #819 to address this.
Required specializing the VkPhysicalDeviceMemoryProperties as there is no easy way to get an array output.
VkPhysicalDeviceGroupProperties also had similar behavior and was also modified.

**Comment by charles-lunarg** [comment]
I've made #819 to address this.
Required specializing the VkPhysicalDeviceMemoryProperties as there is no easy way to get an array output.
VkPhysicalDeviceGroupProperties also had similar behavior and was also modified.
