### ISSUE TITLE
Trace and replay of cube (and others) gets DEVICE_LOST errors

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#80]
Windows 7, SDK 1.0.21.2, Nvidia GTX 660 ti, driver 372.54 vktrace the cube.exe in the SDK bin directory then replay and I get no rendering and a stream of VK_ERROR_DEVICE_LOST messages.  Going back to the commit before "vktrace: map memory types on replay" 7d5b2e98963e1 and everything works fine.

The driver is a key component to reproducing the failure.

**Comment by davidlunarg** [comment]
Partially fixed in 3ceea22f6e4c516af994ec7998044b4f8c3256bb. We still need to address the problem of differentiating between identical entries in the device memory properties table, which likely requires an API change. Will create a new issue for that.
