### ISSUE TITLE
Add renderdoc frame export to vktraceviewer

### ISSUE THREAD

**Issue by edrickhong** [LunarG/VulkanTools#811]
It would be nice to be able to scrub through the trace viewer and open a specific frame in renderdoc to debug some bugs that only show up for a few frames

**Comment by davidlunarg** [comment]
vktrace/vkreplay/vktrace_viewer are now in maintenance mode, eventually to be replace with gfxreconstruct (https://github.com/LunarG/gfxreconstruct). As tools are added to gfxreconstruct, this feature should be kept in mind. You might submit this issue to gfxreconstruct.

**Comment by edrickhong** [comment]
I'll do just that. thanks
