### ISSUE TITLE
vktraceviewer timeline causes 20% CPU utilization

### ISSUE THREAD

**Issue by plohrmann** [LunarG/VulkanTools#82]
I noticed my machine was churning heavily while I had 2 instances of vktraceviewer running; each one was causing 17-20% CPU utililization.

Suspecting the timeline to be the culprit, I commented out its creation, and confirmed that the CPU utilization goes down to ~0%.

On deeper dive, looks like viewport()->update() is being called within the paintEvent, which would cause another paint event to be signaled. We're continually repainting the timeline... yeah, that's bad.

**Comment by davidlunarg** [comment]
Issue #85 references a pull request to address this problem. Pull request has been merged. Closing.
