### ISSUE TITLE
vktraceviewer crashes on shutdown

### ISSUE THREAD

**Issue by plohrmann** [LunarG/VulkanTools#83]
Exception thrown: read access violation.
this->m_pController-> was 0xFFFFFFFFFFFFFF7F.
If there is a handler for this exception, the program may be safely continued.

>	vktraceviewer.exe!vktraceviewer::close_trace_file() Line 698	C++
@ the line "m_pController->UnloadTraceFile();"

```
void vktraceviewer::close_trace_file()
{
    if (m_pController != NULL)
    {
        ui->bottomTabWidget->removeTab(ui->bottomTabWidget->indexOf(m_pTraceStatsTab));
        m_pController->UnloadTraceFile();
#ifndef USE_STATIC_CONTROLLER_LIBRARY
        m_controllerFactory.Unload(&m_pController);
#else
        vtvDeleteQController(m_pController);
#endif
    }
```

**Comment by davidlunarg** [comment]
Fixed. CID is 8d787231b59f669fbd1a4b077eeb41ccf8943992.
