### ISSUE TITLE
Enhancement ideas for vkconfig on Windows

### ISSUE THREAD

**Issue by mikew-lunarg** [LunarG/VulkanTools#830]
Improving the user experience of vkconfig on Windows:

Running from the start menu on Windows:
1. vkcube windows pop open and close twice
1. A window opens with "vulkaninfo" at the top in large letters.  (I realize it says "Vulkan Configuration Tool" in the title bar.)

My initial impression was I had selected the wrong item from the start menu.

It would be nice:
- To open a clearly labeled vkconfig window _before_ running vkcube, perhaps announcing what and why vkcube are for.
- The three tabs contain content of totally different look-and-feel.
- I would expect "Layer Manager" to be the first and default tab, since that's what the tool is configuring; the other tabs are informational only
- To use consistent terms:
  - "vkconfig" v "Vulkan Configuration Tool" v "Layer Manager"
  - "VIA" v "vkvia" v "Installation Analyzer"

**Comment by mikew-lunarg** [comment]
As VIA is embedded, note additional suggestions at #829

**Comment by KarenGhavam-lunarG** [comment]
Vkconfig is currently under major UI redesign and implementation. The next release (pretty soon) is different enough that this issue probably does not apply anymore. So I am going to close this and we can enter new issues against the new vkconfig when released.
