### ISSUE TITLE
Deprecation of vktrace/vkreplay

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#835]
Over the next several months vktrace/vkreplay will be deprecated, to be replaced by gfxreconstruct (https://github.com/LunarG/gfxreconstruct). New development work for Vulkan trace tools should be directed to gfxreconstruct. At this point vktrace/vkreplay is in maintenance mode.

A consideration for transitioning from vktrace to gfxreconstruct is the porting of existing traces created with vktrace to gfxreconstruct. At present, there are no plans to create tools or add capability to gfxreconstruct to assist in this porting.  Existing vktrace traces will need to be converted by replaying the trace and tracing the replay using gfxreconstruct.

**Comment by KarenGhavam-lunarG** [comment]
vktrace/vkreplay has been removed from this repository. You can find it in [LunarG/vktrace](https://github.com/LunarG/vktrace). It has been archived in read only mode (no longer under development)

**Comment by mikew-lunarg** [comment]
It doesn't appear that the Archive flag is set on the https://github.com/LunarG/vktrace repo.  That puts an obvious banner across the top of the page.

**Comment by KarenGhavam-lunarG** [comment]
Working on the archive. doing some last minute auditing before pushing the button
