### ISSUE TITLE
vkreplay should probably exit immediately if it ever gets VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by davidlunarg** [LunarG/VulkanTools#84]
Maybe it needs to exit on other errors too?

**Comment by plohrmann** [comment]
I agree about VK_ERROR_DEVICE_LOST, but not necessarily on other errors. It
is possible that the application itself had errors, but detected them and
handled the situation appropriately. We shouldn't bail on that. Likewise,
there are cases when drivers (or validation layers) incorrectly report
errors that we wouldn't want to impede trace & replay.

**Comment by davidlunarg** [comment]
Fixed in commit 6f499de78d7ea850f0c5aee69f79ad34860aa431

Only exit on VK_ERROR_DEVICE_LOST. Other errors that do not match the error in the log file are logged to output.
