### ISSUE TITLE
Does not build on Ubuntu 19.04

### ISSUE THREAD

**Issue by reduz** [LunarG/VulkanTools#856]
-- Using find_package to locate Vulkan
-- Vulkan FOUND = TRUE
-- Vulkan Include = /usr/include
-- Vulkan Lib = /usr/lib/x86_64-linux-gnu/libvulkan.so
CMake Error at CMakeLists.txt:37 (message):
  Must define location of Vulkan-Headers install -- see BUILD.md

I have installed vulkan headers, loader, validation layers, etc. from Ubuntu packages and won't override it with source ones, so hoping these can be detected and used.

**Comment by reduz** [comment]
As a reference, i tried to compile vulkan headers and tools manually, but it's not possible either:
https://github.com/KhronosGroup/Vulkan-Loader/issues/209

**Comment by reduz** [comment]
Also by the way, this also happens if I use the same branch version as Ubuntu: sdk-1.1.101

**Comment by reduz** [comment]
I really suggest some way to compile this without forcing me to replace the system headers is considered, either by using them or by bulding as direct dependency on GitHub so it compiles everything together.

**Comment by davidlunarg** [comment]
Try building VulkanTools using the instructions in BUILD.md as described in the section titled "Building Dependent Repositories with Known-Good Revision":

>For all platforms, start with:
>
>git clone --recurse-submodules git@github.com:LunarG/VulkanTools.git
>cd VulkanTools
>mkdir build
>
>For 64-bit Linux and MacOS, continue with:
>
>./update_external_sources.sh
>cd build
>../scripts/update_deps.py
>cmake -C helper.cmake ..
>cmake --build .

This will get copies of all external dependencies and build VulkanTools. No system files are modified.

**Comment by reduz** [comment]
Apologies, I missed this answer. I will try again and document what's going on.

**Comment by KarenGhavam-lunarG** [comment]
Closed due to inactivity
