### ISSUE TITLE
VIA: via32 uses the wrong runtime?

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#861]
Found during testing of 1.1.114 SDK: Run C:\VulkanSDK\1.1.114.0\Bin32\vkvia.exe
The output indicates that the runtime used by the app is C:\Windows\System32\vulkan-1.dll. 

This should be C:\Windows\sysWOW64\vulkan-1.dll?

**Comment by KarenGhavam-lunarG** [comment]
@jeremyk-lunarg Since you have been working with VIA recently for a port to macOS, would you feel comfortable resolving this issue?

**Comment by jeremyk-lunarg** [comment]
Fixed by [PR #922](https://github.com/LunarG/VulkanTools/pull/922) which has been merged.
