### ISSUE TITLE
vktrace command line argument handling issues

### ISSUE THREAD

**Issue by djdeath** [LunarG/VulkanTools#862]
I'm trying to trace vkreplay to look at the generated commands.
Unfortunately vktrace's custom command line parser doesn't seem to deal with this very well :
Here is what I'm typing : 

```
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_screenshot VK_SCREENSHOT_DIR=/tmp/screen vktrace -p vkreplay -w $PWD -o /tmp/meta-computecullandload.vktrace -a " -o /tmp/computecullandlod.vktrace -s all -lsf 20 -lef 20 -ds xcb"
```

The custom command parser falls over on the second `-o` in the `-a` argument.

**Comment by davidlunarg** [comment]
The vktrace invokes the vkreplay command. When vktrace invokes a program to trace, it does not search for it in your PATH - it expects the full path to be given, or it must reside in the current directory. Is vkreplay in the current directory?

I slightly modified your command so it would work on my system, and added a full path for the vkreplay command, and it works. Here's what I successfully ran:

$ VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_screenshot VK_SCREENSHOT_DIR=/tmp vktrace -p /home/david/sdk/1.1.114.0/x86_64/bin/vkreplay -w $PWD -o ./cnew.vktrace -a " -o /tmp/c.vktrace -s all -lsf 20 -lef 20 -ds xcb"

**Comment by djdeath** [comment]
Thanks @davidlunarg, no vktrace/vkreplay were not in the current directory.
Works now :)
