### ISSUE TITLE
HTML font is tiny on high DPI Windows

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#864]
Need to package up a qt.conf with the Windows build to the effect of:
```
[Platforms]
WindowsArguments = dpiawareness=0,1,2
```

**Comment by bradgrantham-lunarg** [comment]
As noted in https://doc.qt.io/qt-5/highdpi.html

**Comment by KarenGhavam-lunarG** [comment]
No longer an issue with new vkconfig and this issue was fixed in last SDK with old version of vkconfig
