### ISSUE TITLE
implicit layers aren't discovered by vkconfig with a custom layer path but are still loaded by loader

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#870]
On my laptop I have set a custom layer path.  At that path I have stored the api_dump .dll and .json. 
 I have Optimus (injected by NVOLGV) and RenderDoc (installed).  APIdump is shown in "explicit layers" but neither Optimus nor RenderDoc are shown in "implicit layers".  I can still run RenderDoc, and api_dump saves a dump file.  So I believe I *am* overriding to force api_dump on, and I believe RenderDoc implicit *is* getting enabled by the RenderDoc app.

I'm not sure it would be a good idea to be able to force the renderdoc layer off but it would be useful for me to force Optimus off.  I can't do that without seeing Optimus in the implicit layer list.

vkconfig could probably be pointed at the implicit layers directory.  For some layers it may need to probe Vulkan directly.

**Comment by bradgrantham-lunarg** [comment]
If I add the RenderDoc directory to the layer locations as a custom layer path, I do see it, as an explicit layer (see https://github.com/LunarG/VulkanTools/issues/875), and I can disable it (forcing RenderDoc's functionality off).

If I search for additional layers using "Search" in "Layer Locations", I can also find the NVIDIA layer manifests, which reference Optimus.  (However, multiple manifests exist, so it's not clear which one is the actual loaded Optimus, so I have to forcibly disable all of them.)

So I think this isn't quite the right bug for this issue.  Really the issue is that setting a custom layer path causes only the explicit layers at the custom path to be enable-able as explicit layers, but the implicit layers are still loaded, so they have to be added as custom paths also in order to forcibly disable them.  Perhaps having VK_LAYER_PATH should forcibly disable implicit layers (so *all* layers) unless those implicit layers are in the VK_LAYER_PATH...

**Comment by KarenGhavam-lunarG** [comment]
Not an issue in the next revision of vkconfig
