### ISSUE TITLE
Add vk_layer_settings.txt support to screenshot layer

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#872]
environment variable |  proposed vk_layer_settings key  |  Description
--------------------|-----------|----------------------------------------
VK_SCREENSHOT_FRAMES     |  lunarg_screenshot.frames        |  Set to a comma-separated list of frame numbers.
VK_SCREENSHOT_DIR        |  lunarg_screenshot.dir           |  Set to specify the directory in which to create the screenshot files.
VK_SCREENSHOT_FORMAT     |  lunarg_screenshot.format        |  Set to desired pixel component format to read, one of UNORM, SNORM, USCALED, SSCALED, UINT, SINT, SRGB

Adding support for these keys to these layers and then adding these keys to vkconfig/layer_info.json will enable vkconfig to control the screenshot layer.

**Comment by jeremyk-lunarg** [comment]
Fixed by PR #884 which has been merged.
