### ISSUE TITLE
vkconfig thinks all custom layers are explicit

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#875]
On Linux, when adding custom paths, even adding an implicit_layer.d appears as an explicit layer.

![vkconfig_implicit](https://user-images.githubusercontent.com/50641407/62881692-31c46d00-bce5-11e9-893e-d567822725bf.png)

Custom layers are currently always explicit. There is disabled code guarded by LAYERMGR_CUSTOM_IMPLICIT at https://github.com/LunarG/VulkanTools/blob/9f718a34447e71c8730d83c015564a4a129b5ee3/vkconfig/layer_locations_widget.cpp#L102 that allows selecting whether an added layer path is to implicit or explicit layers.

We could guess by whether the path has "implicit" or "explicit" in it. I don't think there's a way to automatically determine that a layer is implicit from the manifest.

**Comment by KarenGhavam-lunarG** [comment]
No longer an issue with next version of vkconfig
