### ISSUE TITLE
vkconfig: cannot select multiple layers in "Disabled Layers" field

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#879]
Ubuntu 16.04, installed packages. Cosmetic. In both the Enabled Layers and Unset Layers fields, the user may drag across the list of layers to select multiple layers at once, or may use the CTRL key to select multiple non-contiguous layers.

In the Disabled Layers field, only a single layer can be chosen at a time. Dragging doesn't work to select contiguous layers, nor does CTRL-clicking work to select non-contiguous layers.

**Comment by KarenGhavam-lunarG** [comment]
No longer relevant in next version of vkconfig
