### ISSUE TITLE
Add VIA communicated by JSON and display in non-HTML

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#880]
QT Web view widget is not available in Ubuntu 16.04.  Fix this issue and make vkconfig more controlled and less bloated in general by adding JSON (or other machine-readable output) to vkvia, then consume that in vkconfig and display in a qt cascading list view.

**Comment by charles-lunarg** [comment]
Via now can output json for use in the vkconfig rewrite, closing the issue as the VIA portion of the task is now complete.
