### ISSUE TITLE
display of time expiration is awkward if "Undo changes on exit" is checked or if units are "Never".

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#882]
Perhaps we can show a "Set Expiration" button instead which would bring up a dialog to select a time period. Then when the dialog is closed the expiration time would be shown as text next to that button. Then checking "Undo changes on exit" would cause "Set Expiration" to be disabled and the text would disappear.

**Comment by mikew-lunarg** [comment]
Sounds like a good simplification.

**Comment by KarenGhavam-lunarG** [comment]
Next version of vkconfig does not have an expiration feature.
