### ISSUE TITLE
"Clear All" (paintbrush or backspace)  and "Remove One" (big X) icons are not clear

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#889]

**Comment by bradgrantham-lunarg** [comment]
The icon for "Clear All" looks like a paintbrush. It wasn't intuitive to me what this would do. (The tooltip helped.)

On Linux, the "Clear All" icon looks like a backspace key. Better than a paintbrush, but still not clear to me - I would have thought the backspace icon would clear one, and the big X would clear all, which is backwards from what actually happens.

**Comment by KarenGhavam-lunarG** [comment]
Vkconfig is currently under major UI redesign and implementation. The next release (pretty soon) is different enough that this issue probably does not apply anymore. So I am going to close this and we can enter new issues against the new vkconfig when released.
