### ISSUE TITLE
Adding extensions used into vktrace header

### ISSUE THREAD

**Issue by ardaLunarG** [LunarG/VulkanTools#89]
Enquiry the extension used during trace and add to trace header. 

During replay print this information and try to find matching extension on the replay platform.

Extend this information with GPU vendor and driver version.

**Comment by Tony-LunarG** [comment]
With d6f8f98 when the replay of CreateInstance or CreateDevice fails with EXTENSION_NOT_PRESENT, the extensions requested will be logged to INFO.  I believe this fixes the spirit of this issue.  If not, feel free to open another issue.
