### ISSUE TITLE
Maybe there should only be one arrow to move layers between Unset and Enabled and Disabled lists

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#892]
Maybe the arrow should move selected layers in both lists.

**Comment by KarenGhavam-lunarG** [comment]
Vkconfig is currently under major UI redesign and implementation. The next release (pretty soon) is different enough that this issue probably does not apply anymore. So I am going to close this and we can enter new issues against the new vkconfig when released.
