### ISSUE TITLE
Buttons should deactivate if they aren't appropriate to the context

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#893]
It would be nice if the buttons would deactivate if they weren't appropriate to the context:

if no layer is selected, the "Remove Selected" button deactivates
if no layers are set, the "Clear all" button deactivates
if there have been no changes to the current configuration, the "Save" button deactivates
if the current configuration matches the cleared configuration, the "Clear" button deactivates
Doing so would make the action of the tool more obvious.

**Comment by KarenGhavam-lunarG** [comment]
Vkconfig is currently under major UI redesign and implementation. The next release (pretty soon) is different enough that this issue probably does not apply anymore. So I am going to close this and we can enter new issues against the new vkconfig when released.
