### ISSUE TITLE
Clarify whether Save has saved everything or just overrides and layer settings

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#894]
The state of the "Undo changes on exit" and "Show enabled layers only" checkboxes should be saved and restored (because the "Save" button declares that it's saved all layers and settings, while these settings are clearly not saved).

Alternately, clarify in the "Save" message that "Saved all layers and associated settings" or "Saved all layers and layer settings". (But I'd rather see the checkbox state saved.)

**Comment by KarenGhavam-lunarG** [comment]
Not relevant anymore in next revision of vkconfig
