### ISSUE TITLE
Maybe VKConfig could have an active visible countdown timer for Expiration

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#895]
It's not clear how "Expiration time" works. I presumed it would be expiration after exiting vkconfig. It seems to actually be expiration from the last time a setting was saved in vkconfig.

It's also impossible to tell in the GUI whether the current settings have expired. Some indicator would be helpful, whether subtle (i.e. the "Save" button reactivates, showing that the displayed configuration is not the same as the effective configuration) or dramatic (i.e. the GUI adjusts to show the current effective configuration).

Showing the current expiration as a countdown timer would help this.  This probably means rereading the override settings and parsing the expiration information on restart, so the timer can be accurate.

But really expiration should just go away.

**Comment by KarenGhavam-lunarG** [comment]
Next vkconfig no longer will have expiration times.
