### ISSUE TITLE
Undo changes on exit does not behave like a stack but implies it does

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#896]
There's a subtlety in the current working model. If I change some layers, uncheck "Undo changes on exit", and save, I expect those changes to be persistent.

If I then change other layers, but check "Undo changes on exit", save, and exit, it's valid to assume that the changes being undone on exit are just the ones implemented in that session. But that's not what happens - all changes are cleared on exit.

Perhaps the "Undo changes on exit" button should just be renamed "Clear all settings on exit", or "Clear overrides on exit".

**Comment by KarenGhavam-lunarG** [comment]
New vkconfig in next release no longer behaves this way or uses this model anymore.
