### ISSUE TITLE
Modify Getting Started to search the built layers path and not the entire SDK.

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#897]
> "Enable other layers" section, step 3 says:
> 
> Check the "Use custom layer paths" box on the top left. Then click the "Search" button and navigate to the SDK in the popup window. Select the SDK's directory. A popup will ask you to confirm the layers that were found by the SDK. Click ok on this popup.
> 
> vkconfig finds these three layers in two different locations in SDK:
> 

![screenshot](https://user-images.githubusercontent.com/23323159/51400329-f706a780-1afc-11e9-8f01-4a065616ac36.png)

> vkconfig is just searching blindly through the SDK for layer json files

> all of the layers are in x86_64/etc/explicit_layer.d so maybe just modify the instructions to search that path?

**Comment by KarenGhavam-lunarG** [comment]
As designed. Closing.
