### ISSUE TITLE
Add groups of settings to layer_info.json

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#898]
Rather than wait for a UI overhaul, start with something small - "meta settings" in layer_info.json which bundle other settings for a layer.  On discussion with @mark-lunarg , he thinks a good set of bundles/profiles for other settings would be:

Lightweight Validation
- Load Only Khronos Layer
- Disable Thread Safety feature
- Disable Unique Handles feature
- Disable Core Checks feature

Standard Validation
- Load Only Khronos Layer
- Disable Thread Safety feature

Synchronization Validation
- Load Only Khronos Layer
- Enable Synchronization feature
- Disable Object Lifetimes feature
- Disable API Parameters feature
- Disable Core Checks feature
- Disable Unique Handles feature

GPU-Assisted Validation
- Load Only Khronos Layer
- Enable GPU-Assisted feature
- Disable Object Lifetimes feature
- Disable API Parameters feature
- Disable Core Checks feature
- Disable Unique Handles feature
- Disable Thread Safety feature

These all operate within KHRONOS_validation, so probably these could be "profiles" within KHRONOS_validation settings for now.

**Comment by KarenGhavam-lunarG** [comment]
Will be in next release of vkconfig
