### ISSUE TITLE
vkconfig: improve layout efficiency and expansion

### ISSUE THREAD

**Issue by bradgrantham-lunarg** [LunarG/VulkanTools#899]
At least on Ubuntu, the Layer Settings pane typically needs to be expanded to have easy (non-scrolling) access to the settings - at the original size, with any settings enabled, a horizontal scroll bar appears. It would be great if the window started off with a little more horizontal room for settings (or a different layout with less initial room for the other panes).

As the user expands the window, though, all the panes expand, rather uselessly (generally, none of the layer lists need to be expanded, nor do the layer locations). More sophistication (so the panes with scroll bars expand first, then if there are no scroll bars everything expands equally) would be helpful.

**Comment by KarenGhavam-lunarG** [comment]
Vkconfig is currently under major UI redesign and implementation. The next release (pretty soon) is different enough that this issue probably does not apply anymore. So I am going to close this and we can enter new issues against the new vkconfig when released.
