### ISSUE TITLE
DevSim Layer: integration with vkConfig

### ISSUE THREAD

**Issue by mikew-lunarg** [LunarG/VulkanTools#900]
(Edited and moved from https://github.com/LunarG/Projects/issues/142 at @bradgrantham suggestion)

DevSim currently gets settings via environment variables.  It will be enhanced to get settings from vk_layer_settings.txt, see #873.  Need to document precedence between envars and settings, if both are active.

DevSim usemodel is distinct from both explicit and implicit layers (a separate category?)  It is not loaded by the app, so not explicit.  It is not always loaded before app startup, so not implicit.  It is only loaded before app startup when enabled by envars.  So maybe a "conditional implicit layer, disabled by default"?  vkConfig's interface could make this an easier concept.

DevSim is sensitive to it's placement in the layer stack.  Ideally it is "right next to the driver", so it can cleanly override queries of the driver.  There are other layers (e.g. Optimus) that also expect to be "right next to the driver".  The relative order of Optimus and DevSim depends on the usecase.

**Comment by mark-lunarg** [comment]
Can this be closed?

**Comment by mikew-lunarg** [comment]
Overdue for closing
