### ISSUE TITLE
VIA: Report old drivers being dropped by the loader

### ISSUE THREAD

**Issue by lenny-lunarg** [LunarG/VulkanTools#901]
In today's SI meeting, we agreed on a change to loader behavior that will cause the loader to drop very old drivers when newer ones are present. The loader will log a message when ignoring old drivers so that applications can see what is happening. We we need to make sure that vulkaninfo is capable of reporting this warning.

At the very least, VIA will need to pass on this warning message so that someone who runs it can see the message. It may also be useful provide some sort of hint that this can be fixed by updating drivers. I'll post a link to the loader PR that intrudces this behavior once I open it (which should happen shortly).

**Comment by davidlunarg** [comment]
Do not plan to address this issue. The changes would require the creation of a separate layer and driving finding library that would be used by both the loader and via. This would be a high-effort change, with minimal return.
