### ISSUE TITLE
vkconfig with no layers causes vulkaninfo error

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#914]
Remove items from the left column, click save, run vulkaninfo. Error is:
ERROR: [Loader Message] Code 0 : loader_validate_instance_extensions: Instance extension VK_EXT_validation_features not supported by available ICDs or enabled layers.
c:\vulkansdkbuild\workspace\khronos-tools\repo\vulkaninfo\vulkaninfo.c:967: failed with VK_ERROR_EXTENSION_NOT_PRESENT
Click on clear in vkconfig, run vulkaninfo. Works OK.

I also see this when enabling apidump or assistant layer from vkconfig and running vulkaninfo

Found during SDK 121 testing

**Comment by charles-lunarg** [comment]
When VkConfig has custom layer paths enabled, it saves the path location in the VkLayer_override.json and in loaderScanForImplicitLayers it opens the path and loads any layers found as if they are implicit layers, not bothering to check if they should be loaded. This in turn makes all the extensions required by these non-implicit layers also be loaded when queried by vkEnumerateInstanceExtensionProperties. 
This seems to be a loader issue, and so the issue should be moved to the loader repo.
