### ISSUE TITLE
vkreplay: auto orientation not work

### ISSUE THREAD

**Issue by calfcalf88** [LunarG/VulkanTools#918]
replay landscape vktrace file while android phone in portrait mode, after resize_window, error log:
09-18 15:18:14.414   600   600 D SurfaceFlinger: duplicate layer name: changing com.example.vkreplay/android.app.NativeActivity to com.example.vkreplay/android.app.NativeActivity#1
09-18 15:18:14.415   600   600 D SurfaceFlinger: duplicate layer name: changing Background for - com.example.vkreplay/android.app.NativeActivity to Background for - com.example.vkreplay/android.app.NativeActivity#1
and follow many logs like below:
09-18 15:18:14.567   600   773 E BufferQueueProducer: [com.example.vkreplay/android.app.NativeActivity#0] dequeueBuffer: BufferQueue has been abandoned
09-18 15:18:14.567 10202 10347 E vulkan  : dequeueBuffer failed: No such device (-19)
09-18 15:18:14.567 10202 10347 E vkreplay: Return value VK_ERROR_SURFACE_LOST_KHR from API call (vkAcquireNextImageKHR) does not match return value from trace file VK_SUCCESS.
09-18 15:18:14.567 10202 10347 W vkreplay: API call (vkAcquireNextImageKHR) returned failed result VK_ERROR_SURFACE_LOST_KHR
09-18 15:18:14.567 10202 10347 E vkreplay: Failed to replay packet_id 164, with global_packet_index 722.0

android ro.build.version.release is 8.1.0

**Comment by davidlunarg** [comment]
Have you tried gfxreconstruct (https://github.com/LunarG/gfxreconstruct)? vktrace/replay is in the process of being deprecated and replaced with gfxreconstruct. We are constantly making the tradeoff between fixing a bug in vktrace/replay or doing more development in gfxreconstruct, and more often now, we opt for gfxreconstruct.

**Comment by calfcalf88** [comment]
YES, gfxreconstruct works well, thanks.

**Comment by calfcalf88** [comment]
i remove property 'android:exported="true"' from AndroidManifest.xml, then vkreplay works also fine.

**Comment by calfcalf88** [comment]
change property 'android:targetSdkVersion' from 23 to 27 same as gfxrecon set in AndroidManifest.xml, seems vkreplay work fine also.
