### ISSUE TITLE
vktrace UnmapMemory of coherent memory should always serialize on Linux OS

### ISSUE THREAD

**Issue by ardaLunarG** [LunarG/VulkanTools#93]
This issue is fixed on windows with Page Guard feature.
vktrace UnmapMemory of coherent memory should always serialize #61

As Page Guard does not work on Linux it needs to be fixed for Linux OS

**Comment by davidlunarg** [comment]
Fixed in c8e40ffd9cadd2d8bf5d9b0f9b6db6023595a144
