### ISSUE TITLE
VIA should not report LunarG Vulkan SDKs

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#930]
See issue: https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/issues/191

The Vulkan Installation Analyzer says "LunarG Vulkan SDKs". Should probably just say "Vulkan SDKs"

**Comment by lunarpapillo** [comment]
Also, even with `VULKAN_SDK` set in the environment, VIA reports **No installed SDKs found**.

**Comment by lunarpapillo** [comment]
At least as per SDK 1.2.131.1.

**Comment by davidlunarg** [comment]
Created pull request to change wording in output.

@lunarpapillo: The problem you reported for SDK 1.2.131.1 above seems like a different problem. I haven't been able to reproduce it. Can you give details?
