### ISSUE TITLE
LunarG Validation Layers Don't Flag Absent Extensions

### ISSUE THREAD

**Issue by ROTARTSI82** [LunarG/VulkanTools#933]
*DISCLAIMER: I'm still learning Vulkan!*

I think that the validation layers should flag any function calls to uninitialized extensions. For example, in some code I was calling `vkCreateSwapchainKHR` without including the swapchain extension in the logical device creation. Instead of the validation layer flagging it, it just segfaulted, making me spend *ahem* a considerable amount of time debugging. I just think It would be nice if the validation layers checked for this kind of thing...

Also: Should I post this issue to the https://github.com/KhronosGroup/Vulkan-Docs/ repository or is this the right place for this? I'm using the LunarG standard validation in addition to Khronos Validation.

**Comment by KarenGhavam-lunarG** [comment]
This issue should be posted in the [KhronosGroup Validation Layer repository](https://github.com/KhronosGroup/Vulkan-ValidationLayers).

**Comment by ROTARTSI82** [comment]
Thank you posted an issue there.
