### ISSUE TITLE
vkconfig not working in Admin (IsHighIntegrity) 

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#935]
This was originally submitted against the Loader (by @dor666), but is a vkconfig issue. Resolution on loader repository: 

> So in my opinion this is really a vkconfig issue. The loader should stop searching the user registry when it is run as administrator. I admit this is unusual on a system where all programs are run as administrator, but it is important on other systems.

> I believe that vkconfig needs to have the ability to write to the HKEY_LOCAL_MACHINE registry, instead. I think vkconfig could be changed so it either gives you the option to write to the registry (which requires adminstrator permissions) or it would automatically do so if run with administrative privileges. As a result, I'm closing this issue, but I think you should reopen it in LunarG/VulkanTools.

**Comment by KarenGhavam-lunarG** [comment]
@richard-lunarg We should assess if this issue is resolved or still exists in the new vkconfig2

**Comment by richard-lunarg** [comment]
I fail to see how writing to HKEY_LOCAL_MACHINE would change the behavior in question, where an environment variable is or isn't allowed to determine if a DLL can be loaded. Even if vkconfig is run as administrator, it only writes to HKEY_CURRENT_USER.

**Comment by charles-lunarg** [comment]
The issue is that when running an application as an administrator, the loader doesn't load any dll's which didn't require administrative mode to install. So in admin mode, the loader will search for layers in HKEY_LOCAL_MACHINE but not HKEY_CURRENT_USER, so as to prevent malicious layers being loaded when the the application has admin privileges. This is a problem for current and past vkconfig, since if it only writes to HKEY_CURRENT_USER, it wont ever be activated if the vulkan application is being run as an administrator.

**Comment by richard-lunarg** [comment]
After discussing with Charles, I grok the issue now, and agree with Lenny's original recommendation. I'll add a "write to HKEY_LOCAL_MACHINE" option to vkconfig2 to accommodate this. I won't mark this as closed until tested and verified that this resolves the issue. This issue may also exist on Mac and Linux in other guises, so I'm leaving this open until I have a good handle on it on all platforms.

**Comment by dor666** [comment]
I see it writes to HKEY_LOCAL_MACHINE in v1.2.148 :
```
void Configurator::AddRegistryEntriesForLayers(QString qsJSONFile, QString qsSettingsFile) {
    // Layer override json file
    HKEY key;
    HKEY userKey = (_running_as_administrator) ? HKEY_LOCAL_MACHINE : HKEY_CURRENT_USER;
```

And it loads layers correctly, but there is a problem with settings.
Vulkan-ValidationLayers are hardcoded to use HKEY_CURRENT_USER:

```
string ConfigFile::FindSettings() {
    struct stat info;

#if defined(WIN32)
    // Look for VkConfig-specific settings location specified in the windows registry
    HKEY hive;
    LSTATUS err = RegOpenKeyEx(HKEY_CURRENT_USER, "Software\\Khronos\\Vulkan\\Settings", 0, KEY_READ, &hive);
    if (err == ERROR_SUCCESS) {
```

Should I create another issue for ValidationLayers?

**Comment by richard-lunarg** [comment]
>Should I create another issue for ValidationLayers?

Yes, the new functionality in vkconfig is supported by the loader, but was not implemented in ValidationLayers.

**Comment by dor666** [comment]
Hi, ValidationLayers are fixed.
Does api_dump layer need same fix or it reuses code for settings lookup?

**Comment by christophe-lunarg** [comment]
This issue is resolved
