### ISSUE TITLE
Mac vkvia should be able to find installed SDK

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#944]
On the MacBook, `/Applications/vkconfig.app` shows, under the **Installation Analyzer** tab, in the **LunarG Vulkan SDKs** section, that "No installed SDKs found".

This was after running `sudo python3 install_vulkan.py`,m so I would have expected it to identify the installed SDK.

**Comment by KarenGhavam-lunarG** [comment]
@jeremyk-lunarg I believe this is no longer an issue on recent macOS SDKs. Can you confirm?

**Comment by jeremyk-lunarg** [comment]
I still need to add this feature to vkvia.
It can find the SDK if the `VULKAN_SDK` environment variable is set, but it doesn't look in system directories yet.

**Comment by jeremyk-lunarg** [comment]
Fixed with merge of PR #1009
