### ISSUE TITLE
VIA:  Missing table tag in generated HTML

### ISSUE THREAD

**Issue by karl-lunarg** [LunarG/VulkanTools#947]
Reference: https://vulkan.lunarg.com/issue/view/5e22e47886da8143aabe5854

When there is an error while running external tests, the generated HTML is missing an open table tag.

```html

   <H1 class="section"><center>External Tests</center></h1>
        <tr class="odd">
            <td class="odd">Failed to find either 'vkcube' or 'cube' executables</td>
            <td class="odd">FAILURE</td>
        </tr>
    </table>
```
This causes most browsers to not render this section, complicating the interpretation of VIA results.

A count of table open and close tags over the entire file reveals that there is one more close than open.

I'm guessing that when the external tests are successful, the HTML is correct since a missing section would have been noticed more easily.

**Comment by davidlunarg** [comment]
Fixed in commit https://github.com/LunarG/VulkanTools/pull/1723 as part of fixing other issues.
