### ISSUE TITLE
via: Misleading information about failed external tests

### ISSUE THREAD

**Issue by karl-lunarg** [LunarG/VulkanTools#948]
Reference: https://vulkan.lunarg.com/issue/view/5e22e47886da8143aabe5854

VIA reports that it can't _find_ the executable, even when it _can_ find it and there is a failure on execution.

There should be separate error messages for not finding something and getting a failure when executing that something.

Or at least say that it can't find something OR had a problem running it.

**Comment by davidlunarg** [comment]
This was fixed in pull request https://github.com/LunarG/VulkanTools/pull/1723
