### ISSUE TITLE
vkreplayer crashed on android

### ISSUE THREAD

**Issue by jyangsh** [LunarG/VulkanTools#95]
I tried to run the vkreplayer on android on an armeabi-v7a device. But it crashed with the message below.

--------- beginning of crash
09-28 13:31:48.768  5860  5860 E AndroidRuntime: FATAL EXCEPTION: main
09-28 13:31:48.768  5860  5860 E AndroidRuntime: Process: com.example.vkreplay, PID: 5860
09-28 13:31:48.768  5860  5860 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.vkreplay/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.example.vkreplay-1/lib/arm/libvkreplay.so
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-28 13:31:48.768  5860  5860 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.example.vkreplay-1/lib/arm/libvkreplay.so
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.NativeActivity.onCreate(NativeActivity.java:182)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
09-28 13:31:48.768  5860  5860 E AndroidRuntime:        ... 9 more
09-28 13:31:48.771  1013  1024 W ActivityManager:   Force finishing activity com.example.vkreplay/android.app.NativeActivity
09-28 13:31:48.783  1013  5875 W DropBoxManagerService: Dropping: data_app_crash (1483 > 0 bytes)

Indeed, the "libvkreplay.so" is under the folder, /data/app/com.example.vkreplay-1/lib/arm.

root@firefly:/ # ls -la /data/app/com.example.vkreplay-1/lib/arm
-rwxr-xr-x system   system     984788 1979-12-31 14:57 libVkLayer_api_dump.so
-rwxr-xr-x system   system    1607424 1979-12-31 14:56 libVkLayer_core_validation.so
-rwxr-xr-x system   system     845524 1979-12-31 14:57 libVkLayer_image.so
-rwxr-xr-x system   system     480980 1979-12-31 14:57 libVkLayer_object_tracker.so
-rwxr-xr-x system   system     689876 1979-12-31 14:57 libVkLayer_parameter_validation.so
-rwxr-xr-x system   system     833244 1979-12-31 14:57 libVkLayer_screenshot.so
-rwxr-xr-x system   system     476888 1979-12-31 14:57 libVkLayer_swapchain.so
-rwxr-xr-x system   system     923348 1979-12-31 14:57 libVkLayer_threading.so
-rwxr-xr-x system   system     550624 1979-12-31 14:57 libVkLayer_unique_objects.so
-rwxr-xr-x system   system     231156 1979-12-31 14:57 libVkLayer_vktrace_layer.so
-rwxr-xr-x system   system     555148 1979-12-31 14:58 libvkreplay.so

**Comment by cnorthrop** [comment]
There are known issues when trying to trace on 32-bit Linux.  You should have seen other errors and warnings when recording a 32-bit trace.  I believe only 32-bit Windows is supported at the moment.

Are you able to use an arm64 build?

We'd like to get 32-bit supported soon, but increasing 64-bit quality is a high priority.

**Comment by cnorthrop** [comment]
After talking with folks today, we're going to prioritize getting 32-bit supported.

Out of curiosity, did you record the trace you are trying to replay using 32-bit vktrace?

**Comment by jyangsh** [comment]
Yes, the vktrace32 can be built with "-DBUILD_X64=Off". I have captured a 32-bit trace file from the cube demo, but I cannot replay it because the vkreplayer crashed on the android.

[cube0.vktrace.zip](https://github.com/LunarG/VulkanTools/files/500006/cube0.vktrace.zip)

**Comment by jyangsh** [comment]
BTW: is it possible to support android studio build? : )

**Comment by jyangsh** [comment]
I found that it may be related to this line, [https://github.com/LunarG/VulkanTools/blob/master/build-android/jni/Android.mk#L297](url).

The libvkreplay.so can be loaded after the line "LOCAL_SHARED_LIBRARIES += VkLayer_vktrace_layer" is removed.

But another issue occurs, it looks the trace file may be bad, the fileHeader.tracer_count is zero.

--------- beginning of system
09-30 06:43:52.444  2043  2058 I vkreplay: argc = 5
09-30 06:43:52.444  2043  2058 I vkreplay: argv[0] = vkreplay
09-30 06:43:52.444  2043  2058 I vkreplay: argv[1] = -v
09-30 06:43:52.444  2043  2058 I vkreplay: argv[2] = full
09-30 06:43:52.444  2043  2058 I vkreplay: argv[3] = -t
09-30 06:43:52.444  2043  2058 I vkreplay: argv[4] = /sdcard/cube0.vktrace
09-30 06:43:52.450  2043  2058 E vkreplay: No API specified in tracefile for replaying.
09-30 06:43:52.450  2043  2058 D vkreplay: vkreplay_main returned -1
09-30 07:09:38.345  2292  2306 I vkreplay: argc = 5
09-30 07:09:38.345  2292  2306 I vkreplay: argv[0] = vkreplay
09-30 07:09:38.345  2292  2306 I vkreplay: argv[1] = -v
09-30 07:09:38.345  2292  2306 I vkreplay: argv[2] = full
09-30 07:09:38.345  2292  2306 I vkreplay: argv[3] = -t
09-30 07:09:38.345  2292  2306 I vkreplay: argv[4] = /sdcard/cube0.vktrace
09-30 07:09:38.346  2292  2306 E vkreplay: The tracer count = 0.
09-30 07:09:38.346  2292  2306 E vkreplay: No API specified in tracefile for replaying.
09-30 07:09:38.346  2292  2306 D vkreplay: vkreplay_main returned -1

**Comment by cnorthrop** [comment]
Yes, that's the error I'm seeing (zero tracer_count).  I hadn't run into the shared library problem, but I'll double check that any vktrace source/libs are needed during replay.  There is some crossover between the tools.

**Comment by jyangsh** [comment]
I guess that zero tracer_count issue may be related to issue #63. The different alignment of uint64_t type on x86 and arm 32bit is causing the issue. x86_64 and arm64 should not hit this issue because they both align the uint64_t to 8 bytes. But x86 and arm32 may meet this issue because x86 aligns uint64_t to 8 bytes, but arm32 aligns it to 4 bytes.

**Comment by davidlunarg** [comment]
We currently make sure that the beginning of all Vulkan structures in the trace file align to 4 bytes. It wouldn't be difficult to change it to align on 8 bytes. It would result in slightly larger trace files, but might address this difference between x86 and arm32.

**Comment by cnorthrop** [comment]
I have some experiments on my disk that get cube trace/replay working on arm32.  Right now I'm just padding structs and rearranging members of vktrace_trace_packet_identifiers.h, but it gets things off the ground and cube can be traced and replayed correctly.  I believe that confirms we've got a problem with struct alignment difference between compilers/architectures.  I'll get a real fix in place soon.

**Comment by jyangsh** [comment]
fixed by commit 4e1c6ce2ef4ef04af32ed38384e4bf8afb927e4b.

**Comment by jyangsh** [comment]
With line, https://github.com/LunarG/VulkanTools/blob/master/build-android/jni/Android.mk#L297, the crash still happens.

--------- beginning of crash
10-24 03:04:56.434  2027  2027 E AndroidRuntime: FATAL EXCEPTION: main
10-24 03:04:56.434  2027  2027 E AndroidRuntime: Process: com.example.vkreplay, PID: 2027
10-24 03:04:56.434  2027  2027 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.vkreplay/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.example.vkreplay-1/lib/arm/libvkreplay.so
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.example.vkreplay-1/lib/arm/libvkreplay.so
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:182)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
10-24 03:04:56.434  2027  2027 E AndroidRuntime: 	... 9 more
10-24 03:04:56.440  1009  1216 W ActivityManager:   Force finishing activity com.example.vkreplay/android.app.NativeActivity

**Comment by ardaLunarG** [comment]
@jyangsh is this issue still happening?

**Comment by cnorthrop** [comment]
@jyangsh, I'll help you test the PR once master builds for Android again.  I'll try to get some time to focus on it this week.

-C
