### ISSUE TITLE
LunarG icon on vkconfig is invisible in Dark Mode

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#953]
Under Applications, the icon shown for the vkconfig program is primarily black, and then nearly indistinguishable from the background when in macOS Dark Mode.

We should provide an icon that is visible in either Light Mode or Dark Mode.

**Comment by lunarpapillo** [comment]
For completeness... this issue persists at SDK 1.2.135.

**Comment by lunarpapillo** [comment]
Oh, and the LunarG icon is very small, and difficult to discern even in Light Mode when in any small-icon view (e.g. list view).

**Comment by KarenGhavam-lunarG** [comment]
@richard-lunarg This still applicable with new vkconfig?

**Comment by richard-lunarg** [comment]
The new vkConfig uses the Red Vulkan Icon. If overruled, it will be the blue LunarG logo. In either case, the black icon on a clear background will show up fine now in dark mode.
