### ISSUE TITLE
Request for vk.xml to be added to SDK package

### ISSUE THREAD

**Issue by PatrickPurcell** [LunarG/VulkanTools#957]
Is there any chance that the vk.xml associated with a particular SDK version can be packaged with the SDK?  I'm working with lots of generated code using the vk.xml and being able to simply read the vk.xml from the SDK package would allow me to remove build steps that fetch the vk.xml.  Thanks.

**Comment by KarenGhavam-lunarG** [comment]
Could you submit this issue to the SDK issue tracker at vulkan.lunarg.com?

**Comment by PatrickPurcell** [comment]
Absolutely, thanks
