### ISSUE TITLE
Remove reference to QtWebengine in "about" for vkconfig

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [LunarG/VulkanTools#961]
With removal of the dependency on the QtWebengine, we need to remove it's reference in the "about vkconfig" dialogue box. The remaining information needs to stay there/be available per the Qt licensing requirements.

**Comment by richard-lunarg** [comment]
This has been removed from the VkConfig 2.0 project.

**Comment by KarenGhavam-lunarG** [comment]
ok. then I will close this issue.
