### ISSUE TITLE
No layer factory template in SDK.

### ISSUE THREAD

**Issue by dor666** [LunarG/VulkanTools#963]
As stated here: https://vulkan.lunarg.com/doc/sdk/1.2.131.2/windows/layer_factory.html

Layer factory should be placed here: `%VULKAN_SDK%\Templates\Visual Studio 201x\VulkanLayer.zip`

But it's not:
![image](https://user-images.githubusercontent.com/1740971/75325625-6c54b800-5879-11ea-9698-0c6e519eca78.png)

I saw it in "1.1.126" but not in "1.1.130" and "1.2.131.2".

**Comment by shannon-lunarg** [comment]
The VulkanLayer template is now included in the 1.2.135.0 Vulkan SDK
