### ISSUE TITLE
vkVIA : absence of settings file is not a failure

### ISSUE THREAD

**Issue by mikew-lunarg** [LunarG/VulkanTools#981]
Under "Vulkan Layer Settings File", it reports "Failed to open settings file"; a missing setting is not a failure (although the attempt to open the file failed).

Suggest "File not found", to be less alarmist, analogous to other VIA message (e.g.: No .so files found; No such folder)

**Comment by davidlunarg** [comment]
Fixed in pull #1722 and merged.
