### ISSUE TITLE
vkreplay error: Unable to load xcb library.

### ISSUE THREAD

**Issue by haxpor** [LunarG/VulkanTools#983]
Followed along with instruction of `vktrace` and `vkreplay` [here](https://vulkan.lunarg.com/doc/sdk/latest/linux/getting_started.html).

But for `vkreplay -o vkcube_trace.vktrace -l 2`, it output the following error

```
vkreplay error: Unable to load xcb library.
```

I checked that my `LD_LIBRAY_PATH` points to the proper location of `lib` bundled along side Vulkan SDK latest version as of now of `vulkansdk-1.2.131.2`.

My system is Ubuntu 19.10, with kernel 5.3.18-050318-generic.

**Comment by davidlunarg** [comment]
vkreplay is trying to load the shared library libvkdisplay_xcb.so and is not finding it. Is that library in your LD_LIBRARY_PATH or the current directory?

**Comment by haxpor** [comment]
Thanks for reply David. I have such path (checked and there is `libvkdisplay_xcb.so` in it) set to `LD_LIBRARY_PATH` before executing the command. It still show such error.

I tried executing it at the same directory of that shared library, or elsewhere. Both shown the same error message.

**Comment by davidlunarg** [comment]
You did source the setup-env.sh file, right?

What is the output of the following commands:

  env | grep VULKAN
  env | grep VK
  echo $LD_LIBRARY_PATH
  ls $VK_LAYER_PATH

Also what is the contents of each directory in $LD_LIBRARY_PATH?

**Comment by haxpor** [comment]
I did set various environment variables myself, not use `setup-env.sh` though.

`env | grep VULKAN`

```
VULKAN_SDK=/home/haxpor/Data/src/vulkansdk-1.2.131.2/x86_64
```

`env | grep VK`

```
VK_LAYER_PATH=/home/haxpor/Data/src/vulkansdk-1.2.131.2/x86_64/etc/vulkan/explicit_layer.d
```

`echo $LD_LIBRARY_PATH`

```
/home/haxpor/Data/src/vulkansdk-1.2.131.2/x86_64/lib
```

`ls $VK_LAYER_PATH`

```
/home/haxpor/Data/src/vulkansdk-1.2.131.2/x86_64/etc/vulkan/explicit_layer.d
```

**Comment by davidlunarg** [comment]
It all looks fine. A couple more things to check, and then I think I'm out of ideas.

Might one of the environment variables have a hidden character in its value? Or a trailing space? I would suggesting using the setup-env.sh script to make sure this is not the case.

Is LD_PRELOAD set? It might cause the wrong version of a library to be used.

**Comment by haxpor** [comment]
There is no `LD_PRELOAD` set. Tried sourcing from `setup-env.sh` and didn't work the same.

I solved it by `strace vkreplay -o vkcube_trace.vktrace -l 2` to track what's going on.
I saw the following dumped out

```
...
stat("/usr/lib/x86_64", 0x7ffc5f1c2aa0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64/libxcb-ewmh.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64", 0x7ffc5f1c2aa0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libxcb-ewmh.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
munmap(0x7fac93723000, 114202)          = 0
munmap(0x7fac92f9d000, 2109784)         = 0
munmap(0x7fac92f8b000, 69736)           = 0
...
```

What I need is to install another package called `libxcb-ewmh2`, then things work properly now.
Thanks for your help David!
