### ISSUE TITLE
Devsim: Add setting to device simulation to use device extensions

### ISSUE THREAD

**Issue by sfricke-samsung** [LunarG/VulkanTools#985]
This was from a recent issue I had writting a test for Validation Layers where running the DevSim layer with the MockICD exposes all extensions to be supported which is not good when testing Validation Layers with devsim as it gives a less accurate test coverage.

From [what the source seems to be doing](https://github.com/LunarG/VulkanTools/blob/master/layersvt/device_simulation.cpp#L1386) it just returns what the driver supports. I realize for anyone who is using this to test their code works on real hardware, they will run into issues if devsim starts passing down unknown extensions function.

Really just want a `lunarg_device_simulation.device_extensions` setting that is deafult to `false` but would allows the JSON file extension list to get returned and then an awesome bonus if it can be setup to use `true` as default for Validation Layer testing so there is more realistic coverage from using the device profiles (or at least raise the issue in that repo)

Thanks

**Comment by mikew-lunarg** [comment]
@sfricke-samsung Thanks, added to the umbrella tracking issue.

**Comment by jeremyk-lunarg** [comment]
PR to add feature merged.

**Comment by sfricke-samsung** [comment]
@jeremy-lunarg Awesome! Will find time to in near future to try to hook this up with the Validation Layers to allow better MockICD test coverage!
