### ISSUE TITLE
vktraceviewer and vkreplay fails to replay trace file on Linux(Ubunt 16.04)

### ISSUE THREAD

**Issue by edrickhong** [LunarG/VulkanTools#99]
The issue seems to be with vkCreateSurfaceXcb. It claims that the xcb connection passed to it is null so it always fails the present. I will admit that I did a blind copy paste from this git repo to the vulkan sdk so the issue might be there. I will make another post if this is a non-issue.

**Comment by davidlunarg** [comment]
I am able to trace and replay a program that uses vkCreateXcbSurfaceKHR. If your are still experiencing the problem after you verify a source issue is not the cause, could you please provide us with a program so we can duplicate the problem?

**Comment by davidlunarg** [comment]
Haven't heard back on this. Closing the issue, please reopen if this if you are still seeing the problem.
