### ISSUE TITLE
VkPositiveLayerTest.ExternalMemory

### ISSUE THREAD

**Issue by fabienjean** [LunarG/VulkanTools#990]
Hi, 
Result of VkPositiveLayerTest.ExternalMemory is OK but, **i have check the buffer_output and it's empty. not contain values put in buffer_input
Thanks for your help

**Comment by KarenGhavam-lunarG** [comment]
Your issue talks about VkPositiveLayerTest.ExternalMemory. I believe (but am not sure) that is a test for the validation layers. This repository is not for the validation layers.
