### ISSUE TITLE
api dump: Add option to remove thread/frame messages from dump

### ISSUE THREAD

**Issue by null77** [LunarG/VulkanTools#992]
I'd like to omit all these messages from my simplified dump:

```
Thread 18446744073709551615, Frame 0:
```

It makes the task of diffing two simplified dumps easier. Is it possible to add an option?

**Comment by davidlunarg** [comment]
It's very doable, but does require that the change be made to three different code paths - apidump supports text, html, and json output.

A grep/sed command on the resulting output could be used to remove the Thread/Frame information.

Given the grep/sed workaround, this feature would not be a high priority.

However, we will gladly accept a pull request.  :-)

**Comment by null77** [comment]
OK. FWIW I did try to build from source on Windows and had some issues getting the build to complete following the official instructions. They might be out of date.

**Comment by davidlunarg** [comment]
The instructions in BUILD.md are current. First make sure you install the packages listed under "Windows System Requirements". Then the easiest way to build is to follow the instructions under "Building Dependent Repositories with Known-Good Revisions". Run those commands from the VS Dev Env prompt.

**Comment by charles-lunarg** [comment]
For whatever reason this issue wasn't updated when PR #995 was merged.
Could you look at the changes @null77 and confirm if they work as expected?

**Comment by null77** [comment]
Will try to look soon. Unfortunately I don't recall how I was running the tool and why I was seeing thread ID problems.

**Comment by null77** [comment]
Ah, actually, I have used the executor to run API dump recently and was able to diff cleanly. I think this was fixed back in #995 . Thanks for the fix!
