### ISSUE TITLE
screenshot layer crashes on some programs when trying to save a PPM file

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#996]
Using some Steam games (or their corresponding **GFXReconstruct** traces) in Windows, attempting to use the screenshot layer causes a failure.  The failure occurs the first time that the screenshot layer attempts to write a PPM file, and can manifest as a `VK_ERROR_DEVICE_LOST`, a program hang (Windows reports that the program has become unresponsive), or a Windows crash reporting `STATUS_STACK_BUFFER_OVERRUN` (the exact manifestation of the error seems to vary even with the same game or the same trace).  Most of the time a skeleton PPM file (with just the dimensions, and no image data) is created.  The exact frame number doesn't seem to matter.

These games have been observed to fail:
- DOTA2
- Strange Brigade
- Wolfenstein 2

Many other games are unaffected, suggesting that the crash depends on the specific behavior of the game.

**Comment by christophe-lunarg** [comment]
screenshot layer requires a setting to specify the output path to ensure the files are written to a writable location.

**Comment by lunarpapillo** [comment]
> screenshot layer requires a setting to specify the output path to ensure the files are written to a writable location.

If the skeleton PPM file is created, it's clear that the location was writable.

**Comment by davidlunarg** [comment]
I just tried to duplicate this issue with SDK 1.2.198.0. The screenshot layer successfully produced images for frames 100, 200, 500, and 1000. So I can't reproduce this issue. Will close.
